### ISSUE TITLE
Can't get lemur to create a certificate

### ISSUE THREAD

**Issue by timja** [Netflix/lemur#102]
I have setup lemur using lemur-docker and can't get it to create a certificate.

The error returned is: 
{"message": "'NoneType' object has no attribute 'owner'"}

I also build it from source myself and had the same error.

The http request sent was: 

```
Request:
curl 'https://app1.example.com/api/1/certificates' 
-X POST
-H 'Pragma: no-cache' -H 'Origin: https://app1.example.com'
-H 'Accept-Encoding: gzip, deflate' 
-H 'Accept-Language: en-GB,en-US;q=0.8,en;q=0.6' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36' -H 'Content-Type: application/json;charset=UTF-8' 
-H 'Accept: application/json, text/plain, */*' 
-H 'Cache-Control: no-cache' 
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0NDMwOTI1NTcsInN1YiI6MSwiZXhwIjoxNDQzMTc4OTU3fQ.o8qZ28o383YMwVCywRxTNxYTPhFDu-kHHX7yM3qDFq4'
 -H 'Cookie: session=eyJpZGVudGl0eS5hdXRoX3R5cGUiOm51bGwsImlkZW50aXR5LmlkIjoxfQ.COTCBQ.0VA8yUn1KoIoNzlKSJvmXyo8TBo'
 -H 'Connection: keep-alive'
 -H 'Referer: https://app1.example.com/' 
--data-binary '{"country":"","state":"","location":"","organization":"","organizationalUnit":"","owner":"fsdf@sadas","description":"sadsadsa","selectedAuthority":"dsadasdsad","commonName":"asdsa","extensions":{"subAltNames":{"names":[]}},"subAltType":null,"subAltValue":null}' --compressed
```

``` 
Response:
{"message": "'NoneType' object has no attribute 'owner'"}
```

Any help would be appreciated, lemur looks really cool and I would like to try it out.
Tim

**Comment by kevgliss** [comment]
Hey Tim, Do you have any logs on your docker that might help? There should be a file  /usr/local/src/lemur/lemur/lemur.log that might give us some clues.

Additionally looking at your json and whats at http://lemur.readthedocs.org/en/latest/developer/rest.html#post--certificates there seem to be a few discrepancies so it hard to say for sure which value is causing this. 

In several places we need to harden the Lemur APIs to protect against bad data and give better API messages. It looks like you found one of them!

**Comment by timja** [comment]
The log file was empty in my docker container and also the one I build from source.

Below is the output of 
```
$ docker-compose logs:
postgres_1   | LOG:  database system was interrupted; last known up at 2015-09-23 23:56:57 UTC
postgres_1   | LOG:  database system was not properly shut down; automatic recovery in progress
postgres_1   | LOG:  record with zero length at 0/16A8178
postgres_1   | LOG:  redo is not required
postgres_1   | LOG:  MultiXact member wraparound protections are now enabled
postgres_1   | LOG:  database system is ready to accept connections
postgres_1   | LOG:  autovacuum launcher started
lemurweb_1   | Creating lemurdb...
lemurweb_1   | CREATE DATABASE
lemurweb_1   | Creating the lemur user...
lemurweb_1   | CREATE ROLE
lemurweb_1   | Changing postgres password...
lemurweb_1   | GRANT
lemurweb_1   | Done changing postgres password...
lemurweb_1   | DONE CREATING lemurdb...
lemurweb_1   | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
lemurweb_1   | INFO  [alembic.runtime.migration] Will assume transactional DDL.
lemurweb_1   | INFO  [alembic.runtime.migration] Running stamp_revision  -> 1ff763f5b80b
lemurweb_1   | [+] Created 'admin' role
lemurweb_1   | [+] Added a 'lemur' user and added it to the 'admin' role!
lemurweb_1   | [+] Creating expiration email notifications!
lemurweb_1   | [!] Using LEMUR_SECURITY_TEAM_EMAIL as specified by LEMUR_SECURITY_TEAM_EMAIL for notifications
lemurweb_1   | [!] Creating 3 notifications for 30,15,2 days as specified by LEMUR_DEFAULT_EXPIRATION_NOTIFICATION_INTERVALS
lemurweb_1   | [/] Done!
lemurweb_1   | [2015-09-23 23:58:30 +0000] [37] [INFO] Starting gunicorn 19.3.0
lemurweb_1   | [2015-09-23 23:58:30 +0000] [37] [INFO] Listening at: http://0.0.0.0:8000 (37)
lemurweb_1   | [2015-09-23 23:58:30 +0000] [37] [INFO] Using worker: sync
lemurweb_1   | [2015-09-23 23:58:30 +0000] [44] [INFO] Booting worker with pid: 44
lemurweb_1   | [2015-09-23 23:58:30 +0000] [45] [INFO] Booting worker with pid: 45
lemurweb_1   | [2015-09-23 23:58:30 +0000] [46] [INFO] Booting worker with pid: 46
lemurweb_1   | [2015-09-23 23:58:30 +0000] [47] [INFO] Booting worker with pid: 47
lemurweb_1   | [2015-09-23 23:58:30 +0000] [48] [INFO] Booting worker with pid: 48
lemurweb_1   | [2015-09-23 23:58:30 +0000] [49] [INFO] Booting worker with pid: 49
```

**Comment by kevgliss** [comment]
I was able to reproduce this:

```
2015-09-23 17:19:20,546 ERROR: 'NoneType' object has no attribute 'owner' [in /Users/kglisson/Documents/Code/Python/github/forks/lemur/lemur/common/utils.py:60]
Traceback (most recent call last):
  File "/Users/kglisson/Documents/Code/Python/github/forks/lemur/lemur/common/utils.py", line 46, in wrapper
    resp = f(*args, **kwargs)
  File "/Users/kglisson/Documents/Code/Python/github/forks/lemur/lemur/certificates/views.py", line 335, in post
    role = role_service.get_by_name(authority.owner)
AttributeError: 'NoneType' object has no attribute 'owner'
```

Essentially it means that they authority you picked does not exist. In fact you didn't specify an 'authority' at all in your json only 'selectedAuthority' which is just a angular variable and is not actually used by the API.

I would ensure that the authority you created via UI (or otherwise) is in the 'authority' value of your json. Essentially Lemur doesn't create certificates only 'Authority' plugins do. When you create an authority it asks for the type of plugin you want to use (only verisign atm). When you create your "Authority" in Lemur you are creating an instance of that plugin that can then be restricted/controlled. 

After it has been created you are then able to select that authority and use it to issue certificates.

Some takeaways are I will make the 'authority' a required field. I will also add a "Creating your first certificate" guide in the docs, as I can tell it's not super clear at the moment.

Hope that helps.

**Comment by timja** [comment]
Thanks for your help
I tried to create an authority and selected the Verisign plugin I got an error there as well.
Let me know if you want to wait till you've created the guide in the docs first.

```
Request
curl 'https://192.168.99.101/api/1/authorities'
 -H 'Pragma: no-cache' 
-H 'Origin: https://192.168.99.101' 
-H 'Accept-Encoding: gzip, deflate' 
-H 'Accept-Language: en-GB,en-US;q=0.8,en;q=0.6' 
-H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36' 
-H 'Content-Type: application/json;charset=UTF-8'
 -H 'Accept: application/json, text/plain, */*' 
-H 'Cache-Control: no-cache' 
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0NDI5ODA3NjksInN1YiI6MSwiZXhwIjoxNDQzMDY3MTY5fQ.G50x0OMVLdWokB5Vj0Gptc7PlKW9QStVYq7H9XU4O1w' 
-H 'Cookie: session=eyJpZGVudGl0eS5hdXRoX3R5cGUiOm51bGwsImlkZW50aXR5LmlkIjoxfQ.COTckw._zDqboAYi9iz39X0Y3UdkJ7F27Y' 
-H 'Connection: keep-alive' 
-H 'Referer: https://192.168.99.101/' 
--data-binary '{"caType":"root","caSigningAlgo":"sha256WithRSA","caSensitivity":"medium","keyType":"RSA2048","pluginName":"verisign-issuer","caDN":{"country":"NZ","state":"NZ","location":"WLG","organization":"Datacom","organizationalUnit":"Datacom","commonName":"tim.test.datacom.co.nz"},"caName":"test","ownerEmail":"timja@datacom.co.nz","caDescription":"testing","validityStart":"2015-09-22T12:00:00.000Z","validityEnd":"2015-09-29T11:00:00.000Z","extensions":{"subAltNames":{"names":[]}},"subAltType":null,"subAltValue":null}' --compressed
```
```
Response
{"message": "Unable to load certificate"}
```

**Comment by kevgliss** [comment]
Have you configured the following settings in the lemur.conf.py?
http://lemur.readthedocs.org/en/latest/administration/index.html#authority-options
They are needed for the verisign plugin to work. 

You will also need an account with verisign for this to work and have the associated API keys.

If you still want to use the docker you will have to modify the lemur.conf.py and rebuild the docker with the command:

```
docker-compose build lemur-web
```

You would also need to edit the docker file to include the new files that the verisign plugin would need namely the VERISIGN_PEM_PATH

In file https://github.com/Netflix/lemur-docker/blob/master/web/Dockerfile#L31
```
add <path-to-verisign-pem>
```

At some point it will start to be easier to install Lemur from source so you can more easily modify it's settings.

I will work on some additional user guides and create a pull request, feedback on it would be lovely.

**Comment by timja** [comment]
Aah ok, currently I'm more looking at it for internal deployments to start with and then expanding to use the likes of Verisign and Rapidssl later.
I'll look at what it would take to use a local CA later.

I wrote a script for centos 7 which worked pretty well but wasn't as easy as docker to get going.

Thanks for your help, and I can have a look a the pull request once its up
Tim

**Comment by kevgliss** [comment]
Cool, unfortunately we haven't opensource'd our internal CA yet that has full Lemur integration. That's cool you got it working with centos!

**Comment by kevgliss** [comment]
I have #104 open for the user guides and have already merged in #103 for the bad api errors you found. Not exactly sure burying it in the User guide is the best place. But I am not sure of a better place atm.

**Comment by timja** [comment]
#104 Looks good, I think a short section in the ReadMe would be useful on Getting started, with potentially a link to the docker project as well.

Something else I noticed was that when you are Creating an Authority on the page with the plugin option the dropdown has two Verisign options which are identical.

**Comment by kevgliss** [comment]
Filed #105 for the duplicated plugin. Also updated the #104 with some more detail that Lemur doesn't issue the certificate itself.

**Comment by timja** [comment]
Cool looks good to me
