### ISSUE TITLE
If a urlContextPath is set, you can't use a different location to serve the static content

### ISSUE THREAD

**Issue by pandabuilder** [Netflix/lemur#1022]
Example: set, urlContextPath=lemur

NGINX config:

```nginx
location /lemur/api {
     proxy_pass  http://127.0.0.1:8000;
     proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
     proxy_redirect off;
     proxy_buffering off;
     proxy_set_header        Host            $host;
     proxy_set_header        X-Real-IP       $remote_addr;
     proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
 }

 location /lemur {
     root /www/lemur/lemur/static/dist;
     include mime.types;
     index index.html;
 }
```
Since the static content URLs in the html are set like this: "lemur/scripts/...", they end up translating to: "/lemur/lemur/scripts/...".

Is there any configuration option to fix this?

**Comment by kevgliss** [comment]
Unfortunately I am not familiar urlContextPath and when/how it is used. While we do have some example nginx configurations it's not meant to be exhaustive.
