### ISSUE TITLE
Running init more than once will create multiple 'default' rotation policies

### ISSUE THREAD

**Issue by jchuong** [Netflix/lemur#1046]
When you run `init`, it checks for default roles, default users, etc. and skips creating them if those are found.  However, default rotation policy ('default': 30) is created and inserted into the database every time.  This causes an issue when you try to create a certificate without a rotation policy, then the default rotation policy is used (named: "default").  This commonly occurs if you use lemur-docker to test, and then only restart the web container and keep the existing lemur-postgres container with the existing data.

The fix is to either go into the DB and remove the duplicate.  We should check if 'default' already exists (name should probably be set to unique as well).

**Comment by kevgliss** [comment]
This makes sense, rotation policy was added quite a bit after the init stuff was done. I may have missed checking for existence of the policy.
