### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by armondressler** [Netflix/lemur#1062]
I'm trying to get 0.6 to run on a CentOS 7.4 Host. The docs don't seem to mentions any other package designations apart from the ones used in Ubuntu, so this issue might arise from me missing some package.

The following lines are found in the nginx error log:

```
*42 open() "/www/lemur/lemur/static/dist/scripts/ng-table.min.js.map" failed (2: No such file or directory), client: 10.21.0.3, server: , request: "GET /scripts/ng-table.min.js.map HTTP/1.1"
*42 open() "/www/lemur/lemur/static/dist/404.html" failed (2: No such file or directory), client: 10.21.0.3, server: , request: "GET /scripts/ng-table.min.js.map HTTP/1.1"
```

The first file can be found under /www/lemur/bower_components/ng-table/dist/ng-table.min.js.map .
The second one is available under /www/lemur/lemur/static/app/404.html . 

I have followed the instructions mentioned in http://lemur.readthedocs.io/en/latest/  as there is no documentation for 0.6 available .

**Comment by kevgliss** [comment]
So the files seem to be located on the filesystem, but nginx can't find them? I'd double check your nginx.conf. Feel free to include it here.

**Comment by tetanushamster** [comment]
The files aren't located where nginx would expect them. I assume that there is a step during the installation that failed to copy them to the right location (which would be /www/lemur/lemur/static/dist/ ... in this instance).
