### ISSUE TITLE
Cannot revoke certificate. No external id found.

### ISSUE THREAD

**Issue by dmitryzykov** [Netflix/lemur#1123]
I'm trying to delete authority and imported certificate from Lemur WebUI. 
I didn't find such option for Authorities, but in Certificates, I've found `revoke`

This error for revoking authority cert (created by cryptography plugin):
<img width="1142" alt="screen shot 2018-03-22 at 1 04 11 pm" src="https://user-images.githubusercontent.com/15911918/37767139-b58bcf60-2dd1-11e8-8b71-7ce658b63432.png">

And the same error for the manually imported certificate:
<img width="1135" alt="screen shot 2018-03-22 at 1 06 46 pm" src="https://user-images.githubusercontent.com/15911918/37767200-ee755cf6-2dd1-11e8-9fcc-951d1f6f3f0c.png">

**Comment by kevgliss** [comment]
Revocation is not currently supported by the Cryptography issuer.
