### ISSUE TITLE
Failed to upload Validation Error with linuxdst plugin.

### ISSUE THREAD

**Issue by dmitryzykov** [Netflix/lemur#1132]
I'm trying to import certificate with the enabled linuxdst plugin but it shows error `Failed to upload Validation Error`. Without enabled destination plugin, this certificate was imported successfully.
<img width="1147" alt="screen shot 2018-03-24 at 7 25 09 pm" src="https://user-images.githubusercontent.com/15911918/37866874-2063cf86-2f99-11e8-85f8-d9832d5f57c4.png">

linuxdst options are correctly filled in (with help from https://github.com/Netflix/lemur/pull/1125):
<img width="957" alt="screen shot 2018-03-24 at 7 31 30 pm" src="https://user-images.githubusercontent.com/15911918/37866946-3d5a148c-2f9a-11e8-9d80-c75e9ffaca38.png">

All of these options I've sucesfully tested with ssh client:
```
root@bb2ab9843c1c:/usr/local/src/lemur# ssh root@10.2.80.4 -p 22 -i /root/.ssh/id_rsa
Last login: Wed Mar 21 09:26:02 2018 from 10.2.80.1
```

Debug is enabled in `lemur.conf.py` but in the log file no any related information.
```
CORS = True
debug = True
LOG_LEVEL = "DEBUG"
```

So my questions are:
How to figure out details about what causes this validation error?
What are the best practices to debug lemur plugins?

**Comment by kevgliss** [comment]
What's the actual json you're sending to the server? Validation errors would occur before plugin code is ever invoked.

**Comment by kevgliss** [comment]
Additionally, if you look at the json response from that request it should tell you which field failed validation.

**Comment by dmitryzykov** [comment]
I've found why the linuxdst plugin doesn't upload certs.
It's trying to get the certificate information from DB by
https://github.com/Netflix/lemur/blob/ffba1d2b852d0dacf9d8a0a12376820b61f822aa/lemur/plugins/lemur_linuxdst/remote_host.py#L44 
but when the certificate is being imported, the `upload` function is invoked **before** the certificate is stored in DB. So that the linuxdst plugin can't get certificate information.

Debug + sql request:
<img width="1152" alt="screen shot 2018-03-28 at 8 32 33 pm" src="https://user-images.githubusercontent.com/15911918/38048867-59112386-32cf-11e8-8c7a-d3cc36678ab4.png">

How can I fix this situation?
Should I just edit the plugin to use only `upload()` variables such as `name, body, private_key, cert_chain` to get certificate information?
But in this case, how can I get proper CN from this cert? 
Or maybe there is some other, more proper, way how to force `service.get_by_name(name) ` working from destination plugin?
