### ISSUE TITLE
Key rotation

### ISSUE THREAD

**Issue by rpicard** [Netflix/lemur#119]
What is the process for rotating the encryption key used with Lemur? Lets say I accidentally copy it into an IRC chat. What are my next steps?

If there isn't any tooling built-in to help with this, I think it would be a great thing to have. I haven't done much research into the best way to do it, but a good starting point might be: https://cryptography.io/en/latest/fernet/#cryptography.fernet.MultiFernet

It might make sense to look into this at the same time as issue #117 is being addressed.

**Comment by rpicard** [comment]
I can probably contribute some code to this if we come to a consensus on what this should look like.

**Comment by kevgliss** [comment]
Closed by #123
