### ISSUE TITLE
Add Hashicorp Vault plugin

### ISSUE THREAD

**Issue by RcRonco** [Netflix/lemur#1216]
Hi, it's been a long time since I worked on lemur 😁.
I wrote a plugin for Hashicorp Vault, I use it in my organization and I saw more people start using it.
Could you mention the plugin in the [Lemur Docs](http://lemur.readthedocs.io/en/latest/administration.html#rd-party-plugins)?
The previous issue: #848
https://github.com/RcRonco/lemur_vault

**Comment by kevgliss** [comment]
Sure, would you mind opening up a PR with the necessary changes?

**Comment by RcRonco** [comment]
Sure, thanks
