### ISSUE TITLE
how to enable SMTP send from email for expiry notifications

### ISSUE THREAD

**Issue by lashing** [Netflix/lemur#1232]
We are in process of setting up an SMTP based send from email for expiry notifications within lemur.

As per lemur documentation(notification section), we need to enable some flask mail settings to use SMTP for notification email. We are not sure how to use it within lemur. Can somebody provide a documentation for the same?

We have the flask already installed on our virtual environment. not sure which file to edit and what to be added on the notification plugin section.

We have the below files at notification plugin section.(/opt/lemur/lemur/notifications)

```
-rw-rw-r-- 1 lemur nginx     0 May 10 00:00 __init__.py
-rw-rw-r-- 1 lemur nginx 15225 May 10 00:00 views.py
-rw-rw-r-- 1 lemur nginx  5082 May 10 00:00 service.py
-rw-rw-r-- 1 lemur nginx  1643 May 10 00:00 schemas.py
-rw-rw-r-- 1 lemur nginx  1196 May 10 00:00 models.py
-rw-rw-r-- 1 lemur nginx  5712 May 10 00:00 messaging.py
-rw-rw-r-- 1 lemur nginx  1354 May 10 00:00 cli.py
drwxr-xr-x 2 lemur nginx  4096 May 10 00:01 __pycache__
```

Also what parameters to be passed into  /opt/lemur/lemur/config/lemur.conf.py  other than below values what we have presently?

```
# Mail Server
LEMUR_EMAIL_SENDER='SMTP'
LEMUR_EMAIL = ' '

```
Do we need to include below  parameters too as mentioned in Flask-mail Documentation?
(https://pythonhosted.org/Flask-Mail/)

```
============================
MAIL_SERVER : default ‘localhost’
MAIL_PORT : default 25
MAIL_USE_TLS : default False
MAIL_USE_SSL : default False
MAIL_DEBUG : default app.debug
MAIL_USERNAME : default None
MAIL_PASSWORD : default None
MAIL_DEFAULT_SENDER : default None
MAIL_MAX_EMAILS : default None
MAIL_SUPPRESS_SEND : default app.testing
MAIL_ASCII_ATTACHMENTS : default False
================================
```

Anyone have a detailed step by step process for this, please help..

Thank you,

**Comment by kevgliss** [comment]
Simply include (with values modified as needed):
```
MAIL_SERVER : default ‘localhost’
MAIL_PORT : default 25
MAIL_USE_TLS : default False
MAIL_USE_SSL : default False
MAIL_DEBUG : default app.debug
MAIL_USERNAME : default None
MAIL_PASSWORD : default None
MAIL_DEFAULT_SENDER : default None
MAIL_MAX_EMAILS : default None
MAIL_SUPPRESS_SEND : default app.testing
MAIL_ASCII_ATTACHMENTS : default False
```
In lemur.conf.py and they will be used. 

`LEMUR_EMAIL` should be set to the email sender. 
That's all the setup that necessary. 

Additionally be sure to cron the `notification` cli command to actually send the emails.

**Comment by lashing** [comment]
Thanks  @kevgliss

**Comment by lashing** [comment]
Thanks @kevgliss
