### ISSUE TITLE
How to test expiry notification from lemur?

### ISSUE THREAD

**Issue by lashing** [Netflix/lemur#1398]
Hi Team,

We have configured the notification email settings in lemur.conf.py as explained in issue#1232 [https://github.com/Netflix/lemur/issues/1232]. Also created notification labels for 2 days,15 days and 30 days.  Associated all certificates  with these labels. Still notifications are not being sent to the email address defined in the notification or to the certificate uploader. Uploaded a certificate of validity 5 days and getting no notifications for that too. Also we have nearly 600 certificates uploaded to lemur having different expiry dates. Not getting notifications for any of these. Sendmail and mailx seems to be working fine on the lemur server. flask settings are configured already as per the documentation. Sent a test email using mailx command with same smtp server and credentials configured lemur configuration, we are getting the email as expected. Is there a way to send a test expiry notification from lemur?

Thanks,
Lashin

**Comment by kevgliss** [comment]
Are you running the notification command? See:
http://lemur.readthedocs.io/en/latest/administration.html#notify 

Lemur rely's an external mechanism to run this (typically cron or some other scheduler).

**Comment by lashing** [comment]
Thank you!. Tried that and getting below error.

```
bin]$ ./lemur notify expirations
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertCISSourcePlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Plugin 'ACMEIssuerPlugin' may not work correctly. Required variable 'ACME_DIRECTORY_URL' is not set in Lemur's conf.
Starting to notify subscribers about expiring certificates!
[2018-06-28 18:53:15,542] ERROR in messaging: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:719)
Traceback (most recent call last):
  File "/opt/lemur/lemur/notifications/messaging.py", line 98, in send_notification
    notification.plugin.send(event_type, data, targets, notification.options)
  File "/opt/lemur/lemur/plugins/lemur_email/plugin.py", line 118, in send
    send_via_smtp(subject, body, targets)
  File "/opt/lemur/lemur/plugins/lemur_email/plugin.py", line 46, in send_via_smtp
    smtp_mail.send(msg)
  File "/opt/lemur/lib/python3.5/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/opt/lemur/lib/python3.5/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/opt/lemur/lib/python3.5/site-packages/flask_mail.py", line 156, in configure_host
    host = smtplib.SMTP_SSL(self.mail.server, self.mail.port)
  File "/usr/local/lib/python3.5/smtplib.py", line 1022, in __init__
    source_address)
  File "/usr/local/lib/python3.5/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.5/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.5/smtplib.py", line 1030, in _get_socket
    server_hostname=self._host)
  File "/usr/local/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/local/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:719)
```

**Comment by lashing** [comment]
Thanks @kevgliss  I got it working using 'lemur notify expirations' command.  I got some python flask errors when using sendgrid smtp email to send the notification email. got it fixed by removing "starttls" portion from "/opt/lemur/lib/python3.5/site-packages/flask_mail.py". Email notifications are working fine now.

**Comment by nelsonribeiro** [comment]
Hi.
I give this error when i am tryng to send notifications: 

~$ lemur notify expirations
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertCISSourcePlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Starting to notify subscribers about expiring certificates!
Finished notifying subscribers about expiring certificates! Sent: 0 **Failed: 2**

Can you help me to understand what is mean? Where can I see the detail of failed emails?
Thanks
