### ISSUE TITLE
Support sha384 and sha512 for signing

### ISSUE THREAD

**Issue by hoerup** [Netflix/lemur#1447]
Currently lemur only supports signing with sha1 and sha256.

**Comment by nilssohn** [comment]
Is this still up for grabs?

**Comment by kevgliss** [comment]
I believe so.

**Comment by ttinkr** [comment]
Still no SHA512, right? This makes it difficult to use lemur with cfssl.

**Comment by jmcrawford45** [comment]
this is supported now
