### ISSUE TITLE
How to create a certificate from a CSR with the REST API?

### ISSUE THREAD

**Issue by cdanger** [Netflix/lemur#1513]
Hello,
I could not find how to send a CSR as input to create a certificate on Lemur's REST API. Is this possible?
Thanks for your support.

**Comment by kevgliss** [comment]
You should be able to add a `csr` key to the json you send to this endpoint:

http://lemur.readthedocs.io/en/latest/developer/index.html#post--certificates

Looks like we are missing that part of the documentation. If you could open a PR to add it that would be great.

**Comment by cdanger** [comment]
OK, I'll try it to make sure I get it right, and do the PR then. Thanks for the info.
