### ISSUE TITLE
Config does not handle boolean values

### ISSUE THREAD

**Issue by explody** [Netflix/lemur#1629]
Version:  0.7.0

In the process of writing a plugin, we've run  into a bug wherein config values added to lemur.conf.py cannot reliably be set to boolean `False`.   It appears that if a var is so set, the following prevents the config from loading and yields mysterious exceptions that don't easily trace back to this problem.

```python
def validate_conf(app, required_vars):
    """
    Ensures that the given fields are set in the applications conf.
    :param app:
    :param required_vars: list
    """
    for var in required_vars:
       if not app.config.get(var):
            raise InvalidConfiguration("Required variable '{var}' is not set in Lemur's conf.".format(var=var))
```

The problem is that if CONFIG_VAR is False, `if not app.config.get(var)` will return False and raise InvalidConfiguration.

Should it not be  `if var in app.config`, which would confirm existence of the key, not let its value interfere with the validation?

**Comment by castrapel** [comment]
This seems totally reasonable. I have a PR up at https://github.com/Netflix/lemur/pull/1630 .

**Comment by castrapel** [comment]
Merged. Please let me know if this doesn't resolve your issue.
