### ISSUE TITLE
Error in notification emails

### ISSUE THREAD

**Issue by nelsonribeiro** [Netflix/lemur#1659]
Hi.
I give this error when i am tryng to send notifications:

~$ lemur notify expirations
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertCISSourcePlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Starting to notify subscribers about expiring certificates!
Finished notifying subscribers about expiring certificates! Sent: 0 **Failed: 2**

Can you help me to understand what is mean? Where can I see the detail of failed emails?
Thanks

**Comment by castrapel** [comment]
It's a bit difficult without the context of your environment. If you have Sentry enabled, you should be able to receive a stack trace of the problem. I'll try to get logging added for this.

I recommend you first check your configuration to ensure it is set correctly. We support ses and smtp. Here's an example configuration:

LEMUR_EMAIL_SENDER = 'smtp'
LEMUR_EMAIL = "lemur@yourcompany.com"
MAIL_SERVER = "smtp.yourcompany.com"

**Comment by nelsonribeiro** [comment]
Hi.
What is Sentry? Where can I see the logs? Currently I do not know where to consult, this is my big problem :(
Here is an example of my configuration:

# Mail Server
LEMUR_EMAIL_SENDER='SMTP'
LEMUR_EMAIL = 'lemur@sonaemc.com'
LEMUR_SECURITY_TEAM_EMAIL = ['security.operations@sonae.pt']
LEMUR_DEFAULT_EXPIRATION_NOTIFICATION_INTERVALS = [30, 15, 2]
LEMUR_SECURITY_TEAM_EMAIL_INTERVALS = [15, 2]

MAIL_SERVER : 'relayinterno.mch.moc.sgps'
MAIL_PORT : 25
MAIL_USE_TLS : False
MAIL_USE_SSL : False
MAIL_DEBUG : 'app.debug'
MAIL_USERNAME : None
MAIL_PASSWORD : None
MAIL_DEFAULT_SENDER : None
MAIL_MAX_EMAILS : None
MAIL_SUPPRESS_SEND : 'app.testing'
MAIL_ASCII_ATTACHMENTS : False

**Comment by castrapel** [comment]
Hi, I pushed this change which adds some logging to the messaging plugin. Please pull the latest code down and give it a shot. I'll close this for now but please re-open if it doesn't resolve your issue.
