### ISSUE TITLE
Can I remove or revoke a certificate?

### ISSUE THREAD

**Issue by nelsonribeiro** [Netflix/lemur#1660]
Hello, wen i am trying to remove a cert created by my authotity this error appens "Cannot revoke certificate. No external id found."
Otherwise, can i remove certificates easely? I dont find that option.
Thanks

**Comment by castrapel** [comment]
Lemur is designed to keep a historical record of all certificates created and we intentionally do not allow users to create certificates. This prevents users from accidentally deleting important certificates. If you must delete a certificate, you can do so in the Postgres database.

For revoking certificates, the certificate authority must support revocation, and the plugin must implement the revoke_certificate method. What authority is this for?

**Comment by nelsonribeiro** [comment]
Hi. Thanks for the explanation.
The plugin tha i am usising for the authority is the Cryptography, to create a self-signed authority.
Can I use my internal authority Microsoft CA? A plugin exists for this?
Thanks

**Comment by castrapel** [comment]
I don't see an existing plugin for that currently. Since we don't use Microsoft CA internally, the community would need to write a plugin for this. I'm sorry that we don't currently support it.

**Comment by nelsonribeiro** [comment]
Thanks!
