### ISSUE TITLE
Create plugin for Active Directory Certificate Services

### ISSUE THREAD

**Issue by braxtone** [Netflix/lemur#184]
Adding this enhancement request to see if someone is better able to work on this than I. Given the number of large companies utilizing some aspect of the Microsoft PKI tool Active Directory Certificate Services (ADCS), and at least some indication that it can be interacted with over their web services interface from looking at https://security.stackexchange.com/questions/29330/how-does-a-developer-interact-with-microsoft-certificate-web-services and https://blogs.msdn.microsoft.com/alejacma/2011/11/07/how-to-request-a-certificate-programmatically-using-the-certificate-enrollment-web-services-c/ it would be great to see a plugin for ADCS in Lemur.

**Comment by kevgliss** [comment]
This would be great to have around, unfortunately I don't have access to a ADCS environment. Will leave this open to see if someone else would like to take up the challenge.

**Comment by sirferl** [comment]
Pull Request #2255 satisfies this wish...
