### ISSUE TITLE
-c (--config) not working for start

### ISSUE THREAD

**Issue by sirferl** [Netflix/lemur#1887]
The config file specified with -c or --config when starting is not used eg.
lemur --config=/opt/lemur/lemur/lemur.conf.py start 
Only the file  ~/.lemur/lemur.conf.py is used.

**Comment by castrapel** [comment]
Thanks for reporting this, we will look in to it.

Can you use the  LEMUR_CONF=<configfile> environmental variable in the interim?

**Comment by sirferl** [comment]
Since we're only testing right now, this is no problem.

**Comment by sirferl** [comment]
Tried to reproduce the error to find cause.
Could not reproduce, start reads the --config <file> if given.
Sorry for the issue.
