### ISSUE TITLE
OpenSSL export plugin does not load on startup.

### ISSUE THREAD

**Issue by mik373** [Netflix/lemur#207]
I am trying to use a modification of the https://github.com/Netflix/lemur-docker while using 0.2 version of the Lemur release.  On startup OpenSSL export plugin does not load:

2016-01-08 21:13:58,098 ERROR: Failed to load plugin 'openssl_export':
Traceback (most recent call last):
  File "/usr/local/src/lemur/lemur/factory.py", line 162, in install_plugins
    plugin = ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named lemur_openssl.plugin

 [in /usr/local/src/lemur/lemur/factory.py:165]
2016-01-08 21:13:58,181 ERROR: Failed to load plugin 'openssl_export':
Traceback (most recent call last):
  File "/usr/local/src/lemur/lemur/factory.py", line 162, in install_plugins
    plugin = ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named lemur_openssl.plugin

 [in /usr/local/src/lemur/lemur/factory.py:165]

While AWS, Email, and Verisign plugins load just fine.  I can't see a difference amongst them that would prevent this plugin for loading.

As a related question, I'd like to extend limur_openssl to become an issuer as well. What would be the best way to package such change using the Docker container for limur-web?

**Comment by kevgliss** [comment]
It's hard to say what might be your problem, I am guessing you are running the Docker 0.2 and pulling in changes from the 0.2.1 version?

If so, I would suggest you pull in master to see if you can get that to work. 

As far as creating an issuer out of the openssl plugin, I would simply extend the current plugin and issue a pull request.

**Comment by mik373** [comment]
Actually, it looks like unless I try to modify the plugin.py for OpenSSL, the problem does not happen.  But if I try to pull it in from another place, even if it's the original file, it does not load.

Here is the fragment of my Docker file:

# Install Lemur
RUN git config --global url."https://".insteadOf git:// &&\
  cd /usr/local/src &&\
  git clone https://github.com/netflix/lemur.git &&\
  cd lemur &&\
  git fetch &&\
  git checkout 0.2
 
ADD setup.py /usr/local/src/lemur/setup.py
ADD plugins/lemur_openssl/plugin.py /usr/local/src/lemur/lemur/plugins/lemur_openssl/plugin.py

RUN cd /usr/local/src/lemur &&\
    python setup.py develop


Any idea why adding the file from outside after the checkout makes things break?

**Comment by kevgliss** [comment]
```ADD plugins/lemur_openssl/plugin.py /usr/local/src/lemur/lemur/plugins/lemur_openssl/plugin.py```

Does this mean that you are editing the plugin.py and then pulling it into the docker to run with your changes? When plugins fail to load, it's most likely because of syntax error. Which means it can't be imported and hence it can't be found. I would make sure your syntax is correct.

**Comment by mik373** [comment]
Thank you for your help thus far.  My issue was (obviously) using 0.2 source with master's setup.ry.  I have that resolved now. 

I am, however, having an issue creating an OpenSSL CA.

Here is my code:

@staticmethod
    def create_authority(options):
        """
        Creates an authority, this authority is then used by Lemur to allow a user
        to specify which Certificate Authority they want to sign their certificate.

        :param options:
        :return:
        """
        role = {'username': '', 'password': '', 'name': 'openssl'}

        openssl_cert_path = current_app.config.get("OPENSSL_DIR")
        open_ssl_ca_sub = current_app.config.get("OPENSSL_ROOT_CA_SUBJ")
        open_ssl_ca_days = current_app.config.get("OPENSSL_ROOT_CA_DAYS")

        root_ca = ensure_root_ca(openssl_cert_path, open_ssl_ca_sub, open_ssl_ca_days)


        current_app.logger.debug("cert: " + root_ca)

        return root_ca, "", [role]


root_ca returned is '--- Begin Cer'...  generated by OpenSSL


But when I try creating an Authority using my OpenSSL issuer plugin, I get 

2016-01-09 01:42:28,349 ERROR: Unable to load certificate [in /usr/local/src/lemur/lemur/common/utils.py:60]
Traceback (most recent call last):
  File "/usr/local/src/lemur/lemur/common/utils.py", line 46, in wrapper
    resp = f(*args, **kwargs)
  File "/usr/local/src/lemur/lemur/authorities/views.py", line 201, in post
    return service.create(args)
  File "/usr/local/src/lemur/lemur/authorities/service.py", line 57, in create
    cert = Certificate(cert_body, chain=intermediate)
  File "<string>", line 4, in __init__
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/state.py", line 306, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/state.py", line 303, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/src/lemur/lemur/certificates/models.py", line 253, in __init__
    cert = x509.load_pem_x509_certificate(str(self.body), default_backend())
  File "/usr/local/lib/python2.7/dist-packages/cryptography-1.1.2-py2.7-linux-x86_64.egg/cryptography/x509/base.py", line 28, in load_pem_x509_certificate
    return backend.load_pem_x509_certificate(data)
  File "/usr/local/lib/python2.7/dist-packages/cryptography-1.1.2-py2.7-linux-x86_64.egg/cryptography/hazmat/backends/multibackend.py", line 318, in load_pem_x509_certificate
    return b.load_pem_x509_certificate(data)
  File "/usr/local/lib/python2.7/dist-packages/cryptography-1.1.2-py2.7-linux-x86_64.egg/cryptography/hazmat/backends/openssl/backend.py", line 1530, in load_pem_x509_certificate
    raise ValueError("Unable to load certificate")
ValueError: Unable to load certificate


This is very similar to the Verisign issuer:
 role = {'username': '', 'password': '', 'name': 'verisign'}
        return current_app.config.get('VERISIGN_ROOT'), "", [role]


Did you just define the same string as I am returning for the verising root cert?

**Comment by kevgliss** [comment]
It depends on what you want your plugin to do.

In the simplest case I could imagine you would have some pre-created root that you wish to issue certificates off of. In that case you could simply define the ROOT or ROOT_PATH in Lemur's configuration. 

When 'creating' the authority by calling ```create_authority()``` you could return the public certificate of the root. Then when issuing the certificate with ```issuer_certificate()``` you would look to see where you are storing your root (on the filesystem)? And then issue the openssl commands using that static root.

The more complex case is that you want to support the creation of authorities. In this case your ```create_authority()``` function would not just return the static root, you would instead issue the openssl commands to create a new private key and root certificate with the appropriate extensions. Then when you go to create your leaf certificate you would look up the appropriate root and issue your certificate off of it. 

Lemur was never intended to store root private keys for a variety of reasons (typically CA root keys are stored in HSMs or other specialized devices). That being said you might be able to leverage Lemur's built in storage to store not only your root certificate but also your root private key, after all there is nothing inherently different between a root and a regular certificate (except for it's sensitivity) . You would then have a mechanism to lookup generated roots by querying them from Lemur's ```Certificate``` model. 

I would take a look at: 
https://jamielinux.com/docs/openssl-certificate-authority/introduction.html

It is a good starting point in understanding a CA with openssl first. This should make translating the steps to Lemur/Python more straightforward.

I will also mention that a lot of the steps outline in the above documentation can be accomplished with native python libraries ([cryptography.io](https://cryptography.io)). Where possible it is often advantageous to use a library instead of shelling out to OpenSSL. 

Looking forward to your progress!

**Comment by mik373** [comment]
Thank you for the detailed explanation.  This is exactly the link I was following and exactly the implementation I was going after.  That was not the question I was asking, however.
I have the root CA certificate I am trying to return it from the create_authority call as the first value and it's failing with the exception above.  The format of the cert being returned is 
-----BEGIN CERTIFICATE-----
.....
-----END CERTIFICATE-----
Is that not what the service.py call expects?

**Comment by kevgliss** [comment]
Yes it expects a PEM formatted string, perhaps your certificate is malformed somehow?

I would attempt to parse the certificate you are returning with the following code as this is what Lemur calls internally.

```
>>> from cryptography import x509
>>> from cryptography.hazmat.backends import default_backend
>>> cert = x509.load_pem_x509_certificate(pem_data, default_backend())
>>> cert.serial
```

From https://cryptography.io/en/latest/x509/reference/#loading-certificates

**Comment by mik373** [comment]
I want to tell you a little about the specific scenario we want to use Lemur for.
We have a Kubernetes cluster running in AWS that our microservices are deployed into as part of the CD/CI pipeline.  We'd like to have the endpoints of the services wide open to the internet but use valid SSL certificates in order to have the traffic secure when services call each other.  Eventually we will have the private CA as a service but for now it will all just live in the plugin with the private key stored in S3 or mounted encrypted volume.  Lemur will run on a dedicated box(s) in an autoscaling group via docker containers on core OS (deployed via terraform). The policy for the Lemur machines will allow using RDS for storage.

The build process will call Lemur API which will generate a public/private key pair via the OpenSSL plugin and deploy it as a Kubernetes secret using the Lemur destination plugin using Kubernetes api which I am also currently writing. The data for the Kubernetes secret will have the key store and the trust store (we are primarily using Java for our microservices) so I also need to use the logic from your Java destination plugin in order to convert the key/cert PEM into trust and store files.  After the secret is created/updated Then the CI will continue and mount the Kubernetes secret to a place on disk inside the Docker container where Java can access it when the service is started (Dropwizard https module)
The CA cert will be distributed with all the services as well so they can freely and securely call each other as clients.

I'll be happy to contribute bother plugins when I have them working, cleanup, and ready.

Do you have any suggestions / comments on the approach?

**Comment by mik373** [comment]
Below is the root_ca function:

def ensure_root_ca(openssl_cert_path, subject, days):

    root_ca_cert = openssl_cert_path + "/ca.crt"
    root_ca_key = openssl_cert_path + "/ca.key"

    if os.path.isfile(root_ca_cert):
        current_app.logger.info('found root ca cert')
        with open(root_ca_cert, 'r') as myfile:
            data=myfile.read().replace('\n', '')
        return data

    """
    Creates a root CA.
    """
    with mktempfile() as key_tmp:
        with open(key_tmp, 'w') as f:
            f.write(root_ca_key)

        # Create PKCS12 keystore from private key and public certificate
        with mktempfile() as cert_tmp:
            with open(cert_tmp, 'w') as f:
                f.write(root_ca_cert)

            run_process([
                "openssl",
                "req",
                "-x509",
                "-subj", subject,
                "-new",
                "-nodes",
                "-newkey",
                "rsa:2048",
                "-days", days,
                "-keyout", root_ca_key,
                "-out", root_ca_cert
            ])

    with open(root_ca_cert, 'r') as myfile:
        data=myfile.read().replace('\n', '')

    return data


The output of the debugging:
2016-01-09 01:42:28,262 DEBUG: ['openssl', 'req', '-x509', '-subj', '/CN=miru.io/OU=Bikou/O=Jive Software/C=US', '-new', '-nodes', '-newkey', 'rsa:2048', '-days', '2048', '-keyout', '/tmp/ca.key', '-out', '/tmp/ca.crt'] [in /usr/local/src/lemur/lemur/plugins/lemur_openssl/plugin.py:28]
2016-01-09 01:42:28,348 DEBUG: cert: -----BEGIN CERTIFICATE-----MIIDYTCCAkmgAwIBAgIJAKeixnddyUCQMA0GCSqGSIb3DQEBCwUAMEcxEDAOBgNVBAMMB21pcnUuaW8xDjAMBgNVBAsMBUJpa291MRYwFAYDVQQKDA1KaXZlIFNvZnR3YXJlMQswCQYDVQQGEwJVUzAeFw0xNjAxMDkwMTQyMjhaFw0yMTA4MTgwMTQyMjhaMEcxEDAOBgNVBAMMB21pcnUuaW8xDjAMBgNVBAsMBUJpa291MRYwFAYDVQQKDA1KaXZlIFNvZnR3YXJlMQswCQYDVQQGEwJVUzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALeo9qVzj08gABXFFdjMNLtsvc2X0xpSJNXnpUs7Coc0DdIrg4+w0v2R6AYXJ0Wl1KR6tGoDvwDitbzszpDkW5LMpIXFHVz4txJtKltLOUKy0XNtKOEZDI0unulaA4Sr22LzloC5knQz7COQm1tUPWmJGyVNLsNaA/0kS+93QN/oWj4qKLuI0XKzRt59apsGcM5C2R1vVwQFh1mMSfB9OY9xv3XzsViqnBKpXlreRWrYD9NISJpYzDd8IaC+89Bh4RuZ4X+j9QwInZ+dgKK6gFVDXcBm/f1NPc7veuVaqMSktbb8V13YAuYhXeNYQt4JX+oSjGq9BmdqOhabYZLE5D0CAwEAAaNQME4wHQYDVR0OBBYEFF1ngn0YQrivNv9yxDyEZ+uz4DQ8MB8GA1UdIwQYMBaAFF1ngn0YQrivNv9yxDyEZ+uz4DQ8MAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBALCfuJJ+8/MFsKHJ6FebJ/uWsZGPYRwTTQnQeueNSvxALTUA9HVLOMVcDCGrRxZ6o34sM7Iacfqs0VqZ8AoXdkIV6lr0OwteL8ubLWsQaOgaM6V256l4g4hz4w5c10qepP/0TQenZIJagHEVY00yhwMR50zQ9vmzLoBpM2GsFyxfyQk5lsch4M0NLN0dD8mcbzbBInb6AyCwokf22rRm//IhQxAEMJK74PAvLGkgQm2EVuK9P8kXZ7IJNqoORQExsaMhlhfIUb1onwOXZhKiXBiz99IXeDV45E4qZSzCGoPmlQPbxEF9iQImXEao9J7B9WpD2FBTcmLKN7guMRBGZbg=-----END CERTIFICATE----- [in /usr/local/src/lemur/lemur/plugins/lemur_openssl/plugin.py:271]
2016-01-09 01:42:28,349 ERROR: Unable to load certificate [in /usr/local/src/lemur/lemur/common/utils.py:60]
Traceback (most recent call last):
  File "/usr/local/src/lemur/lemur/common/utils.py", line 46, in wrapper
    resp = f(*args, **kwargs)
  File "/usr/local/src/lemur/lemur/authorities/views.py", line 201, in post
    return service.create(args)
  File "/usr/local/src/lemur/lemur/authorities/service.py", line 57, in create
    cert = Certificate(cert_body, chain=intermediate)
  File "<string>", line 4, in __init__
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/state.py", line 306, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/state.py", line 303, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/src/lemur/lemur/certificates/models.py", line 253, in __init__
    cert = x509.load_pem_x509_certificate(str(self.body), default_backend())
  File "/usr/local/lib/python2.7/dist-packages/cryptography-1.1.2-py2.7-linux-x86_64.egg/cryptography/x509/base.py", line 28, in load_pem_x509_certificate
    return backend.load_pem_x509_certificate(data)
  File "/usr/local/lib/python2.7/dist-packages/cryptography-1.1.2-py2.7-linux-x86_64.egg/cryptography/hazmat/backends/multibackend.py", line 318, in load_pem_x509_certificate
    return b.load_pem_x509_certificate(data)
  File "/usr/local/lib/python2.7/dist-packages/cryptography-1.1.2-py2.7-linux-x86_64.egg/cryptography/hazmat/backends/openssl/backend.py", line 1530, in load_pem_x509_certificate
    raise ValueError("Unable to load certificate")
ValueError: Unable to load certificate

**Comment by mik373** [comment]
Thank you for the python crypto instructions: I think I figured it out.

**Comment by mik373** [comment]
I know I am on master so there will probably be bugs.

I am trying to use my Kubernetes destination for the newly issued OpenSSL certificate and I see this error in the logs:

 [in /usr/local/src/lemur/lemur/plugins/lemur_openssl/plugin.py:271]
2016-01-09 06:54:56,122 WARNING: Failed to get SubjectAltName: No <ObjectIdentifier(oid=2.5.29.17, name=subjectAltName)> extension
 was found [in /usr/local/src/lemur/lemur/certificates/models.py:102]
2016-01-09 06:54:56,124 WARNING: Failed to get SubjectAltName: No <ObjectIdentifier(oid=2.5.29.17, name=subjectAltName)> extension
 was found [in /usr/local/src/lemur/lemur/certificates/models.py:102]
2016-01-09 06:55:05,585 ERROR: (psycopg2.ProgrammingError) column domains.sensitive does not exist
LINE 1: ...s.id AS domains_id, domains.name AS domains_name, domains.se...
                                                             ^
 [SQL: 'SELECT domains.id AS domains_id, domains.name AS domains_name, domains.sensitive AS domains_sensitive \nFROM domains JOIN
certificate_associations AS certificate_associations_1 ON domains.id = certificate_associations_1.domain_id JOIN certificates ON c
ertificates.id = certificate_associations_1.certificate_id \nWHERE certificates.id = %(id_1)s \n LIMIT %(param_1)s OFFSET %(param_
2)s'] [parameters: {'id_1': 1, 'param_1': 10, 'param_2': 0}] [in /usr/local/src/lemur/lemur/common/utils.py:60]
Traceback (most recent call last):
  File "/usr/local/src/lemur/lemur/common/utils.py", line 46, in wrapper

**Comment by kevgliss** [comment]
Your plan sounds good, and is probably a good use case for quite a few users. There are several potential CAs that have plugins in various stages you might be able to leverage in the future (Let's Encrypt, cfssl, EJBCA). Of course any contributions/plugins you can add are more than welcome!

As far as your error goes, Master added a new column to the domain table, you will need to upgrade the database to add the new columns.

Run:
```
cd /usr/local/src/lemur/lemur/migrations
lemur db upgrade
```

This is documented at:
http://lemur.readthedocs.org/en/latest/administration.html#upgrading-lemur
Let me know if anything is unclear.

**Comment by mik373** [comment]
Sorry for the long delay, I was working on getting lemur incorporated into our infrastructure.  Now I have it running for real against master branch I pulled a few days ago.  The issue I have is that on init when the migrations are trying to be run I get:

sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) table "encrypted_keys" does not exist
 [SQL: '\nDROP TABLE encrypted_keys']


In fact, my database does not have that table.  The list of table and sequeinces are below:

public | authorities                           | table    | lemur
 public | authorities_id_seq                    | sequence | lemur
 public | certificate_associations              | table    | lemur
 public | certificate_destination_associations  | table    | lemur
 public | certificate_notification_associations | table    | lemur
 public | certificate_replacement_associations  | table    | lemur
 public | certificate_source_associations       | table    | lemur
 public | certificates                          | table    | lemur
 public | certificates_id_seq                   | sequence | lemur
 public | destinations                          | table    | lemur
 public | destinations_id_seq                   | sequence | lemur
 public | domains                               | table    | lemur
 public | domains_id_seq                        | sequence | lemur
 public | notifications                         | table    | lemur
 public | notifications_id_seq                  | sequence | lemur
 public | roles                                 | table    | lemur
 public | roles_id_seq                          | sequence | lemur
 public | roles_users                           | table    | lemur
 public | sources                               | table    | lemur
 public | sources_id_seq                        | sequence | lemur
 public | users                                 | table    | lemur
 public | users_id_seq                          | sequence | lemur

When I try to run the migration manually I get the same error.

Thanks for your help!

**Comment by kevgliss** [comment]
Yes, thats a known issue have a look at https://github.com/Netflix/lemur/pull/208 and see if that suggestion helps.

**Comment by kevgliss** [comment]
I think the best way forward is to remove the older migrations. I don't believe there are any users that old enough to need that migration. https://github.com/Netflix/lemur/issues/221

**Comment by kevgliss** [comment]
Closing this as it will be covered by #221

**Comment by mrala** [comment]
@mik373: were you able to get Lemur to create certs through a self-signed OpenSSL auth?

**Comment by mik373** [comment]
Yes.  Not self signed - we have OpenSSL authorities that sign certificate requests.  Each authority is used as a root for all certs in a set of services that use mutual ssl to talk to each other.  We will contribute the code back soon.

**Comment by mrala** [comment]
Sounds good! I've been working on implementing the same functionality but think I might hold off if the work is already done.
