### ISSUE TITLE
Source Plugins: Options really optional?

### ISSUE THREAD

**Issue by sirferl** [Netflix/lemur#2105]
I am experimenting with Source Plugins.
When I set up a plugin without options section, I got the following error:
_2018-11-13 15:50:44,483 ERROR: 'plugin_options' [in /opt/lemur/lemur/common/schema.py:164]
Traceback (most recent call last):
  File "/opt/lemur/lemur/common/schema.py", line 161, in decorated_function
    resp = f(*args, **kwargs)
  File "/opt/lemur/lemur/sources/views.py", line 154, in post
    return service.create(data['label'], data['plugin']['slug'], data['plugin']['plugin_options'], data['description'])
KeyError: 'plugin_options'_

I added a dummy option to get going.
Can you confirm the non optional nature of options in source plugins?
regards
sirferl

**Comment by castrapel** [comment]
It does look like options are required, even if they are dummy options. All of our sources have options -- Most of them are AWS sources with options being account number and some other attributes.

I'm glad you found a workaround. This task seems relatively low priority for us at the moment so we will mark it as help wanted.
