### ISSUE TITLE
Validation on "Create/Import certificate" works incorrectly

### ISSUE THREAD

**Issue by tomaszszlek** [Netflix/lemur#219]
Hi, I have noticed some strange behavior when I try to create certificate.
When I click on 'CREATE' button, fill out all of the required fields and then click on green "CREATE" then application shows popup with message `Was not created! [object Object]`.
In logs I can see following json response
```
{message: {authority: "Missing required parameter in the JSON body"}}
```
Response code is 400.

The same popup shows up when I try to import existing certificate. In that scenario in logs I can see :

```
{"message": {"publicCert": "The parameter 'publicCert' needs to be a valid PEM string"}}
```
Because of that I cannot create any certificates..
I tried version 0.2, 0.2.1 and 0.1.5. 
I would be thankful for any help.

**Comment by kevgliss** [comment]
Hey, which authority/issuer combination are you trying to issue certificates off of?

**Comment by tomaszszlek** [comment]
Hi, I probably used incorrect version of certificate. I generated self signed using ope ssl and it works now.
