### ISSUE TITLE
Export certificate button do not shows up

### ISSUE THREAD

**Issue by tomaszszlek** [Netflix/lemur#220]
In the angular source file I can see that for each certificate there should be 3 buttons: edit, export, more.
For some reason only two are generated. Button export doesn't show up.

**Comment by kevgliss** [comment]
Which version are you using? Master added those button relatively recently (.2.1+) I believe.

**Comment by tomaszszlek** [comment]
Sorry, the button now shows up. My docker didn't refresh and I used old version (0.1.4). Please close this ticket.
