### ISSUE TITLE
Table "encrypted_keys" does not exist error during init db command.

### ISSUE THREAD

**Issue by tomaszszlek** [Netflix/lemur#222]
I try to set up lemur from scratch (on empty db).
When i run python manage.py init -p password then I see following error in logs when migrations scripts are executed:
```
lemur-web_1   | sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) table "encrypted_keys" does not exist
lemur-web_1   |  [SQL: '\nDROP TABLE encrypted_keys']
```

When I remove all files from migrations/versions folder then init set up database without any errors.

**Comment by kevgliss** [comment]
Yes, I have an issue open to remove those old migration files as it's causing an issue for quite a few people. #221
