### ISSUE TITLE
API docs mismatch with the implementation of filter queries.

### ISSUE THREAD

**Issue by mik373** [Netflix/lemur#228]
The docs claim that authorities and destinations GET API calls can be filtered using the filter query param:

filter – key value pair. format is k=v;

But the actual implementation splits k and v using ';' characters in the corresponding service.py

if filt:
terms = filt.split(';')

I got my queries working using ; but the docs are wrong.

**Comment by kevgliss** [comment]
This should be fixed. Thanks!
