### ISSUE TITLE
Accessing authority used and its cert in the destination plugin.

### ISSUE THREAD

**Issue by mik373** [Netflix/lemur#229]
I'd like to be able to access the authority information for the certificate/private_key I am uploading.  Is there a way to do this?  I don't see anything useful in options.

**Comment by kevgliss** [comment]
Do you mean the Issuer? After you upload and then fetch the uploaded certificate, the issuer is provided to you in the json blob.

**Comment by mik373** [comment]
No, I mean destination.  I want the Kubernetes secret store to have the public certificate of the CA that was used to create this certificate.  That way I can upload it as Kubernetes secret as well and use it when my service is as client for mutual SSL.



class KubernetesDestinationPlugin(DestinationPlugin):
    title = 'Kubernetes'
    slug = 'kubernetes-destination'
    description = 'Allow the uploading of certificates to Kubernetes'

    author = 'Mikhail Khodorovskiy'
    author_url = 'https://github.com/netflix/lemur'

    options = [
        {
            'name': 'kubernetesURL',
            'type': 'str',
            'required': True,
            'validation': '@(https?|http)://(-\.)?([^\s/?\.#-]+\.?)+(/[^\s]*)?$@iS',
            'helpMessage': 'Must be a valid Kubernetes server URL!',
        },
        {
            'name': 'kubernetesAuthToken',
            'type': 'str',
            'required': True,
            'validation': '/^$|\s+/',
            'helpMessage': 'Must be a valid Kubernetes server Token!',
        },
        {
            'name': 'kubernetesServerCertificate',
            'type': 'str',
            'required': True,
            'validation': '/^$|\s+/',
            'helpMessage': 'Must be a valid Kubernetes server Certificate!',
        },
        {
            'name': 'kubernetesNamespace',
            'type': 'str',
            'required': True,
            'validation': '/^$|\s+/',
            'helpMessage': 'Must be a valid Kubernetes Namespace!',
        },

    ]

    def __init__(self, *args, **kwargs):
        super(KubernetesDestinationPlugin, self).__init__(*args, **kwargs)

    def upload(self, name, body, private_key, cert_chain, options, **kwargs):

**Comment by mik373** [comment]
Also, a related question:  when you update the certificate with the PUT request, is that by design that the destination plugin is not called to update is in the third-party destination?  That does not seem right.

**Comment by mik373** [comment]
My public CA cert is in the cert_chain so I am good on the original question, but I would still like to know if the destination plugin is supposed to be handing create, delete(or making inactive), update scenarios?

**Comment by kevgliss** [comment]
It could/should but currently does not. See #65
