### ISSUE TITLE
Feature request: create user with password in noninteractive mode

### ISSUE THREAD

**Issue by lukasmrtvy** [Netflix/lemur#2313]
`python3 manage.py create_user` should generate user with specified password in noninteractive mode:

For example:
`manage.py create_user -u admin -e admin@admin.com -p verysecret`

Its viable for Docker image: https://github.com/Netflix/lemur/pull/2280

**Comment by castrapel** [comment]
Thanks for this request! I put in a PR: https://github.com/Netflix/lemur/pull/2436

**Comment by castrapel** [comment]
This was merged! Closing this out.
