### ISSUE TITLE
Support for self-signed certs

### ISSUE THREAD

**Issue by quintonm** [Netflix/lemur#232]
It would be really nice if Lemur could use a self-signed root CA instead of having to call out to a third party like Verisign.  That would also imply that Lemur would need to deploy the root cert (and possibly intermediate certs) as well.

**Comment by kevgliss** [comment]
There are a few community efforts underway to support self signed certificates (via openssl plugin). In general we try separate concerns between services. This helps keep applications focused and easy to reason about. As Lemur currently has no support for HSMs I would be very wary of it creating CA's for anything other experimental/testing use cases.
