### ISSUE TITLE
Feature request: Add support for cfssl authsign

### ISSUE THREAD

**Issue by alwaysjolley** [Netflix/lemur#2431]
Add support for authsign mode to the cfssl plugin for limiting access to the CA to only authorized users.

1. add auth key (hex) string
2. when key is present, attempt authsign, else use normal sign mode.

https://github.com/cloudflare/cfssl/blob/master/doc/authentication.txt

**Comment by castrapel** [comment]
Thank you for reporting this issue. We don't use CFSSL. Marking this issue as help-wanted.
