### ISSUE TITLE
Clone from existing cert when creating new cert

### ISSUE THREAD

**Issue by ip2k** [Netflix/lemur#247]
It would be useful to be able to clone cert metadata from an existing cert in Lemur and have that fill out fields in the "Create Certificate" wizard, giving you a chance to edit it as you go. This would be useful when e.g. generating a new cert because an existing cert is expiring, or generating a new cert due to adding additional subjectAltName(s).

This could also be a default behavior when specifying, in the "Create Certificate" wizard, that the cert you're creating "Replaces" an existing Lemur cert.

**Comment by kevgliss** [comment]
Similar to #197
