### ISSUE TITLE
Question about Lemur 

### ISSUE THREAD

**Issue by yitzyire** [Netflix/lemur#2492]
Is there any way to configure auto approval cert requests to the Digicert API, what I'm noticing is that Digicert is putting all cert requests into a holding section for manual processing in certificate requests 

I'm using Release: 0.7.0

Kind Regards

**Comment by kevgliss** [comment]
Which Digicert API are you using Cert Central? I know historically there was another API (CIS?) that could be used that would auto-approve the certificates. We do have support for that API as well. It may be that CertCentral has added that ability as well but I'm not sure. 

This is the CIS plugin if that API is available to you.
https://github.com/Netflix/lemur/blob/master/lemur/plugins/lemur_digicert/plugin.py#L445

**Comment by hildoubledutch** [comment]
The DigiCert Plugin appears to assume the option "Automatically approve New and Reissue certificate requests when the requester is also an approver" to be ticket under "preferences".

**Comment by kevgliss** [comment]
Yeah, that sounds right @hildoubledutch.

**Comment by castrapel** [comment]
Closing this out due to inactivity.
