### ISSUE TITLE
Quickstart skips creation of `lemur` PostgreSQL user

### ISSUE THREAD

**Issue by lfaraone** [Netflix/lemur#252]
[§ Setup Postgres](https://github.com/Netflix/lemur/blob/master/docs/quickstart/index.rst#setup-postgres) has the following steps:

1. Set a password for user `postgres`
2. Create database `lemur`
3. Set password for the `lemur` user.

Shouldn't there either be a step 2½ where the `lemur` user is created? Or drop step 3 entirely and just recommend people use the default user for development. (This should be fine for people running things in containers or a VM)

**Comment by kevgliss** [comment]
That could have gotten lost somewhere along the line... feel free to send a PR if you have something that clears this up. Otherwise I will look into it.
