### ISSUE TITLE
lemur as a general store of secrets

### ISSUE THREAD

**Issue by JohnTheodore** [Netflix/lemur#253]
Are there plans to add general key service management to lemur? eg, I have some API key that a VM or role needs in order for the app to function... can lemur manage that?

I read this slide deck: https://speakerdeck.com/bdpayne/key-management-in-aws-how-netflix-secures-sensitive-data-without-its-own-data-center

Why isn't cryptex/lemur one system? are there plans to open source cryptex?

**Comment by kevgliss** [comment]
There are no plans for Lemur to be a general key service management system. It has a very focused goal of providing certificate creation and management in an approachable package. We try to keep our microservices small, focused, and easy to reason about. In this way we are able to compose our architecture; adding and removing pieces as needed without the large blast radius that you might get from one monolithic application. 

Cryptex is actually used by Lemur, in an indirect way. It could be argued that cryptex/lemur is one system (our environment) and that they are just two pieces among many others. There are no current plans to open source cryptex at this time. We are always evaluating which parts of our ecosystem make sense open source.

**Comment by zarfide** [comment]
To add to what Kevin said, Cryptex isn't really built to manage someone else's secrets.  Rather, it's designed to be in the direct request path of the crypto operation and perform the crypto for you and keep the key values internally and not give them out.  It could only indirectly be used as a place to stash someone else's API keys and it's generally not a use case we recommend.

If you have third party API keys to hide on AWS instances, the approach I recommend is to put the API keys in a datastructure (such as an S3 bucket) available only to the role of the instance in question and/or wrap with KMS. I believe https://github.com/codahale/sneaker uses this sort of approach (warning: I have not personally used sneaker so I cannot endorse it specifically).

As to open sourcing Cryptex, it predates our open source efforts and it would need a lot of work to clean up and modularize such that it would be useful to anyone outside of the Netflix ecosystem.  And while there is no fundamental reason why we can't do that at the moment we don't have the engineering resources allocated for such a task.

**Comment by JohnTheodore** [comment]
Thanks for the thoughtful replies. We're thinking about using lemur for certificate management, and perhaps sneaker for general KMS stuff in aws.
