### ISSUE TITLE
Digicert CIS plugin calling missing endpoints?

### ISSUE THREAD

**Issue by jplana** [Netflix/lemur#2556]
While playing with the Digicert plugin, initially for certificate sync, found that Digicert endpoint is always refusing our REST api calls with "400 Unauthorized". We found that the plugin is calling endpoints such as:  "{0}/platform/cis/certificate/{1}" but couldn't find documentation for those in https://www.digicert.com/services/v2/documentation.

We might be missing something (either in the doc or in Lemur's code) but at this point I'm not sure if that API exists anymore in Digicert's side. 

We're happy to try to fix things for that plugin if necessary but would like to know first if it makes sense to migrate those calls to the documented API.

**Comment by kevgliss** [comment]
Are you sure you want to use the CIS plugin? I believe the CIS api is a legacy API. I believe you want to use the the other digicert plugin that uses the cert central api (the one you linked to).

**Comment by jplana** [comment]
Well, I wasn't sure about what Digicert CIS was and couldn't find any reference to that API. My only motivation to use the CIS plugin was that it already implemented the SourcePlugin, whereas the current DigiCertSourcePlugin doesn't. I guess I can try to implement the missing method if that's fine. Thanks!
