### ISSUE TITLE
Email notification doesn't work

### ISSUE THREAD

**Issue by rpicard** [Netflix/lemur#258]
Email notifications aren't being sent, and I'm seeing this in the logs:

```pyt
2016-03-23 21:26:03,261 ERROR: u'email-notification' [in /opt/lemur/lemur/common/utils.py:60]
Traceback (most recent call last):
  File "/opt/lemur/lemur/common/utils.py", line 46, in wrapper
    resp = f(*args, **kwargs)
  File "/opt/lemur/lemur/plugins/views.py", line 129, in get
    return plugins.get(name)
  File "/opt/lemur/lemur/plugins/base/manager.py", line 37, in get
    raise KeyError(slug)
KeyError: u'email-notification'
```

**Comment by kevgliss** [comment]
Are you on the latest version? Typically this line would ensure that the email plugin is at least available.

https://github.com/Netflix/lemur/blob/master/setup.py#L167

**Comment by rpicard** [comment]
Using revision 0a58e106b5318ded0da7e3007205e4183e387bb3. Think upgrading will fix this?

**Comment by kevgliss** [comment]
I am not sure, that is the latest release (0.2.2). Do you have that line in your setup.py? You could also try running `python setup.py install` again. Basically Lemur can't find that plugin for some reason, make sure it exists under `lemur/plugins/lemur_email`.

**Comment by rpicard** [comment]
That line does exist in my `setup.py` and `lemur/plugins/lemur_email` exists as well.

**Comment by kevgliss** [comment]
The other thing that I have seen cause this is that somehow the plugin is unable to load because of syntax error, when Lemur starts up do you get any messages about "Failed to load plugin X"?

This is the line that would through that message:
https://github.com/Netflix/lemur/blob/master/lemur/factory.py#L165

**Comment by rpicard** [comment]
Yep, actually it looks like no plugins are loading:

```
/var/log/lemur.log:2016-03-21 18:21:35,949 ERROR: Failed to load plugin 'email_notification':
/var/log/lemur.log:2016-03-21 18:21:35,978 ERROR: Failed to load plugin 'java_export':
/var/log/lemur.log:2016-03-21 18:21:35,979 ERROR: Failed to load plugin 'aws_source':
/var/log/lemur.log:2016-03-21 18:21:35,979 ERROR: Failed to load plugin 'verisign_issuer':
/var/log/lemur.log:2016-03-21 18:21:35,979 ERROR: Failed to load plugin 'openssl_export':
/var/log/lemur.log:2016-03-21 18:21:35,980 ERROR: Failed to load plugin 'aws_destination':
/var/log/lemur.log:2016-03-21 18:21:36,141 ERROR: Failed to load plugin 'email_notification':
/var/log/lemur.log:2016-03-21 18:21:36,141 ERROR: Failed to load plugin 'java_export':
/var/log/lemur.log:2016-03-21 18:21:36,142 ERROR: Failed to load plugin 'aws_source':
/var/log/lemur.log:2016-03-21 18:21:36,142 ERROR: Failed to load plugin 'verisign_issuer':
/var/log/lemur.log:2016-03-21 18:21:36,142 ERROR: Failed to load plugin 'openssl_export':
/var/log/lemur.log:2016-03-21 18:21:36,143 ERROR: Failed to load plugin 'aws_destination':
```

**Comment by kevgliss** [comment]
Is that output from a grep? Right under those lines there should be a stack-trace explaining whats going on.

**Comment by rpicard** [comment]
You really know your stuff. The stack traces revealed that `future` wasn't installed. Thanks!
