### ISSUE TITLE
Importing all certificates from AWS

### ISSUE THREAD

**Issue by johnakash** [Netflix/lemur#260]
Hi Team,

We are having around 300+ certificates on our infra and we would like to use Lemur to manage them. Could you please let us know how can we perform bulk import?

Now we are using venafi for managing the SSLs. Could you please let us know how to perform bulk import?

Is it possible to perform a network scan to identify the SSL certs on our AWS infra?

**Comment by kevgliss** [comment]
I am not sure how you would migrate from Venafi to Lemur. But if all of your certificates are in AWS Lemur does have the ability to pull down and track existing certificates. 

Assuming Lemur has been installed and given the correct IAM roles (see [here](http://lemur.readthedocs.org/en/latest/administration.html#setting-up-iam-roles)).

You would then add a 'source' in Lemur that with the account or accounts your wish to sync. 

After which you will need to run the `lemur sync_sources` command. This can be a one time import or you can put the command in a cron to be run on a interval. ([docs](http://lemur.readthedocs.org/en/latest/administration.html#sync))

I believe Venafi does have an API, if you wanted to migrate certificates from Venafi to Lemur you might have to write a source plugin. See [here](http://lemur.readthedocs.org/en/latest/developer/plugins/index.html) for the docs on how to write a plugin and [here](https://github.com/Netflix/lemur/blob/master/lemur/plugins/lemur_aws/plugin.py#L60) for an example of the AWS source plugin. It's fairly straightforward.

**Comment by johnakash** [comment]
Hi kevgliss,

Thanks for the quick response. The assume role is already in place but unfortunately the SSL certificates are not seems to be pulling down. Could you please let us know how can we debug more to identify the issue?

**Comment by johnakash** [comment]
Hi kevgliss,

Thanks for the quick response. The assume role is already in place but unfortunately the SSL certificates are not seems to be pulling down. Could you please let us know how can we debug more to identify the issue?

**Comment by kevgliss** [comment]
What happens when you run `lemur sync -list`? Anything in the logs look interesting?

**Comment by johnakash** [comment]
Hi kevgliss,

While we are running lemur sync -list we are getting an error and the same is mentioned below,

lemur sync -list
usage: lemur [-c CONFIG] [-?]
             {show_urls,shell,provision_elb,sync_sources,create_user,rotate_elbs,lock,check_revoked,db,init,runserver,start,unlock,create_role,notify,clean,publish_verisign_units,rolling,create_config}
             ...
lemur: error: invalid choice: 'sync' (choose from u'show_urls', 'shell', u'provision_elb', 'sync_sources', u'create_user', u'rotate_elbs', 'lock', 'check_revoked', u'db', u'init', u'runserver', u'start', 'unlock', u'create_role', 'notify', u'clean', 'publish_verisign_units', u'rolling', 'create_config')

But while we are running **lemur sync_sources** we are getting the below response,

/www/lemur/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
Active  Label   Description
True    1-aws   1 accout SSL certs!
True    2-aws 2 AWS!
True    3-aws 3 for test!

**Comment by kevgliss** [comment]
Apologies, I thought that command got renamed. (looks like the docs drifted from the code a bit). What do you get when running `lemur sync_sources -s 1-aws`? That should attempt to sync up that source. You can also sync multiple sources by comma seperating the sources e.g. `lemur sync_sources -s 1-aws,2-aws,3-aws`

**Comment by johnakash** [comment]
Hi Kevgliss,

I am appologyzing for the delay caused on the response. Please find the output of the command below,

_lemur sync_sources -s 1-aws
/www/lemur/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[+] Staring to sync sources: tmocde!
Traceback (most recent call last):
  File "/www/lemur/bin/lemur", line 9, in <module>
    load_entry_point('lemur', 'console_scripts', 'lemur')()
  File "/www/lemur/lemur/manage.py", line 848, in main
    manager.run()
  File "/www/lemur/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/www/lemur/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/www/lemur/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/www/lemur/lemur/manage.py", line 223, in sync_sources
    sync(labels=labels)
  File "/www/lemur/lemur/sources/service.py", line 87, in sync
    sync_create(certificate, source)
  File "/www/lemur/lemur/sources/service.py", line 41, in sync_create
    cert = cert_service.import_certificate(**certificate)
  File "/www/lemur/lemur/certificates/service.py", line 179, in import_certificate
    cert.owner = kwargs.get('owner', current_app.config.get('LEMUR_SECURITY_TEAM_EMAIL')[0])
IndexError: list index out of range
_

But while executing the command on those accounts in which there is not SSL configured is showing the response shown below,
_ lemur sync_sources -s 2-aws
/www/lemur/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[!] Unable to acquire file lock on /tmp/.lemur_lock, is there another sync running?
[+] Staring to sync sources: tmopub!
[+] Finished syncing sources. Run Time: 10.8733239174
_

**Comment by kevgliss** [comment]
I would check in your config that `LEMUR_SECURITY_TEAM_EMAIL` is set in your Lemur config. This is used as the owner of imported certificates as Lemur doesn't know who the owner is. 

We could possibly update the [docs](http://lemur.readthedocs.org/en/latest/quickstart/index.html#update-your-configuration) to be explicit about what values you need to replace/add.

Or perhaps/additionally we can modify the create_config command to ask for these values and insert them into the config.
