### ISSUE TITLE
Lemur Ignores -c Option

### ISSUE THREAD

**Issue by ardichoke** [Netflix/lemur#2636]
When starting lemur with -c (ex: `lemur start -c /etc/lemur.conf.py`), the value passed into -c is silently ignored.

**Comment by kevgliss** [comment]
Looks similar to #1887 have you tried `--config`? Could be just the sort name not being parsed.

**Comment by ardichoke** [comment]
Just tested with `--config`, same result. The only way that I can get it to use the config file is to have it in `~/.lemur/lemur.cfg.py` (or symlink the config file to that location).

Interestingly, if the file passed to `-c` or `--config` is not readable due to permissions, lemur will die because it failed to read the config file... so at some point it is attempting to at least open the configuration file  passed in on the command line. It is not actually using the settings in that file though, only the one in the users home directory.

**Comment by kevgliss** [comment]
Can you see if #2646 fixes your issue?

**Comment by ardichoke** [comment]
Yes, some very rudimentary tests of your branch indicate it does fix -c and --config functionality.
