### ISSUE TITLE
certificate reissue not working

### ISSUE THREAD

**Issue by alwaysjolley** [Netflix/lemur#2706]
Using a build from the current master i am unable to reissue certificates with the command `certificate reissue`. I can see a list of certificates that are due for renewal with common name, subject alt names, authority, and validity start and end times for the new certificate but nothing else happens. 

```
$ /www/lemur/bin/python36 /www/lemur/bin/lemur -c /home/lemur/.lemur/lemur.conf.py certificate reissue
[+] Starting certificate re-issuance.
[+] something.testdomain.com-FakeLEIntermediateX1-20190311-20190609 is eligible for re-issuance
[2019-03-18 14:46:07,235] WARNING in models: Custom OIDs not yet supported for clone operation.
Custom OIDs not yet supported for clone operation.
[2019-03-18 14:46:07,235] WARNING in models: Custom OIDs not yet supported for clone operation.
Custom OIDs not yet supported for clone operation.
[+] Re-issuing certificate with the following details: 
		[+] Common Name: something.testdomain.com
		[+] Subject Alternate Names: something.testdomain.com
		[+] Authority: letsencrypt_staging_v2
		[+] Validity Start: 2019-03-18T18:46:07.229876+00:00
		[+] Validity End: 2019-06-16T18:46:07.229876+00:00
```

Am i missing something? is this the wrong command?

Thanks

**Comment by kevgliss** [comment]
Are there any errors associated with your issue in the logs?

**Comment by alwaysjolley** [comment]
No error, nothing seems to happen. The cert does not update. i can even see no traffic is generated out to the CA to attempt to sign a new certificate.

I assume i am doing something wrong on my end but i have no idea where the error is since i am not seeing anything in the logs to indicate an issue.

**Comment by alwaysjolley** [comment]
Figured it out, i was missing the `--commit`
since this is not documented anywhere i could find, this is the command i am using to auto renew certificates
`/www/lemur/bin/python36 /www/lemur/bin/lemur -c /home/lemur/.lemur/lemur.conf.py certificate reissue --commit`

**Comment by kevgliss** [comment]
For future reference you should be able to pass `--help` to any of the commands to view the available options. Let us know if that's not the case.

**Comment by ardichoke** [comment]
Yes, --help does list --commit, but the help message for it isn't particularly clear as to what it does or the fact that it is necessary to actually execute certificate renewal. This is the entirety of the help message for that flag:

>   -c, --commit          Persist changes.
