### ISSUE TITLE
.travis.yml: The 'sudo' tag is now deprecated in Travis CI

### ISSUE THREAD

**Issue by cclauss** [Netflix/lemur#2758]
[Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).

"_If you currently specify __sudo: false__ in your __.travis.yml__, we recommend removing that configuration_"

**Comment by castrapel** [comment]
Thanks @cclauss , we use `sudo: required` in our https://github.com/Netflix/lemur/blob/master/.travis.yml . I believe we're good as we are. Please let us know if you notice any problems.

**Comment by cclauss** [comment]
__sudo__ is a no-op so sudo is ___always___ so removing this line will not change your tests.

**Comment by hosseinsh** [comment]
Thanks @cclauss for the follow-up. 
removed sudo in https://github.com/Netflix/lemur/pull/2764
