### ISSUE TITLE
Unable to configure DYN dns provider

### ISSUE THREAD

**Issue by mauded** [Netflix/lemur#2780]
Lemur Web Version: 0.7.0 (Although have tried a latest master build also and the issue still persists for us)

We are currently experiencing what appears to be a web gui issue where selecting DYN in the DNS Providers drop down list doesn't append any fields to the form to supply any credentials/keys for use.

I have checked through various changelogs/documentation/searches online and can't seem to find any config file specific options to do set this up at file level (hence my assumption it should be DB driven via the web form).

Any suggestions or SQL snippets to perform to allow this functionality for DYN specifically would be highly appreciated.

Note: Selecting cloudflare or route53 appends fields appropriately, just not for dyn.

**Comment by castrapel** [comment]
Hi @mauded sorry about the UI issue. I assume you're trying to get LetsEncrypt support working.

You'll need the following variables defined in your configuration:

ACME_DYN_CUSTOMER_NAME
ACME_DYN_USERNAME
ACME_DYN_PASSWORD

You may also need this in your configuration:

`ACME_DNS_PROVIDER_TYPES = {"items": [
    {
        'name': 'route53',
        'requirements': [
            {
                'name': 'account_id',
                'type': 'int',
                'required': True,
                'helpMessage': 'AWS Account number'
            },
        ]
    },
    {
        'name': 'cloudflare',
        'requirements': [
            {
                'name': 'email',
                'type': 'str',
                'required': True,
                'helpMessage': 'Cloudflare Email'
            },
            {
                'name': 'key',
                'type': 'str',
                'required': True,
                'helpMessage': 'Cloudflare Key'
            },
        ]
    },
    {
        'name': 'dyn',
    },
]}`

 I recommend grabbing an API key and using Postman to POST a request that would create the provider for you. Here's an example of what to POST:

`{
          "providerType": {
            "name": "Dyn",
            "requirements": [
              {
                "name": "dyn"
              },
            ],
            "route": "dns_provider_options",
            "reqParams": null,
            "restangularized": true,
            "fromServer": true,
            "parentResource": null,
            "restangularCollection": false
          },
          "name": "Dyn",
          "description": "Dyn DNS Provider"
        }
}`

You'll need to post this to /api/1/dns_providers with an appropriate authorization header

**Comment by mauded** [comment]
@castrapel, thank you very much for your detailed response! This is incredibly helpful after exhausting as much manual efforts to resolve this alone.

If I can assist anybody further in terms of debugging the WebUI issue if this cannot be re-produced then please do feel free to give me a shout with some quick requirements that can help :)
