### ISSUE TITLE
Synchronizing certificates from Digicert

### ISSUE THREAD

**Issue by mnatalonicb** [Netflix/lemur#2785]
I currently have a instance of Lemur stood up that is using the Digicert plugin to request certificates. I am able to request certificates, but I am also looking to for a way to synchronize certificates from Digicert down into Lemur. 

I followed the docs for setting up synchronization as a cronjob but I am still unable to sync certificates. Could I have some assistance? Is this possible from the Digicert plugin?

**Comment by castrapel** [comment]
Hi @mnatalonicb , we do not synchronize certificates from Digicert, but I do see a digicert-cis-source source plugin. I cannot speak to the reliability of this plugin and it looks like it only works for Digicert's CIS api.

To add a source via the web UI, you would go to admin / sources / Create , and select the Digicert plugin. You'll need configuration variables for DIGICERT_CIS to get this to work.

If you're able to add a source for this , syncing can be accomplished via the CLI - 

"LEMUR_CONF=/locationtoyourconfig.py lemur source sync"

**Comment by mnatalonicb** [comment]
Thanks @castrapel
