### ISSUE TITLE
views.py

### ISSUE THREAD

**Issue by cmuellerme** [Netflix/lemur#2786]
hi, by setup lemur create_config i get the following error

  File "/www/lemur/lemur/auth/views.py", line 118
    headers = {'Authorization': f'Bearer {access_token}'}
                                                       ^
SyntaxError: invalid syntax
(lemur) lemur@lemur:/www/lemur$

**Comment by castrapel** [comment]
Hi, please upgrade to Python 3.6 or above to support format strings. Here are some more details: https://realpython.com/python-f-strings/

Thanks,
Curtis

**Comment by Nightreaver** [comment]
In the Dockerfile you use `FROM python:3.5` ... that doesnt make sense when we need to use python 3.6 ...

**Comment by castrapel** [comment]
This is as good point. We don't use Docker internally at Netflix, and this is a community supported plugin - Sorry about overlooking this. I will deploy a PR to bump Python for docker. https://github.com/Netflix/lemur/pull/2805
