### ISSUE TITLE
lemur create_config command failed

### ISSUE THREAD

**Issue by bmjain** [Netflix/lemur#2816]
Unable to Create configuration using 'lemur create_config". Getting the error as shown below:

`(lemur) lemur@osboxes:/www/lemur/lemur$ lemur create_config`
`/www/lemur/lib/python3.5/site-packages/sqlalchemy/sql/functions.py:68: SAWarning: The GenericFunction 'array_agg' is already registered and is going to be overriden.
  "is going to be overriden.".format(identifier))`

`Traceback (most recent call last):`

  `File "/www/lemur/bin/lemur", line 11, in <module>
    load_entry_point('lemur', 'console_scripts', 'lemur')()`

  `File "/www/lemur/lib/python3.5/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)`

  `File "/www/lemur/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()`

  `File "/www/lemur/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()`

  `File "/www/lemur/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)`

  `File "/www/lemur/lemur/__init__.py", line 19, in <module>
    from lemur.auth.views import mod as auth_bp`

  `File "/www/lemur/lemur/auth/views.py", line 129
    headers = {"Authorization": f"Bearer {access_token}"}`

`SyntaxError: invalid syntax`

**Comment by castrapel** [comment]
Looks like you need to use Python 3.6 or above for the string formatting.
