### ISSUE TITLE
AWS Certificate Manager Plugin Creation

### ISSUE THREAD

**Issue by bmjain** [Netflix/lemur#2823]
I wanted to import all certificates from AWS (IAM and ACM) into the Lemur. With current implementation, I am able to fetch only IAM server certificates. But I wanted to fetch the ACM certs too. Do you have an existing implementation of the same or do I need to create a new plugin to do that?

**Comment by hosseinsh** [comment]
sorry for the late reply, yes Lemur lacks a plugin for ACM certificates

**Comment by jmcrawford45** [comment]
Fixed by #4704
