### ISSUE TITLE
Uploading certificate 

### ISSUE THREAD

**Issue by johnakash** [Netflix/lemur#283]
Hi Team,

How can we upload / import a certificate to Lemur using APIs? I am not that much good in python scripting. Could you please guide me how can we achieve this?

**Comment by kevgliss** [comment]
Please see the documentation at:
http://lemur.readthedocs.org/en/latest/developer/index.html#lemur.certificates.views.CertificatesUpload

You can use whatever language would like to talk to the API.

**Comment by johnakash** [comment]
Hi Kevgliss, 

Thanks for sharing the documentation, but unfortunately I am not that much familiar with python scripting. As a first step I tried to create a script for Authentication (http://lemur.readthedocs.org/en/latest/developer/index.html#post--auth-login). I am getting an output of 405. Could you please let me know how can we fix the issue with the script first and later will trying with uploading. 

**Script created**
#!/usr/bin/python
import requests
response = requests.request("POST",
                           "http://10.1.1.1/#/login",
                            data={'username': "lemur", 'password': "adsadsad"},
                            headers={'content-type': 'application/json'}
							)
print response

**Output getting**
>>> print response
<Response [405]>

**Comment by kevgliss** [comment]
You are using the wrong url, what you see in the browser is not the same as the api as its all javascript. I think you want something like: `http://10.1.1.1/api/1/auth/login`.

**Comment by johnakash** [comment]
Hi Mate,

Thanks for the update and that was informative. I am trying to develop a python script, but now the result is showing as  Response [400] and the Chrome postmaster plug in giving json format output as
 {
  "status": 400,
  "message": "Bad Request"
}


In Text Format we are getting an output as given below,
{
  "message": {
    "username": "Missing required parameter in the JSON body"
  }
}

**Comment by kevgliss** [comment]
The data you send to Lemur needs to be in json format.

try:
```
#!/usr/bin/python
import json
import requests
response = requests.request("POST",
    "http://10.1.1.1/api/1/auth/login",
    data=json.dumps({'username': "lemur", 'password': "adsadsad"}),
    headers={'content-type': 'application/json'}
)
```

**Comment by johnakash** [comment]
Hi kevgliss,

The script is seems to be providing 200 response. As per the documentation (http://lemur.readthedocs.org/en/latest/developer/index.html#post--auth-login)  we will be getting a token as output, but while executing this script. Could you please let us know how can we get that?

**Comment by johnakash** [comment]
Hi kevgliss,

Thanks for your guide lines I was able to create script to upload certificate to Lemur. Please find the script below. please go through it and let know if we can improve it some how. 

#!/usr/bin/python
import json
import requests
login = requests.request("POST",
    "http://10.1.1.1/api/1/auth/login",
    data=json.dumps({'username': "lemur", 'password': "admin"}),
    headers={'content-type': 'application/json'}
)
login.json()["token"]
print login.json()
Auth = {'Authorization': 'token %s' %login.json()["token"], 'content-type': 'application/json'}
rootcert = open('/home/user/scripts/spk.pem', 'rw')
privatecert = open('/home/user/scripts/private.key', 'rw')
upload = requests.request("POST",
"http://10.1.1.1/api/1/certificates/upload",
data=json.dumps({"owner": "user@domain.com", "publicCert": rootcert.read(), "privateKey": privatecert.read(), "destinations": [], "notifications": [], "replacements": [], "name": "Fina Test" }),
headers=Auth
)
print upload.json()

**Comment by kevgliss** [comment]
Looks good to me! Glad you got it working.

**Comment by lashing** [comment]
Above script didn't work for me. I had to use "body" instead of "publicCert" and "chain" instead of "intermediateCert" to make it working. Also in the  official lemur documentation (http://lemur.readthedocs.io/en/latest/developer/index.html#post--auth-login), the example for "lemur.certificates.views.CertificatesUpload" is completely misleading.

**Comment by kevgliss** [comment]
I've opened #1231 to fix that doc string. Thanks for the report!

**Comment by JohnTheodore** [comment]
Does anyone on this thread have scripts they can share for cert renewal? say if I have a box with nginx or apache, and I want to do a renewal and a reload with lemur. do all the checks/validations. kind of like the library of tools let's encrypt has, but for lemur.

**Comment by sebasamd** [comment]
Hello,
I can communicate with the api to upload certificates, but I have problems to achieve a correct format of it.
I only achieved it using a string taken from the web browser debug console. In all other cases I only get "message": "Failed to decode JSON object: Invalid control character at: line 3 column 40 (char 73)"  That point to "body": section.

I'm usign a_string.replace("\n", "") in Python convert the original .pem to one without breaklines.

Thanks in advaced
