### ISSUE TITLE
Manually providing dns_providers for ACME protocol

### ISSUE THREAD

**Issue by tmurphy131** [Netflix/lemur#2856]
The lemur production documentation states the following when configuring an authority by way of the ACME protocol:

"By default, users will need to select the DNS provider that is authoritative over their domain in order for the LetsEncrypt flow to function. However, Lemur will attempt to automatically determine the appropriate provider if possible. To enable this functionality, periodically (or through Cron/Celery) run lemur dns_providers get_all_zones. This command will traverse all DNS providers, determine which zones they control, and upload this list of zones to Lemur’s database (**in the dns_providers table**). Alternatively, you can manually input this data."

My company uses an internal solution that has authoritative DNS control. I would have to go the manual route of inputting my data into the dns_providers table. I was given a list of zones from the DNS team to upload to postgres however it seems that information is not enough (name and description). What are the requirements for manually inputting this data?

**Comment by hosseinsh** [comment]
First you need to create a DNS provider, via the UI: ADMIN->DNS Providers.
Ideally, your internal DSN provider is compatible with one of the available plugins. Today Lemur supports cloudflare, dyn, route53, and ultraDNS (see https://github.com/Netflix/lemur/tree/master/lemur/plugins/lemur_acme). You can however easily add a new plugin, for your internal DNS provider, as by implementing the required features (put TXT record, delete TXT record, etc.)

![Screen Shot 2019-10-08 at 5 14 28 PM](https://user-images.githubusercontent.com/4578421/66442314-1b8a1300-e9ef-11e9-8ba3-b349e51d7d7c.png)

Once you have that entry in the dns_providers table, you need to either manually or programmatically, add the zones under the domains row: ["foo.com", "bar.net", ...]

Note that some of the plugins require setting USERNAME PASSWORD or API_KEY for access the DNS provider.

**Comment by hosseinsh** [comment]
also this might help for setting up a new DNS provider: 

https://github.com/Netflix/lemur/issues/2780
