### ISSUE TITLE
WebUI not working - Checked bower.json and angular-chart.js and the required packages looks in-tact.

### ISSUE THREAD

**Issue by sureshyella** [Netflix/lemur#2858]
I can't login and click any tab like DASHBOARD, CERTIFICATES, etc...rest api works. this is exactly the same issues reported earlier in the new build. I verified bower.json and angular packages.  Any help on this would be appreciated.
#
![Screen Shot 2019-10-08 at 1 57 50 PM](https://user-images.githubusercontent.com/47510835/66432920-02279d80-e9d4-11e9-9fdf-9c665dad39f5.png)

{
  "name": "lemur",
  "repository": {
    "type": "git",
    "url": "git://github.com/netflix/lemur.git"
  },
  "private": true,
  "dependencies": {
    "jquery": "~2.2.0",
    "angular-wizard": "~0.4.0",
    "angular": "1.4.9",
    "json3": "~3.3",
    "es5-shim": "~4.5.0",
    "bootstrap": "~3.3.6",
    "angular-bootstrap": "~1.1.1",
    "angular-animate": "~1.4.9",
    "restangular": "~1.5.1",
    "ng-table": "~0.8.3",
    "moment": "~2.11.1",
    "angular-loading-bar": "~0.8.0",
    "angular-moment": "~0.10.3",
    "moment-range": "~2.1.0",
    "angular-clipboard": "~1.3.0",
    "angularjs-toaster": "~1.0.0",
    "angular-chart.js": "~0.8.8",
    "ngletteravatar": "~4.0.0",
    "bootswatch": "~3.3.6",
    "fontawesome": "~4.5.0",
    "satellizer": "~0.13.4",
    "angular-ui-router": "~0.2.15",
    "font-awesome": "~4.5.0",
    "lodash": "~4.0.1",
    "underscore": "~1.8.3",
    "angular-smart-table": "2.1.8",
    "angular-strap": ">= 2.2.2",
    "angular-underscore": "^0.5.0",
    "angular-translate": "^2.9.0",
    "angular-ui-switch": "~0.1.0",
    "angular-sanitize": "~1.5.0",
    "angular-file-saver": "~1.0.1",
    "angular-ui-select": "~0.17.1",
    "d3": "^3.5.17"
  },
"../bower.json" 56L, 1411C                                                               1,1           Top

**Comment by hosseinsh** [comment]
Lemur doesn't work on Firefox. do you observe the same issue also with other Browsers?

**Comment by sureshyella** [comment]
I have the same problem in chrome/Safari.  Looks like REST API is working but not UI.

vagrant@ubuntu-xenial:~$ curl -H "Content-Type: application/json" -X POST -d '{"username":"lemur","password":"xxxx"}' http://127.0.0.1:8000/api/1/auth/login 
{"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzA1NjA4MzgsImV4cCI6MTU3MDY0NzIzOCwic3ViIjoxfQ.a_4ZfIko9VGolcy2vIzfeTnrDNiKISEll1d9wMMwnLM"}

**Comment by sureshyella** [comment]
<img width="607" alt="Screen Shot 2019-10-09 at 1 58 19 PM" src="https://user-images.githubusercontent.com/47510835/66519823-dde3c380-ea9c-11e9-9b65-fa24b6a618ce.png">

**Comment by sureshyella** [comment]
-- | -- | -- | --

**Comment by sureshyella** [comment]
> Lemur doesn't work on Firefox. do you observe the same issue also with other Browsers?
I have the same problem in chrome/Safari. Looks like REST API is working but not UI.
