### ISSUE TITLE
Role Creation and Restricting Access

### ISSUE THREAD

**Issue by johnakash** [Netflix/lemur#286]
Hi Team,

We would like to know how can we create new roles with different permission levels. As of now I cannot view any permission levers while creating a new role using dashboard. 

In the documentation (http://lemur.readthedocs.org/en/latest/administration.html#identity-and-access-management) we can see different permission level users. How can we create users / roles with AdminPermission, CreatorPermission and OwnerPermission?

Besides that could you please let us know how can we restrict a user to access only for some particular servers. For example if i am managing an application called netflix (_which having lot of certs uploaded to the lemur_), is it possible to set the permission level to view / edit / download the certificate associated with netflix only?

**Comment by kevgliss** [comment]
You can create n number of roles that you would like under Settings > Roles. Once created you can assign those roles to particular authorities to restrict access to those authorities. For certificates this is currently controlled by the 'owner' field. The owner you place will be matched against the current roles assigned to the user and given the appropriate view permissions. Currently all are allowed to view the public key material and only private key material is restricted. Additionally you can assign the 'Admin' role to any user you wish (if you are already an admin) under Settings > Users > Edit User > Select 'Admin'.

In the future, I want to add an additional association to certificates such that you can attach arbitrary roles to certificates just as you can with authorities. The implicit owner association is not a good solution and is not very flexible. 

I've updated #198 with this requirement.

**Comment by johnakash** [comment]
Thanks for the update, but while creating a new role we cannot specify the privilege other than admin rt? 
![lemur](https://cloud.githubusercontent.com/assets/1567281/14681655/aeec0180-073f-11e6-85df-731568646d62.png)
 
What I am looking for is to create roles with different permissions like admin, support and readonly, then adding user to those roles who can access /update the corresponding certificates. 

The ultimate goal is to restrict a user to access only for some **set of particular certificates** . For example if i am managing an application called netflix (which having lot of certs uploaded to the lemur), is it possible to set the permission level to view / edit / download the certificate associated with netflix only?

Do we need to use Authorities to achieve any of these goals?

**Comment by kevgliss** [comment]
No, you do not need authorities. There are currently only three sets of permissions AdminPermission, OwnerPermission, and CreatorPermission. The roles themselves just control membership. The context of the roles are what controls access. 

For instance, we currently manage things by team DL.  When they login they are assigned a role that corresponds with that DL. This means that when someone says teamA@example.com is an owner of that certificate anyone with the team@example.com role is given the owner permission. In the context of certificates the only difference between an owner and a regular user is the ability view the private key. 

This is a bit kludgy if you do not want use an email address as the owner, #198 once implemented would hopefully address that.

**Comment by johnakash** [comment]
Ok, that is fine with authorities.

Regarding the roles, as screenshot shown on our last comment we cannot find various permission levels (AdminPermission, OwnerPermission, and CreatorPermission) on that window. Only **Admin** is available there 

Could you please guide us how can we create roles with above mentioned privileges?

**Comment by johnakash** [comment]
Hi kevgliss,

I was able to create two roles,

- Admin: having entire access
- ReadOnly: having readonly access who can view the dashboard not to download certificate.

Could you please let me know how can we create a user with readonly permission and download certificate access?

**Comment by kevgliss** [comment]
By default all users have readonly access. Only admins or certificate creators and certificate owners will have access to download certificates. 

You can create/assign an owner role by creating a role named `owner@example.com` and using that string in the `owner` field when creating/importing certificates. You can then apply that role to any user and they will have access to the private key.

Again this is a bit kludgy if you do not rely on email addresses as groups of users. #198 Should help fix this.

**Comment by johnakash** [comment]
Hi kevgliss,

Thanks a lot. It was working fine and seems to be perfect.
