### ISSUE TITLE
Validity Error

### ISSUE THREAD

**Issue by johnakash** [Netflix/lemur#287]
Hi Team,

We have configured Lemur on both Ubuntu and RHEL 7.2. While we are uploading a certificate on **Ubuntu** the **validity** on basic info tab (_login to lemur >> certificate >> choose a certificate >> BASIC INFO_) as **Valid** , but in the case of **RHEL 7.2** the Validity is showing as **Unknown**.

Ubuntu Status 
![lemur-ubuntu](https://cloud.githubusercontent.com/assets/1567281/14675904/cd68f698-0728-11e6-980b-4fba2aae3925.png)

RHEL Status
![lemur-rhel](https://cloud.githubusercontent.com/assets/1567281/14675837/784dbc2a-0728-11e6-96b7-e7f2ae306f62.png)

Both certificates are same and uploaded in the same method (using both API and Dashboard).

Could you please let us know how can we fix this issue?

**Comment by kevgliss** [comment]
The validity check is just a daily cron job that determines if the certificate in question has been revoked via CRL or OCSP, if something fails or it's unable to determine the status it's listed as 'unknown'  does the RHEL 7.2 system not have access to the internet?

**Comment by johnakash** [comment]
Thanks a lot kevgliss. It seems to be working fine with us.
