### ISSUE TITLE
API for replacing an existing certificate and for checking the expiry date of SSL cert

### ISSUE THREAD

**Issue by johnakash** [Netflix/lemur#288]
Hi Team,

We are looking for two APIs, please let us know how can we create python script for the following operations

- Replacing Certificate
We would like to replace a certificate with new one which has been re-issued from the certificate authority. Please let us know if you need to have more clarity on this requirement. 

- Checking Expiry date
We are looking for an API which can fetch the expiry date of the certificate using a script execution.

Thanks,
Akash John

**Comment by johnakash** [comment]
Hi Team, do we have an update on this?

**Comment by kevgliss** [comment]
The APIs for accomplishing the above are documented... If there are gaps in how to use the API please open an issue where the documentation is unclear.

**Comment by johnakash** [comment]
Hi, we can see only listing part on the document (http://lemur.readthedocs.org/en/latest/developer/index.html#lemur.certificates.views.CertificatesReplacementsList) and no documentation on the same doc , could you please point me if there is any other documentation available to replace an existing certificate?


 If no, I will open a task for documentation unclear.

**Comment by kevgliss** [comment]
The API (and documentation) does not provide exact endpoints to do what you currently would like. Instead it's up to you to use the existing APIs to accomplish the task at hand. 

For instance if you want to "replace" a certificate:
The docs at: http://lemur.readthedocs.org/en/latest/developer/index.html#post--certificates point out a "replacement" field that allows you specify an existing certificate to replace (of which you must pass the ID). 

Additionally, if you are not generating a certificate within Lemur the upload endpoint allows for the same specification.
http://lemur.readthedocs.org/en/latest/developer/index.html#post--certificates-upload

Checking the expiration date is simply iterating over all the certificates and looking for your date in the response json. There is currently no API that allows you to query for all certificates with a given expiration date. If you would like to add such functionality I would be more than happy to merge that in.

**Comment by johnakash** [comment]
Hi kevgliss,

We were able to fetch the expiry date with APIs, please find the script below,
#!/usr/bin/python
import json
import requests

login = requests.request("POST",
    "http://10.1.1.1/api/1/auth/login",
    data=json.dumps({'username': "lemur", 'password': "test"}),
    headers={'content-type': 'application/json'}
)

login.json()["token"]
#print login.json()

Auth = {'Authorization': 'token %s' %login.json()["token"], 'content-type': 'application/json'}

list = requests.request("GET",
"http://10.1.1.1/api/1/certificates",
headers=Auth
)
width = 20

print "DNS Name"+',',"Expiry.Date"+','
data = list.json()
rawdata = data['items']
for item in rawdata:
  print item["cn"]+',', str (item["notAfter"])

**Additionally, if you are not generating a certificate within Lemur the upload endpoint allows for the same specification.
http://lemur.readthedocs.org/en/latest/developer/index.html#post--certificates-upload**

This not seems to be working with us. Please let us know if we need to try some other method to perform certificate replacement using APIs.

**Comment by kevgliss** [comment]
Can you describe 'not working`? Do you get an error? Does it now upload?

**Comment by johnakash** [comment]
Hi Kevgliss,

We are apologizing in the delay in response.

We are neither getting an error nor getting reflecting the changes on the console. Please find the script below. 

#!/usr/bin/python
import json
import requests

login = requests.request("POST",
    "http://10.1.1.1/api/1/auth/login",
    data=json.dumps({'username': "lemur", 'password': "admin"}),
    headers={'content-type': 'application/json'}
)

login.json()["token"]
print login.json()

Auth = {'Authorization': 'token %s' %login.json()["token"], 'content-type': 'application/json'}

rootcert = open('/home/11/scripts/123/certificate.pem', 'rw')
privatecert = open('/home/11/scripts/123/private.pem', 'rw')

upload = requests.request("GET",
"http://10.1.1.1/api/1/certificates/18/replacements",
data=json.dumps({"owner": "user@domain.com", "publicCert": rootcert.read(), "privateKey": privatecert.read(), "destinations": [], "notifications": [], "replacements": [], "name": "akash-replacements" }),
headers=Auth
)

print upload.json()


Could you please let us know how can we fullfill our requirement?

Thanks,
Akash John

**Comment by kevgliss** [comment]
Ah, to upload a certificate you need the upload [endpoint](http://lemur.readthedocs.io/en/latest/developer/index.html#lemur.certificates.views.CertificatesUpload). Here, in the replacement field you would specify the certificate you wish to replace, e.g. ```replacements: [{"id": <replaced-certificate-id>}]```

**Comment by johnakash** [comment]
Great!! it worked.. Thanks a lot. 

Please find the worked script below,

#!/usr/bin/python
import json
import requests

login = requests.request("POST",
    "http://10.1.1.1/api/1/auth/login",
    data=json.dumps({'username': "lemur", 'password': "p@ss123"}),
    headers={'content-type': 'application/json'}
)

login.json()["token"]
print login.json()

Auth = {'Authorization': 'token %s' %login.json()["token"], 'content-type': 'application/json'}

rootcert = open('certificate.pem', 'rw')
privatecert = open('private.pem', 'rw')

upload = requests.request("POST",
"http://10.1.1.1/api/1/certificates/upload",
data=json.dumps({"owner": "user@domain.com", "publicCert": rootcert.read(), "privateKey": privatecert.read(), "destinations": [], "notifications": [], "replacements": [{"id": 18}], "name": "replacetest" }),
headers=Auth
)

**Comment by johnakash** [comment]
Hi kevgliss, so could you please let us know what is the purpose of the replacements endpoint?

**Comment by kevgliss** [comment]
The purpose it have an audit trail of when certificate has been superseded and is no longer needed.
