### ISSUE TITLE
Error on LDAP authentication

### ISSUE THREAD

**Issue by Gutttlt** [Netflix/lemur#2888]
There is a problem logging in a LDAP user. A user can't be logged in and the message 

> ERROR in views: ldap error: 'Role' object has no attribute 'set_third_party'

 appears in logs.

It looks like a copy-paste error and can be easily fixed:

```
--- a/lemur/auth/ldap.py
+++ b/lemur/auth/ldap.py
@@ -98,7 +98,7 @@ class LdapPrincipal():
             role = role_service.get_by_name(self.ldap_default_role)
             if role:
                 if not role.third_party:
-                    role = role.set_third_party(role.id, third_party_status=True)
+                    role = role_service.set_third_party(role.id, third_party_status=True)
                 roles.add(role)
```

Could one of the contributors make a commit please?
Backporting to 0.7.0 would be also great.

**Comment by hosseinsh** [comment]
hi @Gutttlt,  thank you for brining  this up. Would you mind creating a Pull Request with the one liner? 
we are not using LDAP, hence difficult to test.

**Comment by Gutttlt** [comment]
Done, see https://github.com/Netflix/lemur/pull/2890.

**Comment by hosseinsh** [comment]
Merged the PR.
