### ISSUE TITLE
Vault plugin not showing  after installation

### ISSUE THREAD

**Issue by sreejit2410** [Netflix/lemur#2892]
Hi Team,

I was trying to install lemur vault. getting the below error.

Processing /usr/local/src/lemur/lemur/plugins/lemur_vault
Collecting Flask
  Using cached Flask-1.1.1-py2.py3-none-any.whl (94 kB)
ERROR: Could not find a version that satisfies the requirement lemur (from lemur-vault==0.4) (from versions: none)
ERROR: No matching distribution found for lemur (from lemur-vault==0.4)

**Comment by jmcrawford45** [comment]
lemur vault plugin is not a separate package so you should be able to just install lemur and use the plugin
