### ISSUE TITLE
Clarify the appropriate version of Python required

### ISSUE THREAD

**Issue by mcandre** [Netflix/lemur#2895]
Please clarify the right version of Python to use when contributing to this project:

* In `README.rst` file
* In `.python-version` file

**Comment by mcandre** [comment]
Relates to #2894

**Comment by mcandre** [comment]
Propose setting Python to 2.7.17, the most up-to-date edition of Python in the 2.x series, at least.

https://www.python.org/downloads/

**Comment by hosseinsh** [comment]
Thanks for your input. have updated the readme file

the python version required is defined here:
https://github.com/Netflix/lemur/blob/master/.travis.yml#L12-L13
and here in the  docs:
https://lemur.readthedocs.io/en/latest/quickstart/index.html?highlight=python#dependencies
