### ISSUE TITLE
Release 0.8

### ISSUE THREAD

**Issue by mcandre** [Netflix/lemur#2904]
It's been a few moons since the last release.

https://github.com/Netflix/lemur/releases

**Comment by sirferl** [comment]
@hosseinsh : Can I help you here?

**Comment by hosseinsh** [comment]
cutting a new release has been in the back of my head since longer, particularly as some major features and plugins have been added to Lemur since the last release. I will try to prioritize this in the coming weeks.

**Comment by hoerup** [comment]
Any news on this ?

**Comment by hoerup** [comment]
Still No news regarding a release ??

**Comment by sirferl** [comment]
Maybe the next release is a bit harder to build, but we should do this more often...

**Comment by hosseinsh** [comment]
@sirferl agree with you, planing to make it a recurring event.

**Comment by hosseinsh** [comment]
new Lemur release completed
https://pypi.org/project/lemur/0.8.0/
