### ISSUE TITLE
failing local dev because of 404 on webgui

### ISSUE THREAD

**Issue by harmw** [Netflix/lemur#291]
When trying to setup a local dev env on OSX I'm getting a 404 when browsing to `http://localhost:3000`. Feels like something completely unrelated to lemur itself, but what could I be doing wrong here?

`lemur --config=/Users/me/.lemur/lemur.conf.py start -b localhost:3000 --log-level debug`

```
[2016-04-24 23:06:36 +0200] [70738] [INFO] Starting gunicorn 19.4.1
[2016-04-24 23:06:36 +0200] [70738] [DEBUG] Arbiter booted
[2016-04-24 23:06:36 +0200] [70738] [INFO] Listening at: http://127.0.0.1:3000 (70738)
[2016-04-24 23:06:36 +0200] [70738] [INFO] Using worker: sync
[2016-04-24 23:06:36 +0200] [70741] [INFO] Booting worker with pid: 70741
[2016-04-24 23:06:36 +0200] [70738] [DEBUG] 1 workers
[2016-04-24 23:06:40 +0200] [70741] [DEBUG] GET /
```

Installation was done per the docs, so using `make develop` from the root of a clean checkout of _master_.

**Comment by kevgliss** [comment]
If you take a look at docs [here](http://lemur.readthedocs.org/en/latest/developer/index.html#developing-with-flask), It mentions that `start` isn't typically the best for doing dev work. Instead it's suggested that you use the `runserver` command as that creates a single threaded flask webserver. 

Additionally, in a dev environment the API and the GUI run on different ports. The frontend is merely static javascript that the API does not serve. In production we rely on nginx serving up these assets. For dev we rely on the the gulp command `gulp serve` to serve the assets. 

This second step looks a like a gap in the docs. I will work on adding it in, there is also an additional configuration variable you will need to add to your configuration `CORS = True` to allow the GUI to talk to the API in dev.

**Comment by harmw** [comment]
The docs are indeed a bit messy to the uninitiated, but thanks :sweat_smile:
So I'm looking at two commands for local development: `lemur runserver` to get the API online on localhost:5000 and `gulp serve` to get a webgui on localhost:someport. But where do I get *gulp*?

**Comment by kevgliss** [comment]
I opened up #293 to hopefully clarify this a bit. Gulp should be installed when you installed Lemur.

**Comment by harmw** [comment]
right: `$ ./node_modules/.bin/gulp serve`

**Comment by harmw** [comment]
excellent @kevgliss, thanks. One remaining issue I don't get: how to tie both `gulp` and `lemur` together, because right now the webgui shows only some non-clickable buttons

**Comment by kevgliss** [comment]
What do you mean non-clickable? My local dev process is usually:

```
~/D/C/P/g/f/lemur git:master ❯❯❯ lemur runserver -p 8000                                                                                                                                                                           ⬆ ✭ ◼
/Users/kglisson/.virtualenvs/lemur/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
 * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
```

then in a separate terminal:
```
~/D/C/P/g/f/lemur git:master ❯❯❯ gulp serve                                                                                                                                                                                        ⬆ ✭ ◼
[12:46:08] Using gulpfile ~/Documents/Code/Python/github/forks/lemur/gulpfile.js
[12:46:08] Starting 'dev:styles'...
[12:46:08] Starting 'dev:scripts'...
[12:46:08] Starting 'dev:fonts'...
[12:46:10] all files 167.28 kB
[12:46:10] Finished 'dev:styles' after 1.76 s
[12:46:10] Finished 'dev:fonts' after 1.83 s
[12:46:10] all files 77.95 kB
[12:46:10] Finished 'dev:scripts' after 2.16 s
[12:46:10] Starting 'dev:inject'...
[12:46:10] gulp-inject 47 files into index.html.
[12:46:10] gulp-inject 32 files into index.html.
[12:46:10] gulp-inject 1 files into index.html.
[12:46:10] Finished 'dev:inject' after 81 ms
[12:46:10] Starting 'watch'...
[12:46:10] Finished 'watch' after 15 ms
[12:46:10] Starting 'serve'...
[12:46:10] Finished 'serve' after 80 ms
[BS] Access URLs:
 -------------------------------------------------
       Local: http://localhost:3000/index.html
    External: http://10.16.179.236:3000/index.html
 -------------------------------------------------
          UI: http://localhost:3001
 UI External: http://10.16.179.236:3001
 -------------------------------------------------
[BS] Serving files from: .tmp
[BS] Serving files from: lemur/static/app
[BS] Watching files...
```
Ensure that your conf.py has at least the following:
```
debug = True
CORS = True
```
By default the Javascript know to talk to the API on port 8000, so they should be able to communicate between themselves without any effort on your part.

**Comment by harmw** [comment]
Ah, the default is `-p 8000`. Now it all _just works_. I obviously skipped this in the docs since it is listed under **Setup a Reverse Proxy**, which I don't plan on using for local dev.
I should be able to build plugins now, thanks!

**Comment by kevgliss** [comment]
Awesome!
