### ISSUE TITLE
Kubernetes plugin TLS secret format sends chain certificate instead of requested public certificate

### ISSUE THREAD

**Issue by dpaar** [Netflix/lemur#2913]
In https://github.com/Netflix/lemur/blob/master/lemur/plugins/lemur_kubernetes/plugin.py#L96
```
if secret_format == "TLS":
    secret["type"] = "kubernetes.io/tls"
        secret["data"] = {
            "tls.crt": base64encode(cert_chain),
            "tls.key": base64encode(private_key),
}
```

This should be `"tls.crt": base64encode(body),`.

**Comment by hosseinsh** [comment]
Hi @dpaar, we don't use that plugin internally, and hence difficult to test. Would you mind raising a PR?

**Comment by sirferl** [comment]
Hi @hosseinsh 
Hello, we can do that. I just want to hear the opinion of @wfhartford, if he's available.
regards
sirferl

**Comment by wfhartford** [comment]
Thanks for mentioning me here, but I have no strong opinion on this, and can't remember why I opted for the chain rather than just the cert. After implementing the changes for Kubernetes, I ended up going a different way for our certificate management so changes here won't hurt me.

**Comment by sirferl** [comment]
@wfhartford : Thank you for the response.
We will proceed with the PR.
If I may ask: what did you end up with for managing certificates ?

**Comment by wfhartford** [comment]
I can't remember why exactly I decided to move away from Lemur, which probably could have satisfied both of my use cases, but I ended up using cert-manager for my publicly trusted certs and a very small and specialised program written in go for my internal CAs.

**Comment by sirferl** [comment]
@wfhartford : thanks for the update.

**Comment by hosseinsh** [comment]
Merged the PR.
