### ISSUE TITLE
weird behavior after login

### ISSUE THREAD

**Issue by harmw** [Netflix/lemur#295]
On local dev, I'm getting weird login behavior:
```
127.0.0.1 - - [28/Apr/2016 21:36:12] "GET /api/1/auth/providers HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2016 21:36:12] "GET /api/1/auth/me HTTP/1.1" 401 -
127.0.0.1 - - [28/Apr/2016 21:36:13] "GET /api/1/auth/me HTTP/1.1" 401 -
127.0.0.1 - - [28/Apr/2016 21:36:26] "OPTIONS /api/1/auth/login HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2016 21:36:27] "POST /api/1/auth/login HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2016 21:36:32] "OPTIONS /api/1/auth/me HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2016 21:36:32] "OPTIONS /api/1/auth/me HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2016 21:36:32] "OPTIONS /api/1/certificates?count=10&page=1&sortBy=id&sortDir=desc HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2016 21:36:32] "GET /api/1/auth/me HTTP/1.1" 403 -
127.0.0.1 - - [28/Apr/2016 21:36:32] "GET /api/1/auth/me HTTP/1.1" 403 -
127.0.0.1 - - [28/Apr/2016 21:36:32] "GET /api/1/certificates?count=10&page=1&sortBy=id&sortDir=desc HTTP/1.1" 403 -
127.0.0.1 - - [28/Apr/2016 21:41:54] "GET /api/1/sources?count=10&page=1&sortBy=id&sortDir=desc HTTP/1.1" 403 -
127.0.0.1 - - [28/Apr/2016 21:41:54] "GET /api/1/destinations?count=10&page=1&sortBy=id&sortDir=desc HTTP/1.1" 403 -
127.0.0.1 - - [28/Apr/2016 21:41:54] "GET /api/1/plugins?type=destination HTTP/1.1" 403 -
```
Login is fine, but the login button in the upper-right doesn't change to read something like _profile_ and lists are empty. The 403's in the above are also highly unexpected.

Actual response from that last GET to _/api/1/plugins_:
```
message:"Token is invalid"
```

**Comment by kevgliss** [comment]
Weird, few things to check. Make sure the Lemur is indeed sending a authorization token along with those requests. And make sure your `LEMUR_TOKEN_SECRET` is set in your config.

Relevant [code](https://github.com/Netflix/lemur/blob/master/lemur/auth/service.py#L100)

**Comment by harmw** [comment]
Doesn't like like it. The response is a piece of JSON with the _token_ key inside, but there is no _Authorization_-header. After the POST to `login` I can observe **7** OPTIONS requests to `me`, all with no apparent request nor response body. The 8th OPTIONS request yields a 403, and contains the above message about the invalid token. This request _does_ however contain the _Athorization_-field.

Let me debug a little how that code works out compared to my observations, thanks. `LEMUR_TOKEN_SECRET` is set per `lemur init` (or whatever the cmd was).

**Comment by kevgliss** [comment]
This is the flow I would expect:

![screen shot 2016-05-02 at 10 14 11 am](https://cloud.githubusercontent.com/assets/2262214/14961494/a61ec426-104e-11e6-93c0-c773a0226d3c.png)

The post to Login should indeed return a token, then the calls to /me should include that same token in the Authorization header.

![screen shot 2016-05-02 at 10 14 11 am](https://cloud.githubusercontent.com/assets/2262214/14961525/d4930402-104e-11e6-9ddc-925b946ee394.png)

I've never see an option request yield a 403, is `DEBUG=True` set in your lemur.conf? This is what enables CORS that is use for development.

**Comment by harmw** [comment]
yep, both `debug` and `cors` are set to **True**.

**Comment by harmw** [comment]
after injecting this it all magically started working:
```
        options = {
              'verify_signature': False,
              'verify_exp': False,
              'verify_nbf': False,
              'verify_iat': False,
              'verify_aud': False,
              'require_exp': False,
              'require_iat': False,
              'require_nbf': False
           }
```
Not a solution, but I should be able to finally start some work now.

**Comment by kevgliss** [comment]
It looks like the the satellizer library isn't injecting the token from local storage into your requests... This is the line that should set your token:

https://github.com/Netflix/lemur/blob/master/lemur/static/app/angular/authentication/services.js#L13

We might be running into this:
https://github.com/sahat/satellizer/issues/777 as I don't see the token in your /me request.

Are there any errors in the browser or on the app that I could look into?

**Comment by kevgliss** [comment]
@harmw Was this ever resolved?

**Comment by harmw** [comment]
hi Kev, didn't look into anything Lemur recently so sadly no

**Comment by harmw** [comment]
Strangely, I'm observing this error again after a recent and all-fresh `git pull`.

**Comment by kevgliss** [comment]
Do you know if this is browser specific?

**Comment by harmw** [comment]
Doesn't look like it, just tried both Firefox and Chrome and got the same error (eg. 403).

**Comment by kevgliss** [comment]
Are you still receiving `access-control-max-age: b'21600'` in your response? Are you running under python3 or python2? It that looks like a unicode issue that could be messing stuff up.

**Comment by harmw** [comment]
Request:
```
Host: localhost:8080
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0ODE2NjYwOTcsInN1YiI6MSwiZXhwIjoxNDgxNzUyNDk3fQ.eGwLLgBbXpyIT6IuANALq7Z6Oy-2_UXRWGPVavqrXkm
Referer: http://localhost:8080/
Cookie: mp_3dc73f826819c8e11d0d9898ca4291c8_mixpanel=%7B%22distinct_id%22%3A%20%2215766860b8676-0b97ad1b9e289d8-485863-1aeaa0-15766860b87317%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D; rc_uid=ZmMM4pMfX2xSapL5E; rc_token=ori8ST4pwxG8YZ97fB49hhxvEYvJgwYn3eolv-wzTqT; session=eyJpZGVudGl0eS5hdXRoX3R5cGUiOm51bGwsImlkZW50aXR5LmlkIjoxfQ.CzHyXw.zT3LCNEgqvFk-IxMViNaGzuywla
DNT: 1
Connection: keep-alive
```
Response:
```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
Access-Control-Allow-Methods: DELETE, GET, HEAD, OPTIONS, POST, PUT
Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Max-Age: b'21600'
Connection: keep-alive
Content-Length: 31
Content-Type: application/json
Date: Tue, 13 Dec 2016 19:20:47 GMT
Server: nginx/1.11.5
Set-Cookie: session=eyJpZGVudGl0eS5hdXRoX3R5cGUiOm51bGwsImlkZW50aXR5LmlkIjoxfQ.CzHzTA.gV7dy3wqzz7POAJ3xiVmyV3QIE9; HttpOnly; Path=/
```
Python2 and yes that header is still set.

**Comment by kevgliss** [comment]
So, 0.4 was the last release to support python 2.x. Master currently only supports python 3.5+. I would run the development app under python 3.5 and see if that helps or you can checkout the 0.4 release and see if you encounter the same issue.

**Comment by harmw** [comment]
aha! lets see if bringing in Python3 solves this!

**Comment by harmw** [comment]
fixed!

**Comment by kevgliss** [comment]
Nice!
