### ISSUE TITLE
What is certificate Relpacement

### ISSUE THREAD

**Issue by vinish86** [Netflix/lemur#296]
Can you give me an idea of what exactly will happen if I am performing a certificate replacement on Lemur? Will it be replacing the existing certificate with new one with same name?

**Comment by kevgliss** [comment]
Currently, replacement is only a record keeping action. It does not re-issue certificates, it merely tracks that a given certificate was superseded by another. Additionally, 'replacing' a certificate marks it as in-active meaning no expiration notifications will be sent.
