### ISSUE TITLE
Issuer Plugin: Pending Certificate Creation results in Redis Connection Error

### ISSUE THREAD

**Issue by selwynoh** [Netflix/lemur#2983]
I am implementing the create_certificate method for an Issuer plugin. For a certificate that is awaiting approval, I return a request_id instead of the certificate:
return None, None, request_id

This results in the following error, when I submit a create certificate request. The UI hangs, and I eventually get this error in the console:
[2020-05-21 00:42:50,596] ERROR in redis: {'function': 'lemur.common.redis.redis', 'message': 'Redis Connection error', 'host': 'localhost', 'port': 6379}
{'function': 'lemur.common.redis.redis', 'message': 'Redis Connection error', 'host': 'localhost', 'port': 6379}
{'function': 'lemur.common.redis.redis', 'message': 'Redis Connection error', 'host': 'localhost', 'port': 6379}
[2020-05-21 00:43:20 +0000] [10535] [CRITICAL] WORKER TIMEOUT (pid:10539)
[2020-05-21 00:43:20 +0000] [10539] [INFO] Worker exiting (pid: 10539)
[2020-05-21 00:43:20 +0000] [10547] [INFO] Booting worker with pid: 10547

However, the pending certificate is created successfully (appears on the pending certificates page).

**Comment by hosseinsh** [comment]
in case you are developing locally 

you might want to setup a local `redis-server`

```
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379'
CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
```

**Comment by selwynoh** [comment]
Thanks. I added CELERY_RESULT_BACKEND, CELERY_BROKER_URL, and REDIS_HOST to lemur.conf.py. I no longer get the Redis Connection errors, but still get the CRITICAL WORKER TIMEOUT.

It appears to be timing out on the "from lemur.common.celery import fetch_acme_cert" line in lemur.certificates.service.py:

    if isinstance(cert, PendingCertificate):
        # We need to refresh the pending certificate to avoid "Instance is not bound to a Session; "
        # "attribute refresh operation cannot proceed"
        pending_cert = database.session_query(PendingCertificate).get(cert.id)
        **from lemur.common.celery import fetch_acme_cert**
        if not current_app.config.get("ACME_DISABLE_AUTORESOLVE", False):
            fetch_acme_cert.apply_async((pending_cert.id,), countdown=5)
