### ISSUE TITLE
Chain Certificate is not exporting

### ISSUE THREAD

**Issue by johnakash** [Netflix/lemur#301]
Hi Team,

While extracting .p12 formatted file (which was exported from Lemur) we cannot find the Chain file on the same. Could you please let us know if we need to perform any additional step to download the .p12 along with the chain. 

Thanks,
Akash John

**Comment by kevgliss** [comment]
Verified this as a bug. Will look into a fix.

**Comment by johnakash** [comment]
Thanks kevgliss. **You guys are awesome**..  now we are able to export the chain certificate.
