### ISSUE TITLE
Add documentation to reuse ACME accounts

### ISSUE THREAD

**Issue by peschmae** [Netflix/lemur#3149]
Currently there is no documentation, on how to configure an ACME account, that is used for all certificates.

The current implementation creates a new account for each certificate request (as well as renewal), which can lead to a rate limit exhaustion.
In #3129 an additional issue was discovered that can be resolved using a preconfigured ACME account, but it's not entirely clear how to configure the `ACME_PRIVATE_KEY` and `ACME_REGR` properly.

It took me some time to figure out, how to properly set these two variables, so they work as intended, thus I propose to add a paragraph on how to configure it, and also how to convert a private key PEM to the JWK format required by the acme_client.

**Comment by peschmae** [comment]
I'll work on this, and create a pull request with the documentation update

**Comment by hosseinsh** [comment]
Thanks for taking on the task of improving the  documentation around ACME setup.
As mentioned in #3129, setting up `ACME_PRIVATE_KEY` and `ACME_REGR` would allow reusing an existing account 

https://github.com/Netflix/lemur/blob/983f9beacb85cb1ecb8ce10a5028d2664dffed23/lemur/plugins/lemur_acme/plugin.py#L237-L251

These links might provide more insight.
https://letsencrypt.org/docs/account-id/
https://cert-manager.io/docs/configuration/acme/#external-account-bindings


One can also  use the Lemur flow to register a new account, and while doing so,  extract the private key and account ID and persisting them

**Comment by rb5acgusr** [comment]
In case of LetsEncrypt Lemur flow might generate ACME Account ID and Private Key. I tried to use the account and key details obtained during certbot register process. However, Lemur is failing with malformed URI if I use in this format. 

'{"body": {}, "uri": "https://acme.sectigo.com/v2/InCommonRSAOV/acct/EAB_KID"}'

When I use 

'{"body": {}, "uri": "https://acme.sectigo.com/v2/InCommonRSAOV"}'

then it fails with externalAccountBinding error. What we need is a simple example updating lemur.conf.py to pass ACME_REGR and ACME_PRIVATE_KEY in JWK or any other format that works :-)

**Comment by peschmae** [comment]
For now I'll just add documentation about how to reuse an existing acme account.

But all in all I think it would preferable to have the account information stored in the authority when a new one is created. This would also allow to implement the `revoke_certificate` function, which is currently missing in the acme plugin.

**Comment by peschmae** [comment]
I've opened an issue, to implement storing the account credentials when a new account was created #3152

It would also make sense to create an issue for the  externalAccountBinding, but since I don't have a certificate authority, using ACME and EAB I can't test it, and thus can't implement it.
