### ISSUE TITLE
Problem with tests

### ISSUE THREAD

**Issue by sirferl** [Netflix/lemur#3156]
I tried to run py.test -v from the plugins/lemur_entrust directory and get the following message:
$ py.test -v
ImportError while loading conftest '/opt/lemur/lemur/plugins/lemur_entrust/tests/conftest.py'.
tests/conftest.py:1: in <module>
    from lemur.tests.conftest import *  # noqa
../../tests/conftest.py:23: in <module>
    from .factories import (
../../tests/factories.py:3: in <module>
    from factory import Sequence, post_generation, SubFactory
E   ModuleNotFoundError: No module named 'factory'

I have no experience with pytest. Can anyone help?

**Comment by sirferl** [comment]
found it :
missed pip install factory_boy

**Comment by hosseinsh** [comment]
in addition to `pytest -v lemur/plugins/lemur_entrust/tests/test_entrust.py::test_process_options`, using the debug mode in Pycharm is nice for developing and debugging tests
