### ISSUE TITLE
Ignore "revoked" certificates when checking for revoked status

### ISSUE THREAD

**Issue by sirferl** [Netflix/lemur#3195]
Certificates already flagged as "revoked" in the Lemur-DB should be left out of the check for revoke status.
IMHO somewhere here in check_revoked(): (from cli.py) or get_all_valid_certs (from services.py) the filter has to be implemented.

**Comment by hosseinsh** [comment]
hi @sirferl, good point, we can revise this method `get_all_valid_certs` to ignore revoked certs, which falls under `not valid`

https://github.com/Netflix/lemur/blob/ea33fe997941cd3dd208a7b82a75f58a62ad4188/lemur/certificates/service.py#L106-L124

**Comment by hosseinsh** [comment]
addressed in https://github.com/Netflix/lemur/pull/3207

**Comment by sirferl** [comment]
thank you @hosseinsh for the quick response and the improvements for entrust_plugin.
