### ISSUE TITLE
Can Lemur push certificates to a remote machine and restart the respective service?

### ISSUE THREAD

**Issue by Alestrix** [Netflix/lemur#3225]
Please mark this issue as question, thanks.

### Background
I am trying to evaluate whether Lemur might fit our needs by browsing through the documentation, though there are still many questions I cannot find the answer to.

For our use case Lemur would have to either (not decided yet)

- create the private key + CSR pair or
- receive the CSR via some API
 
and then retrieve a signed certificate from the PKI using EST or some REST based API.

Next, the certificate and possibly the private key need to be pushed (SFTP) to the target system and probably one or more services on the target system need to be restarted.

### Questions
The documentation has no mentioning of SFTP, but apparently there is an SFTP plugin that can deploy certificates (and private keys?) "in nginx or apache format" on a remote path. But I cannot find documentation on:

- What is the difference between those two formats? Can the file(s?) include the private key, if available to Lemur? Do the file(s) include intermediates?
- After pushing the file(s), can Lemur use ssh to execute some service restart or config reload command on the remote machine?
- Can Lemur deploy a certificate into a **remote** Java key store?
- Can Lemur monitor Certificate validity and, N days before end of validity, automatically (if private key is accessible to Lemur) re-create a CSR, get a cert, and deploy it, all without user intervention?

Thanks!

**Comment by hosseinsh** [comment]
Hi @Alestrix, 

both of the use-cases are supported in Lemur: 

> create the private key + CSR pair or
> receive the CSR via some API

One can interact with Lemur either via REEST API or the UI which is also API driven. It is possible to dramatically retrieve a cert and the respective private key, as long as the user has the permissions to do so. Each cert has an owner, and also a set or definable Roles who can access the certificate's private key. 

Correct, there is a SFTP plugin, contributed by the plugin, and would support uploading the cert and also the private key to the destination:

https://github.com/Netflix/lemur/blob/master/lemur/plugins/lemur_sftp/plugin.py#L115-L122


It can certainly be expanded to supported other formats, if necessary.

>  Do the file(s) include intermediates?
They do. 

> After pushing the file(s), can Lemur use ssh to execute some service restart or config reload command on the remote machine?

That functionality is not supported today. Lemur can rotate certs on Load Balancers. 
You might want a daemon that checks for a new certificate, and bouncers thee server.
Alternatively, you 

> Can Lemur deploy a certificate into a remote Java key store?

not today. hopefully not much effort to add such a plugin.

> Can Lemur monitor Certificate validity and, N days before end of validity, automatically (if private key is accessible to Lemur) re-create a CSR, get a cert, and deploy it, all without user intervention? 

Yes, as a matter of fact, this is the main reason we use Lemur internally to manage all browser-trusted TLS certificates in our fleet. This functionality is referred to as Auto-rotate. 30 days before expiry Lemur issue a new certificate (new CSR and private key) for the same domain, and uploads it to the defined destinations. If the destination is a Load balancer, Lemur attaches it to the Load balancer. For edge-cases, where Lemur can't rotate the cert, one can set up notifications, to get reminded. 

There might also be use-cases, where they need to create many certs, and they would talk to Lemur via API.
