### ISSUE TITLE
How to request a certificate with Client Authentication enabled

### ISSUE THREAD

**Issue by drcursor** [Netflix/lemur#3234]
Please mark this issue as question.

I'm trying to request a certificate via the REST API with Client Authentication Extended Key Usage enabled, but I can't find any way to do it. Is there any way to do it ?

Thank you.

**Comment by hosseinsh** [comment]
I usually use the UI as a short cut to cheat on the Query format: 

```
{
  "country": "US",
  "state": "California",
  "location": "Los Gatos",
  "organization": "myCompany",
  "authority": {
    "name": "LetsEncrypt",
  },
  "validityType": "customDates",
  "keyType": "RSA2048",
  "owner": "youremail@somewhere",
  "commonName": "yourdomain.net",
  "extensions": {
    "subAltNames": {
      "names": [
        {
          "nameType": "DNSName",
          "value": "yourdomain.net"
        }
      ]
    },
    "extendedKeyUsage": {
      "useClientAuthentication": true
    },
    "custom": []
  },
  "description": "test",
  "validityStart": "2020-11-04T08:00:00.000Z",
  "validityEnd": "2020-11-06T08:00:00.000Z",
}
```

**Comment by drcursor** [comment]
Thank you for the very quick answer.
I still haven't been able to figure out which one of the request options causes the certificate to have the following information:
>             X509v3 Basic Constraints: critical
>             CA:FALSE
