### ISSUE TITLE
EntrustSourcePlugin get_certificates not needed

### ISSUE THREAD

**Issue by yiluzhu** [Netflix/lemur#3256]
In file /lemur/plugins/lemur_entrust/plugin.py, the EntrustSourcePlugin is defined.  However its method get_certificates is not implemented, and the comment is "Not needed for ENTRUST".

I don't understand why this method is not needed.  How does this source plugin work then?

**Comment by yiluzhu** [comment]
@sirferl 
Hi there.  I can see you've added this comment.  Can you give some details, please?

**Comment by hosseinsh** [comment]
Hi @yiluzhu, the source plugin is not implemented for Entrust, but the issuer plugin is implemented. This means you can issue certificates via Entrust
https://github.com/Netflix/lemur/blob/master/lemur/plugins/lemur_entrust/plugin.py#L206-L256



However, you cannot sync already issued certs in Entrust to Lemur. 
Is that a functionality you need?

**Comment by yiluzhu** [comment]
Hi Hossein, thanks for your reply.  Yes we do need this functionality.  

You said "you cannot sync already issued certs in Entrust to Lemur", did you mean the code is not implemented?  Or Entrust does not allow Lemur to import its certificates?

**Comment by sirferl** [comment]
hi @yiluzhu it is not implemented at the moment. If there is a demand, I can work in it.

**Comment by yiluzhu** [comment]
Thank you very much, @sirferl .  If you could work on it that would be really appreciated.

**Comment by yiluzhu** [comment]
@sirferl @hosseinsh how are you doing, guys?  Have you got a chance to start the source plugin for Entrust?

**Comment by hosseinsh** [comment]
Hi @yiluzhu, I don't have it planned on my roadmap to add the source plugin for Entrust, but happy to review it if anyone raises a PR.

**Comment by sirferl** [comment]
Hello, I just added a pull request with this functionality.
Sorry that I am not as responsive as I hope to be at the moment,
But there is a lot of other work in my company at the moment to do.
regards

**Comment by yiluzhu** [comment]
Hi @sirferl , thank you very much for your help! That is much quicker than I expected!

**Comment by sirferl** [comment]
@yiluzhu you're welcome. Please Test it before putting into production. I could just make a quick rundown. If you encounter any errors I will fix them ASAP!

**Comment by yiluzhu** [comment]
Yes I will test it. Thanks.

**Comment by hosseinsh** [comment]
@yiluzhu this the PR, if you would like to do some local testing, provide your feedback: 

https://github.com/Netflix/lemur/pull/3280

**Comment by sirferl** [comment]
@yiluzhu added a few more fields from the entrust information

**Comment by sirferl** [comment]
@yiluzhu Does this work for you? If yes, we should close the issue.

**Comment by yiluzhu** [comment]
The testing team is still testing it, and so far so good.  I think we can close it for now.

Thanks again for your help.
