### ISSUE TITLE
Drop support for python2.7

### ISSUE THREAD

**Issue by kevgliss** [Netflix/lemur#340]
I don't think there is anything holding us back from exclusively supporting python3, wondering if there is a strong preference to sticking with python2.7?

**Comment by neilschelly** [comment]
Things are currently in a state in between both python2 and python3. I favor moving forward. I know there are several bytes() calls that probably need to be changed into bytes(something,'utf-8') calls for example.

I'm volunteering to help with this effort.

**Comment by kevgliss** [comment]
There have been several issues with maintaining python2/3 compatibility, internally we are moving to python3 so it will be the best supported going forward. I will reach out to some other larger users before deciding.

**Comment by kevgliss** [comment]
@neilschelly I've talked to with most of the larger users and plan to move forward with dropping python2 support have 0.4 is released (should be later next week).

**Comment by neilschelly** [comment]
Awesome to hear. If I can help, let me know. I can start doing my testing/experimenting with python 3.4 and just start submitting PRs for things that I find as I find them? Or do you already have a branch that has most of that covered?

**Comment by kevgliss** [comment]
I don't have anything started as of yet, was planning to start after the 0.4. release. Feel free to submit PRs as you find them.

**Comment by kevgliss** [comment]
I have released 0.4 and will be actively removing python2 specific code.

**Comment by kevgliss** [comment]
Closed by #518. Let me know if there are any other remnants.
