### ISSUE TITLE
GET /certificates with query limit

### ISSUE THREAD

**Issue by arubasu** [Netflix/lemur#343]
Hi,

I am trying to get all the certificate(total 38) details with the following commands. But every time it is showing only 10 certificate details(default limit is 10). How to change the limit query inside the curl command.
$ curl  -H "Content-Type: application/json" -H "Authorization:Bearer $token" -X GET "http://1.2.3.4/api/1/certificates?limit=200"

Regards,
Arunava

**Comment by kevgliss** [comment]
Use the `count` argument instead of `limit`.

**Comment by arubasu** [comment]
Thanks Man. :)
Please change the Lemur documentation as well.

**Comment by kevgliss** [comment]
Updating now... thanks for the catch!

**Comment by arubasu** [comment]
You are welcome. :+1:
