### ISSUE TITLE
ACME_PRIVATE_KEY format

### ISSUE THREAD

**Issue by kojraai** [Netflix/lemur#3483]
Hi there!

I'm trying to create some new certs with an existing LE account and I'm unable to get this work. 

The following error message I got every time:

 Reusing existing ACME account
lemur_1     | [2021-03-16 23:04:15,158] ERROR in service: {'message': 'Exception minting certificate', 'issuer': 'R3', 'cn': 'lemur-test.mydomain.com'}
lemur_1     | Traceback (most recent call last):
lemur_1     |   File "/opt/lemur/lemur/certificates/service.py", line 365, in create
lemur_1     |     cert_body, private_key, cert_chain, external_id, csr = mint(**kwargs)
lemur_1     |   File "/opt/lemur/lemur/certificates/service.py", line 315, in mint
lemur_1     |     cert_body, cert_chain, external_id = issuer.create_certificate(csr, kwargs)
lemur_1     |   File "/opt/lemur/lemur/plugins/lemur_acme/plugin.py", line 242, in create_certificate
lemur_1     |     return acme_dns_challenge.create_certificate(csr, issuer_options)
lemur_1     |   File "/opt/lemur/lemur/plugins/lemur_acme/challenge_types.py", line 191, in create_certificate
lemur_1     |     acme_client, registration = self.acme.setup_acme_client(authority)
lemur_1     |   File "/opt/venv/lib/python3.8/site-packages/retrying.py", line 49, in wrapped_f
lemur_1     |     return Retrying(*dargs, **dkw).call(f, *args, **kw)
lemur_1     |   File "/opt/venv/lib/python3.8/site-packages/retrying.py", line 212, in call
lemur_1     |     raise attempt.get()
lemur_1     |   File "/opt/venv/lib/python3.8/site-packages/retrying.py", line 247, in get
lemur_1     |     six.reraise(self.value[0], self.value[1], self.value[2])
lemur_1     |   File "/opt/venv/lib/python3.8/site-packages/six.py", line 703, in reraise
lemur_1     |     raise value
lemur_1     |   File "/opt/venv/lib/python3.8/site-packages/retrying.py", line 200, in call
lemur_1     |     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
lemur_1     |   File "/opt/lemur/lemur/plugins/lemur_acme/acme_handlers.py", line 162, in setup_acme_client
lemur_1     |     regr = messages.RegistrationResource.json_loads(existing_regr)
lemur_1     |   File "/opt/venv/lib/python3.8/site-packages/josepy/interfaces.py", line 180, in json_loads
lemur_1     |     loads = json.loads(json_string)
lemur_1     |   File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
lemur_1     |     raise TypeError(f'the JSON object must be str, bytes or bytearray, '
lemur_1     | TypeError: the JSON object must be str, bytes or bytearray, not dict

My lemur.conf.py contains:

(I changed the sensitive data for this example)

ACME_URL = "https://acme-v02.api.letsencrypt.org"
ACME_EMAIL = "lemur@mydomain.com"
ACME_DIRECTORY_URL = "https://acme-v02.api.letsencrypt.org/directory"
ACME_REGR = {"body": {}, "uri": "https://acme-v02.api.letsencrypt.org/acme/acct/11111111"}
ACME_PRIVATE_KEY = """ 
{
    "kty": "RSA",
    "n": "yr1qBwHizA7ME_iV32bY10ILp.....",
    "e": "AQAB",
    "d": "llBlYhil3I.....",
    "p": "-5LW2Lewogo.........",
    "q": "zk6dHqHfHksd.........",
    "dp": "qfe9fFIu3mu.......",
    "dq": "cXFO-loeOyU.......",
    "qi": "AfK1sh0_8sLTb..........."
} 
"""

All of my values come from letsencrypt regr.json and private_key.json
I've also tried different format like ACME_PRIVATE_KEY = '{}' or ACME_PRIVATE_KEY = {} but always the same error msg.

The certificate generation works fine if I'm not defining the ACME_ values in the lemur.conf.py however my goal is to use an existing LE account. 

Any help is appreciated!

Thanks,
JK

**Comment by hosseinsh** [comment]
Hi @kojraai<

I suspect `ACME_REGR` might be causing this, since it is expected to be a string, not dict.
consider: 
```
ACME_REGR = `{}`
ACME_PRIVATE_KEY = '{}'
```

All the best of luck.
