### ISSUE TITLE
Custom Extension Does Not Honor String Type

### ISSUE THREAD

**Issue by zarfide** [Netflix/lemur#352]
When generating a certificate I asked for a custom extension and although I explicitly specified IA5String (0x16 ASN.1 tag) I get PrintableString (0x13 ASN.1 Tag).  This is also a regression as this worked a few months ago.

**Comment by mikegrima** [comment]
It may be related to fields not being included in: https://github.com/Netflix/lemur/blob/master/lemur/schemas.py#L197-L200

```
class CustomOIDSchema(BaseExtensionSchema):
    oid = fields.String()
    oid_type = fields.String(validate=validators.oid_type)
    value = fields.String()
```

We will try to add more fields in and test.

**Comment by zarfide** [comment]
Based on what CloudCA wants I think "oid_type" needs to be "encoding".

           ```
"custom" : [{
                   "oid" : "1.2.3.4.5",
                   "isCritical" : false,
                   "encoding" : "ia5string",
                   "value" : "MY_VALUE"
           }
```

**Comment by mikegrima** [comment]
`oid_type` should be renamed to `encoding`.

**Comment by mikegrima** [comment]
Submitting a PR now.

**Comment by mikegrima** [comment]
Testing the PR.

**Comment by mikegrima** [comment]
Done.

**Comment by zarfide** [comment]
Thank you, fix validated against cloudca.
