### ISSUE TITLE
Unable to create a root CA which is non-VeriSign

### ISSUE THREAD

**Issue by paulsimon99** [Netflix/lemur#363]
In the plugin Window, I only saw the verisign plugin, any way to replace it with my own private self signed root CA?

Thanks for comments

**Comment by kevgliss** [comment]
Hey @paulsimon99 Lemur itself does not create root certificates, it acts a broker between CAs and user's who need certificate. There is however a PR (https://github.com/Netflix/lemur/pull/359) that attempts to add this functionality but I have not had a chance to review it. 

Generally we like to separate the certificate authority (verisign, internal CA) from deployment and tracking (Lemur). This helps keep our services smaller and more flexible.
