### ISSUE TITLE
adding rotation toggle+filtering to frontend

### ISSUE THREAD

**Issue by havron** [Netflix/lemur#3633]
👋 In my fork, I recently added the ability to toggle and filter a Certificate's rotation field directly on the certificates list (table) view - I wanted to ask here if it would be of value to raise a PR for it? Since it does add another column to the frontend, I didn't want to clutter the certificates view if there isn't enough general interest in this. For me, it's very useful to be able to quickly see+filter which certs aren't using autorotate and which are without going into the edit view for each cert!

Here's the code: https://github.com/havron/lemur/commit/3390c898ec35de2b9baff502284e3e1f69ca0f7a

It builds on @charhate's certificate table update API in https://github.com/Netflix/lemur/pull/3176 🙂

**Comment by hosseinsh** [comment]
Hi @havron, this seems a nice addition to the Lemur UI. From experience, I notice the overhead of multiple clicks to see if a certificate has auto-rotate enabled, and this is one of the common operations. 
I will seek the opinion of the other members, and report back on the general interest.

**Comment by hosseinsh** [comment]
@havron looks like there is popular demand for this feature. looking forward to a PR, whenever you get around to it.

**Comment by havron** [comment]
Yay, happy to hear that! Just opened a PR: https://github.com/Netflix/lemur/pull/3646.

**Comment by havron** [comment]
Closing now that it's merged
