### ISSUE TITLE
Creating New Authority with specified private key

### ISSUE THREAD

**Issue by Jonesy22** [Netflix/lemur#3655]
Trying to find a way to specify the private key when creating an authority. This would be kept secure using the roles within Lemur, but for pre-exsiting private keys, I want to create an input field in the "Create Authority" input modal to copy paste the existing key. I modifed lemur/lemur/static/app/angular/authorities/authority/tracking.tpl.html to include a Private Key div, and I also included it in the schema here: lemur/lemur/authorities/schemas.py. I'm having 2 issues.

1) Actually getting the input field to show up in the UI when creating a new authority

2) How to add this to the options of an authority, so when the lemur_cryptography plugin has the create_authority function called, it will create the authority with the pasted in private key if there is one

Appreciate any help or tips.

**Comment by Jonesy22** [comment]
<Deleted>

**Comment by hosseinsh** [comment]
Hi @Jonesy22, this PR https://github.com/Netflix/lemur/pull/3611 might give you an idea how to add new options for Authority creation.

We added `eab_kid` and other fields, some of which are also encrypted via Lemur's secret key.
you won't need any specific UI changes, since all defined options will be rendered in UI.

**Comment by Jonesy22** [comment]
Thanks. I misunderstood where the fields were being created from. Now when I fill in the private key field within the UI for Create Authority, and then create it, and then go back into the Create Authority, the key remains there. However for security purposes I don't want to be able to see it after I create the authority, which includes not being able to see it in the GET request. Is there a flag somewhere so it doesn't remain in the textarea after the CA is created?

**Comment by Jonesy22** [comment]
In regards to clearing the contents of the GUI field, after creating an authority, this is done in .../lemur/authorities/service.py in create().
