### ISSUE TITLE
Support certificate revocation

### ISSUE THREAD

**Issue by cfieber** [Netflix/lemur#369]
We are using Lemur managed CAs for https client authentication and would like:

1) the ability to take a `revoke` action on a certificate. This would issue the appropriate revoke to the backing CA
2) the ability to export a CRL from the backing CA

In our use case we will periodically poll the CRL file and refresh it to the host that is doing SSL handshaking (possibly during our bake phase) as opposed to hitting it in real time during handshaking so we don't necessarily require that it is a programmatic API or that it is highly available or anything... something similar to the way the certs are currently accessible would work well for us.

**Comment by kevgliss** [comment]
Adding a few more requirements:

-Revocation should only be allowed only by certificate owners
-Revocation should require additional confirmation warnings
-Lemur should track the the reason,date and user revoking the certificate
-Issuer plugins should self declare if they support revocation (some authorities might not support API based revocation)
-If revocation is supported by the plugin it should be a per authority option (some users might feel that this is too sensitive for a certificate owner to handle)

CRLs will be presented in the issued certificate, typically these are hosted from by the CA itself. Would you expect Lemur to fetch them for you, or would going straight to the URL presented in a given certificate work?

**Comment by cfieber** [comment]
I would ideally want Lemur to expose a link to the CA's CRL file as part of the more details view of an Authority
The issued certs will be sent off to the client and I don't necessarily want to have to inspect a client cert in order to pull out the URL out of it

**Comment by kevgliss** [comment]
Got it that should be easy enough to pull out and present in the response.

-Add new certificate field with the CRL contained within.

**Comment by gugahoi** [comment]
Any timeline for this functionality? Still in the plans?

**Comment by kevgliss** [comment]
We are not moving forward with this internally. Instead, we are pushing the certificate expiration down to as low as possible. How are you currently using Lemur? Are you using it's built in CA or a third-party?

**Comment by kevgliss** [comment]
Create a new API endpoint `/revoke` that would allow an end user to revoke a given certificate.

All of the basics of ownership would apply to the revocation action. Lemur will utilize the backend CA to actually issue a revocation request. This will likely be an API only feature initially.

**Comment by kevgliss** [comment]
This has been added for the Digicert CA plugins.
