### ISSUE TITLE
SSH CA support

### ISSUE THREAD

**Issue by fuero** [Netflix/lemur#370]
(Open)SSH supports using a CA to verify servers and clients (not X509 though):

http://www.openssh.com/txt/release-5.4

Having support for this would make a great addition along the way for Lemur.

Details on how to use this:
https://www.digitalocean.com/community/tutorials/how-to-create-an-ssh-ca-to-validate-hosts-and-clients-with-ubuntu

**Comment by kevgliss** [comment]
@fuero Have you taken a look at https://github.com/Netflix/bless? It's the way we prefer to manage our SSH certificates.

**Comment by fuero** [comment]
I wasn't aware of that. Sadly, this approach isn't suitable for our needs, we're not using AWS and aren't planning to.
Currently we're deploying our certs with puppet and generate keys and certs manually which is rather annoying.

**Comment by kevgliss** [comment]
Interesting, I think you might be able to extend Lemur to accomplish this but we don't currently have a use-case. If you're open to contributing, these docs should help get you started: http://lemur.readthedocs.io/en/latest/developer/index.html. I'd imagine you would want to start with the pending openssl issuer ( #359 ) plugin and go from there.
