### ISSUE TITLE
Using Private Key for signing, but restricting viewing of Private Key in UI

### ISSUE THREAD

**Issue by Jonesy22** [Netflix/lemur#3718]
This was slightly discussed in #2697 but didn't seem to get resolved. In my script I want to pass in the authority name so we can use that Authority's private key to sign something, but we don't want the user doing this to be able to see the key in plaintext for security reasons. Roles can be used to restrict or allow users to see keys, but if the user can't see the key, they can't use an API GET call to get the key. So ultimately looking for a way to use the key without seeing the key.

**Comment by Jonesy22** [comment]
Operator role seems to still allow viewing of private key. If a user has operator role for a certain authority, I'd like that user to be able to sign certificates with that authority, without being able to view the key.

**Comment by hosseinsh** [comment]
@Jonesy22 which Authority plugin you had in mind?

I definitely support allowing an authority to be used without exposing it's private key. As matter of fact, this is how we use Lemur, but out setup consists of public CAs (no private key access) and our internalCA, where Lemur also doesn't render the  private key in the UI.

**Comment by Jonesy22** [comment]
Cryptography plugin. Basically our flow is to create an authority to hold a private key, but we don't want to be able to view the private key the UI or use an API call to get it. Just to have the authority hold the key so it can be used to sign a certificate. (When you create a certificate, it shows a list of CA's that are available to use). So we want to be able to specify AuthorityX, and UserA must have at least operator permissions to see this AuthorityX option in the certificate creation, but we don't want UserA to be able to see the private key of AuthorityX in the certificates menu.

**Comment by hosseinsh** [comment]
This seems reasonable, where the admin role would have full access, but the operator role can only request issuance, without seeing the private key of the authority.

Unfortunately, we don't use the Cryptography plugin internally, so not facing the same permission issue. Happy to review an PRs that add this support, and will keep it in mind, in case we can improve on the flow somehow.

**Comment by Jonesy22** [comment]
Exactly. And thank you for your assistance, I think #2697 actually does resolve this in a workaround manner, which I didn't notice before. The flow would be to create a role, in this case, access_sensitive, and then require that role in the get function in ..certificates/views.py (In my case it wouldn't be for pending, but actually for certificates), and therefore users who need to use the Authority can since they will be granted operator role for that authority, but they will not be able to GET the private key as they don't have the access_sensitive role. Then you can assign the root user access_sensitive if it's necessary, but so far this does what we want, hopefully no bugs.
