### ISSUE TITLE
Support rotating certificate for a CloudFront distribution

### ISSUE THREAD

**Issue by bobmshannon** [Netflix/lemur#3789]
Currently, Lemur can upload certificates to IAM under the `/cloudfront` path. However, the current AWS plugin does not support discovering CloudFront distributions as endpoints and rotating their certificates. While alternative offerings like ACM could perhaps be used in such cases, it might be good to support rotating certificates on CloudFront distributions as well using Lemur.

**Comment by hosseinsh** [comment]
To be supported with https://github.com/Netflix/lemur/pull/3807

**Comment by bobmshannon** [comment]
I'll have a look - thanks!

**Comment by bobmshannon** [comment]
I tested @douglasc-nflx's PR which adds support for this and everything is looking good so far:

```
dog@lemur-6df69b55d4-swtm8:/$ /opt/venv/bin/lemur certificate rotate -o <<SNIPPED>> -e <<SNIPPED>> -c
[!] Running in COMMIT mode.
[+] Starting endpoint rotation.
[+] Rotating endpoint: <<SNIPPED>> to certificate <<SNIPPED>>
[2021-11-19 22:35:27,028] INFO in cli: {'function': 'lemur.certificates.cli.rotate', 'message': 'Rotating one endpoint', 'endpoint': 'd30k87r70yuslg.cloudfront.net', 'certificate': '<<SNIPPED>>'}
{'function': 'lemur.certificates.cli.rotate', 'message': 'Rotating one endpoint', 'endpoint': '<<SNIPPED>>.cloudfront.net', 'certificate': '<<SNIPPED>>'}
[+] Done!
```

The only thing I had to do was to allow the following actions on the cloudfront resources to be managed:

```
cloudfront:GetDistribution
cloudfront:GetDistributionConfig
cloudfront:ListDistributions
cloudfront:UpdateDistribution
```
