### ISSUE TITLE
Notifications seem to be being ignored

### ISSUE THREAD

**Issue by jneverest** [Netflix/lemur#3853]
I'm trying to test notifications, but lemur doesn't seem to think any need to be sent.

I imported a certificate from a site to test, so I only have the public key. The dates on the cert are:
```
Valid From 2020-01-30T00:00:00+00:00 (2 years ago)
Valid To 2022-01-29T23:59:59+00:00 (in 3 months)
```
I have a 6 month notification attached to the certificate, it shows up on it's list of notifications and notifications are enabled. The plugin is set to email, and my email address is entered.

When I run the notify command (/www/lemur/bin/lemur --config=/etc/lemur.conf.py notify expirations) this is the output
```
[2021-11-10 18:48:41,447] WARNING in managers: Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
[2021-11-10 18:48:41,447] WARNING in managers: Plugin 'DigiCertCISSourcePlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertCISSourcePlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
[2021-11-10 18:48:41,447] WARNING in managers: Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
[2021-11-10 18:48:41,447] WARNING in managers: Plugin 'EntrustIssuerPlugin' may not work correctly. Required variable 'ENTRUST_API_CERT' is not set in Lemur's conf.
Plugin 'EntrustIssuerPlugin' may not work correctly. Required variable 'ENTRUST_API_CERT' is not set in Lemur's conf.
[2021-11-10 18:48:41,448] WARNING in managers: Plugin 'EntrustSourcePlugin' may not work correctly. Required variable 'ENTRUST_API_CERT' is not set in Lemur's conf.
Plugin 'EntrustSourcePlugin' may not work correctly. Required variable 'ENTRUST_API_CERT' is not set in Lemur's conf.
Starting to notify subscribers about expiring certificates!
Finished notifying subscribers about expiring certificates! Sent: 0 Failed: 0
```
As you can see, there isn't any errors sending the notifications itself, it simply doesn't think there are any to send. What am I missing with notifications?

**Comment by jtschladen** [comment]
Hello,

Notifications are only sent on the _exact_ date that the notification period corresponds to. Therefore, that certificate wouldn't meet the criteria for a 6 month notification; you'd instead need to create one matching the exact number of days remaining on that specific certificate.

This is in part because notifications are not stateful, and are only meant to be sent once per day, at which time all notifications are sent for certs that _currently_ (on that date) match their configured expiration notification periods.

**Comment by jneverest** [comment]
> This is in part because notifications are not stateful, and are only meant to be sent once per day, at which time all notifications are sent for certs that _currently_ (on that date) match their configured expiration notification periods.

This explains it - changed the notification to 80 days exactly and at least now im getting connection refused errors which is at least something i can troubleshoot.

Thank you!
