### ISSUE TITLE
Lemur failing to build due to Bower's `angular-file-saver` dependency

### ISSUE THREAD

**Issue by terraflubb** [Netflix/lemur#4026]
Late last week we noticed that Lemur stopped building due to a freshly-broken dependency:

```
bower file-saver.js#~1.20150507.2     ECMDERR Failed to execute "git ls-remote --tags --heads
https://github.com/Teleborder/FileSaver.js.git", exit code of #128
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ 
for more information. fatal: Authentication failed for 'https://github.com/Teleborder/FileSaver.js.git/'
```

The problem is that https://github.com/Teleborder/FileSaver.js.git/ no longer exists. The `angular-file-saver` dependency is pulling in `Teleborder/FileSaver.js`, and `Teleborder` is no longer accessible.

Here is where Lemur is pulling the parent of the bad dependency: https://github.com/Netflix/lemur/blob/master/bower.json#L40

An issue about this over at `angular-file-saver` has been created ( https://github.com/alferov/angular-file-saver/issues/48 ) and there's even a PR that claims to correct it  ( https://github.com/alferov/angular-file-saver/pull/49 ) but that repo's master branch hasn't seen any activity since early 2017, so I don't know what kind of timeline we can expect.

I also found a fresh StackOverflow report of this error (not Lemur-related) with a suggested workaround which I haven't tested yet, which might help others who are stuck: https://stackoverflow.com/questions/71979265/unable-to-resolve-file-saver-js-dependency-file-from-bower-install-angular-file

**Comment by scopey** [comment]
I tried the link from StackOverflow and it did allow the install to continue.

**Comment by charhate** [comment]
Thanks @terraflubb and @scopey. Your input helped to speed up the fix, used the same StackOverflow suggestion.

**Comment by terraflubb** [comment]
No problem! Thank you for sorting this out, it's nice to stop using a fork. :grin:
