### ISSUE TITLE
Error when trying to pass name of role rather than ID

### ISSUE THREAD

**Issue by prdonahue** [Netflix/lemur#412]
Expectation is that I would be able to do something like this:

```
{
    "active": true,
    "username":"newuser"
    "password":"newpass"
    "email": "foo@bar.com",
    "roles": [ "admin", "RANDOM_CA_owner" ]
}
```

But seeing the following error:
```
AttributeError: 'unicode' object has no attribute 'items'
```

**Comment by kevgliss** [comment]
I will take a look at this. Currently roles are expected to be objects and only support ID lookups.

e.g.
  
    "roles": [{"name": "admin", "id": 123}]

I could see how this could be annoying depending on your use case. 

I will try to at least support:

    "roles": [{"name": "admin"}]

Which would save the client a lookup. I will update the documentation regardless.

**Comment by prdonahue** [comment]
That would be great, thanks!

One other thing that the docs could use (are they public? if so happy to send a PR) would be an example of passing a role in:

```
POST /users HTTP/1.1
Host: example.com
Accept: application/json, text/javascript

{
   "username": "user3",
   "email": "user3@example.com",
   "active": true,
   "roles": []
}
```

**Comment by prdonahue** [comment]
Err, is the docs/ folder what gets sent to lemur.readthedocs.io?

**Comment by kevgliss** [comment]
Yep everything under /docs eventually makes its way to lemur.readthedocs.io.
