### ISSUE TITLE
Is it possible to connect to ZeroSSL?

### ISSUE THREAD

**Issue by sxiii** [Netflix/lemur#4175]
ZeroSSL supports ACME, however, it provides only the endpoint URL (`https://acme.zerossl.com/v2/DV90`), EAB KID and EAB HMAC Key. However, Lemur requires the following as well:
* Acme_private_key
* Acme_regr
* Certificate

It's unclear where to get the private key from ZeroSSL as well is what is acme_regr, also, unclear, why there is field "certificate" when you add the authority (isn't that the point that authority will create the cert and use ACME to communicate with Lemur and provide the cert)?

Also, it's unclear if I need to use ACME or ACME HTTP-01 options.

I've tried going though documentation (both ZeroSSL and Lemur's) and googling but it didn't helped. Also I feel like we should have support via ZeroSSL API ideally, although someone would have to write a plugin for this, I suppose.

So the question is if the ZeroSSL is supported, and if yes, what should I enter in the empty fields for that to work.

Thank you!

**Comment by hosseinsh** [comment]
Hi @sxiii,

I don't believe Lemur has a dedicated ZeroSSL plugin, however, if ZerosSSL supports ACME you are in luck:
https://lemur.readthedocs.io/en/latest/production/index.html?highlight=EAB#external-account-binding-eab

in Lemur UI, initiate "create Authority", set Type to Root, and under More Options select the ACME plugin. 

ACME plugin uses DNS for validation; requires access to your DNS providers such that Lemur can update the DNS record required for domain validation. 
ACME-http01 plugin uses http01 for validation. (it requires a Lemur destination to upload the token, also you need to redirect `http://<YOUR_DOMAIN>/.well-known/acme-challenge` to this destination which holds the token for validation)


https://letsencrypt.org/docs/challenge-types/#http-01-challenge
