### ISSUE TITLE
A custom cert name with spaces causes AWS Upload failures

### ISSUE THREAD

**Issue by mikegrima** [Netflix/lemur#432]
Creating a cert with a custom name that has spaces, such as: `My Certificate` will not properly get uploaded to AWS.

-- Potential Fixes:

1. Prevent spaces in custom names
2. Allow custom cert names to be editable
3. If spaces are allowed, the AWS uploader plugin needs to upload it in a way that can work properly.

**Comment by kevgliss** [comment]
I don't like having AWS delegate core Lemur functionality. That being said I don't particularly like having whitespace in custom names either. How do we feel about replacing any whitespace found in a certificate's custom name with a `-`? This would align it better with the generated names as well.

**Comment by mikegrima** [comment]
+1 to remove whitespace.
