### ISSUE TITLE
ping / oauth2 failing without errors

### ISSUE THREAD

**Issue by JohnTheodore** [Netflix/lemur#443]
I turned on ACTIVE_PROVIDERS = 'ping', I now get the new button 'Login with Lemur' in black.

Though if I click it, I get an ephemeral popup that immediately disappears.

In the network tab I can see two xhr requests to '/api/1/auth/me', with a 401 response that says:  "message": "Missing authorization header" (note I get these responses _after_ I click the new login button)

The backend doesn't return any errors, though I do have debug mode on. 

Oddly I seem to get these /api/1/auth/me 401 errors at the login screen, even if I turn off any active providers. Then once I login, the 401s go away. So perhaps the login screen is doing some header check that doesn't need to be done at all for that page. There are 4 of the 401s from auth/me, 2  when I load the login screen, and another 2 when I try to click to new login button for oauth2

**Comment by kevgliss** [comment]
There are quite a few additional config items to set when using `ping` as a provider. Where these set?

**Comment by JohnTheodore** [comment]
Yes, I have the other config variables set I believe:

ACTIVE_PROVIDERS = ['ping']
PING_SECRET = 'xxxx'
PING_ACCESS_TOKEN_URL = 'https://xxxx'
PING_USER_API_URL = 'https://xxxx'
PING_JWKS_URL = 'https://xxx/oauth2/jwks'
PING_NAME = 'lemur'
PING_CLIENT_ID = 'lemur'

If ACTIVE_PROVIDERS isn't an array, it doesn't render the new login button.

**Comment by kevgliss** [comment]
`PING_NAME` is what eventually gets displayed with on the button `Login with X`. Do you ever receive any requests with token back from ping? 

Depending on your Ping setup, after the pop-up is closed I would expect a call-back on the endpoint `/auth/ping`. If you're not seeing that I would double check your settings above. As that would imply that something is a miss with the URLs.

**Comment by JohnTheodore** [comment]
So I don't see any request to /auth/ping. There is a popup which immediately disappears. I was worried inspector tool network log might not show a request from the popup. So I went to chrome://net-internals/#events in chrome, which shows me _all_ network requests, regardless of which tab. and I only have lemur open.

I see two requests to /auth/me, and one to here: https://lemur.example.com/?response_type=code&client_id=lemur&scope=openid%20email%20profile%20address

^I think this last one is in the popup? It's hard to debug, since inspector tool can't be used on ephemeral popups.

It doesn't seem like lemur is attempting to connect to my ping endpoints.

Are there lines/traces I can set pdb traces on? I set a trace in class Providers(Resource) under the instance method 'get'. I can see elif provider == "ping" (which does get executed).

I can see this: 
current_app.config.get("PING_NAME")
current_app.config.get('PING_REDIRECT_URI')
current_app.config.get("PING_REDIRECT_URI")
current_app.config.get("PING_CLIENT_ID")
current_app.config.get("PING_AUTH_ENDPOINT")


For PING_NAME and PING_CLIENT_ID, those work fine.

For PING_REDIRECT_URI and PING_AUTH_ENDPOINT .. these do _not_ work. These last two variables aren't in the docs anywhere I can tell. I am following these docs: https://lemur.readthedocs.io/en/latest/administration.html#authentication-options are these the right ones?

Once/if I get this working, I can make a PR to add these to the docs.

**Comment by kevgliss** [comment]
Yes, you will need `PING_AUTH_ENDPOINT` and `PING_REDIRECT_URI` set and we should get those added to the docs... 

The request to:
https://lemur.example.com/?response_type=code&client_id=lemur&scope=openid%20email%20profile%20address

Should actually be going to:
https://lemur.example.com/api/1/ping?response_type=code&client_id=lemur&scope=openid%20email%20profile%20address

Try setting `PING_REDIRECT_URI` to:
`PING_REDIRECT_URI = 'https://lemur.example.com/api/1/auth/ping'

**Comment by kevgliss** [comment]
Were you able to fix your issues?

**Comment by JohnTheodore** [comment]
So I can cut certs through the verisign API.

Oauth2 had a few issues. My co-worker is sending in PRs for them. the base64 encoding, google groups is hard coded, and another issue with urllib. We patched them all on our instance, so things oauth2 works now. I think the PRs will land soon. I'll close this ticket.
