### ISSUE TITLE
Route53 DNS-01 Across AWS Accounts

### ISSUE THREAD

**Issue by ccben87** [Netflix/lemur#4928]
Hi, is it possible to configure Lemur to create Route53 DNS records in an AWS account different from the account where the Lemur EC2 instance is running from? If so, could you please advise how this is possible? There does not seem to be anything to configure apart from account ID.

**Comment by ccben87** [comment]
My mistake, this does work. I just had my policy wrong.

For anyone else that might need it, you can even do an AssumeRoleWithWebIdentity if you specify an environment variable for AWS_WEB_IDENTITY_TOKEN_FILE.

**Comment by cidrbl0ck** [comment]
Hey @ccben87 It's beed a minute but can I ask you, how did you configure the DNS provider in Lemur? Where are the credentials used?

**Comment by ccben87** [comment]
@cidrbl0ck Sorry for the late reply on this, somehow didn't see this notification! To answer your question, it gets configured like this:

<img width="900" height="460" alt="Image" src="https://github.com/user-attachments/assets/a6715b45-66aa-4f91-aeb5-b321d4d48c7f" />

The credentials used by default - if deployed in AWS - is the EC2 instance profile assigned to your EC2 instance. You would give that EC2 instance profile the requisite rights to Route53 in the account number you configure as a Route53 DNS Provider. You can also do cross-account IAM permissions if you need to but for this I would refer you to the AWS documentation on the matter. So to answer your question, you don't need to normally configure credentials for Route53.

Alternatively, you can configure AWS environment variables to authenticate: https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-envvars.html

For example, you can configure AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION environment variables and then those will be used by Lemur automatically. This is the simplest way of doing it. If you're not using AWS to host your Lemur instance then you can create some AWS IAM credentials and then define them as environment variables.
