### ISSUE TITLE
ADMINS constant is ignored

### ISSUE THREAD

**Issue by JohnTheodore** [Netflix/lemur#494]
Perhaps I'm making a mistake, but the ADMINS constant in lemur.conf.py doesn't seem to be hooked up to anything.

**Comment by kevgliss** [comment]
I think you are correct and it is left over from an earlier version of Lemur. How were you expecting to use this variable?

**Comment by JohnTheodore** [comment]
I thought I could just put usernames in the array, and then when someone logs in as that user, they're an admin.

**Comment by kevgliss** [comment]
Is that easier for you then simply adding the `admin` role to those users?

**Comment by JohnTheodore** [comment]
after turning on oauth2, I'm no longer an admin to do that. :p

I'll just write to the database directly and poke around the users table.

**Comment by kevgliss** [comment]
Yes, you can always use the cli to add a role to a user.

**Comment by JohnTheodore** [comment]
o that sounds easier. What would the CLI command be to add a role to a user?

**Comment by kevgliss** [comment]
I may have spoken too quickly. It appears that there is the ability to create a new user with roles from CLI but not edit an existing user. 

https://github.com/Netflix/lemur/blob/master/lemur/manage.py#L267
