### ISSUE TITLE
CSR Key size not match the CA

### ISSUE THREAD

**Issue by RcRonco** [Netflix/lemur#527]
When creating a CA there is an option to choose a 4096 or 2048 bits key.
In the Create Certificate the CSR is created with 2048bit and not by the CA.

the code is in [lemur/certificates/service.py line 319](https://github.com/Netflix/lemur/blob/master/lemur/certificates/service.py#L321).

**Comment by kevgliss** [comment]
Ah, you are correct. Thanks for pointing this out.

**Comment by kevgliss** [comment]
Looking at this more is the expectation that the `Create Certificate` option should have the option to specify the key size? If so, I think thats reasonable.

**Comment by RcRonco** [comment]
Add the option to choose key size would be better.

I work on plugin for Hashicorp Vault, there is restriction when setting role to 4096bit and send 2048bit and other wise.
