### ISSUE TITLE
lemur create_config fails on validate_conf 

### ISSUE THREAD

**Issue by genadipost** [Netflix/lemur#557]
When running ```lemur create_config``` i get the following error:
```
(lemur) genadi@ubuntu:~/PycharmProjects/lemur$ lemur create_config
Traceback (most recent call last):
  File "/home/genadi/PycharmProjects/lemur/bin/lemur", line 11, in <module>
    load_entry_point('lemur', 'console_scripts', 'lemur')()
  File "/home/genadi/PycharmProjects/lemur/lemur/manage.py", line 839, in main
    manager.run()
  File "/home/genadi/PycharmProjects/lemur/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/genadi/PycharmProjects/lemur/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/genadi/PycharmProjects/lemur/local/lib/python2.7/site-packages/flask_script/__init__.py", line 156, in __call__
    app = app(**kwargs)
  File "/home/genadi/PycharmProjects/lemur/lemur/__init__.py", line 59, in create_app
    app = factory.create_app(app_name=__name__, blueprints=LEMUR_BLUEPRINTS, config=config)
  File "/home/genadi/PycharmProjects/lemur/lemur/factory.py", line 61, in create_app
    configure_app(app, config)
  File "/home/genadi/PycharmProjects/lemur/lemur/factory.py", line 118, in configure_app
    validate_conf(app, REQUIRED_VARIABLES)
  File "/home/genadi/PycharmProjects/lemur/lemur/common/utils.py", line 99, in validate_conf
    raise InvalidConfiguration("Required variable '{var}' is not set in Lemur's conf.".format(var=var))
lemur.exceptions.InvalidConfiguration: Required variable 'LEMUR_SECURITY_TEAM_EMAIL' is not set in Lemur's conf.
```
[```validate_conf```](https://github.com/Netflix/lemur/blob/master/lemur/factory.py#L118) runs (in ```configure_app```) before [```create_config```](https://github.com/Netflix/lemur/blob/a40bc65fd4010cd72928edb983e0d315f2b3680c/lemur/manage.py#L411) and attempts to validate options that are not defined yet (as the configuration file does not exists):
```
REQUIRED_VARIABLES = [
    'LEMUR_SECURITY_TEAM_EMAIL',
    'LEMUR_DEFAULT_ORGANIZATIONAL_UNIT',
    'LEMUR_DEFAULT_ORGANIZATION',
    'LEMUR_DEFAULT_LOCATION',
    'LEMUR_DEFAULT_COUNTRY',
    'LEMUR_DEFAULT_STATE',
    'SQLALCHEMY_DATABASE_URI'
]
```
But when looking farther at [```create_config```](https://github.com/Netflix/lemur/blob/a40bc65fd4010cd72928edb983e0d315f2b3680c/lemur/manage.py#L423) and [```generate_settings```](https://github.com/Netflix/lemur/blob/a40bc65fd4010cd72928edb983e0d315f2b3680c/lemur/manage.py#L176):
```
def generate_settings():
    """
    This command is run when ``default_path`` doesn't exist, or ``init`` is
    run and returns a string representing the default data to put into their
    settings file.
    """
    output = CONFIG_TEMPLATE.format(
        # we use Fernet.generate_key to make sure that the key length is
        # compatible with Fernet
        encryption_key=Fernet.generate_key(),
        secret_token=base64.b64encode(os.urandom(KEY_LENGTH)),
        flask_secret_key=base64.b64encode(os.urandom(KEY_LENGTH)),
)
```
The variables in ```REQUIRED_VARIABLES``` are not created in the default configuration file.

I would propose two changes:
-  Remove [```validate_conf```](https://github.com/Netflix/lemur/blob/master/lemur/factory.py#L118) from ```configure_app```or handle the case if configuration file does not exists.
- Add [```REQUIRED_VARIABLES```](https://github.com/Netflix/lemur/blob/b46ff4158ada9f7a90bde173c47e45a7370aef23/lemur/factory.py#L32) options into[```generate_settings```](https://github.com/Netflix/lemur/blob/a40bc65fd4010cd72928edb983e0d315f2b3680c/lemur/manage.py#L176).

**Comment by kevgliss** [comment]
Ah, thats a good catch. I think it would be best to handle the case where the configuration does not exist, this would allow us to keep the same behavior as before `REQURED_VARIABLES` was introduced. Also, I don't believe there are good defaults that could be added to the template except something like `REQUIRED_VAR='CHANGEME'`
