### ISSUE TITLE
Error while parsing certificate

### ISSUE THREAD

**Issue by RcRonco** [Netflix/lemur#558]
Hi I notice that most of the time the ```body``` parameter in ```parse_certificate``` is ```unicode``` and not ```str```, which cause an error. 

i just added to the line 47:

```python
if isinstance(body, str) or type(body) is unicode:
        body = body.encode('utf-8')
```

Im not sure if this is the best solution, because the first part of the condition is not necessary because ```x509.load_pem_x509_certificate``` can get a ```str``` but not ```unicode```.

https://github.com/Netflix/lemur/blob/master/lemur/common/utils.py#L47

**Comment by kevgliss** [comment]
Are you using python 3? That latest versions (>0.4) of Lemur only use python3.
