### ISSUE TITLE
allow lemur init to use alternate config

### ISSUE THREAD

**Issue by jeremyguarini** [Netflix/lemur#588]
When installing we can define an alternate path for the `lemur create_config` with the -c arg. Can we get `lemur init` to accept an alternate path? Or is it always expected to have configuration items (config, keys, etc) under ~/.lemur/ ?

thanks

**Comment by kevgliss** [comment]
That seems reasonable.

**Comment by jeremyguarini** [comment]
thanks

**Comment by kevgliss** [comment]
Looking into this it seems we already support this. For any given command you should be able to pass '-c' with point to the configuration for which you want use.

In your case something like:
  
    lemur -c <path-to_config> init

Should use the configuration as passed.

Can you try that out and let me know how it goes?

**Comment by jeremyguarini** [comment]
So having already performed init, it appears to work. Though when I run `lemur -c /path/to/config start` it tries to use the ~/.lemur/ path.

Starting from scratch in a temp dir and fresh database all seems well until I try to start. Renaming the config found in ~/.lemur and trying to start I get the following

> : mv ~/.lemur/lemur.conf.py ~/.lemur/lemur.conf.py.bak
(lemur) jguarini-ld1:/tmp/lemur: lemur -c /tmp/lemur/config/lemur.conf.py start -b 0.0.0.0:8001
/tmp/lemur/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
/tmp/lemur/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Traceback (most recent call last):
  File "/tmp/lemur/bin/lemur", line 11, in <module>
    load_entry_point('lemur', 'console_scripts', 'lemur')()
  File "/tmp/lemur/lemur/manage.py", line 636, in main
    manager.run()
  File "/tmp/lemur/lib/python3.5/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/tmp/lemur/lib/python3.5/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/tmp/lemur/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/tmp/lemur/lemur/manage.py", line 377, in run
    validate_conf(pre_app, REQUIRED_VARIABLES)
  File "/tmp/lemur/lemur/common/utils.py", line 99, in validate_conf
    raise InvalidConfiguration("Required variable '{var}' is not set in Lemur's conf.".format(var=var))
lemur.exceptions.InvalidConfiguration: Required variable 'LEMUR_SECURITY_TEAM_EMAIL' is not set in Lemur's conf.


thanks for looking into this

**Comment by kevgliss** [comment]
Ugh, That is an ugly amount of output for a simple command. Let me see if I can clean that up.

**Comment by kevgliss** [comment]
Okay, so I think I solved this. Not super happy with the way it had to be done but I think it's the best we can hope for.

Checkout #596 and see if it fits your needs.

**Comment by jeremyguarini** [comment]
Briefly looking over the gunicorn doc for make_config() it appears to take an ignore arg. Could you simply supply ignore=['config'] on line 356 `settings = make_settings()` so that it looks like `settings = make_settings(ignore=["config"])`  and do away with the whole if `klass.name == ` part in the while loop? Now I haven't tested this so it may not work as I expect it to. But it seems that if the ignore list holds a value then the in make_settins() if `if setting.name in ignore:` it's just skipped anyways.

See https://github.com/benoitc/gunicorn/blob/master/gunicorn/config.py for reference

Thoughts?

**Comment by kevgliss** [comment]
You might be looking at older code.

https://github.com/Netflix/lemur/blob/master/lemur/manage.py#L361

The newest code does away with `klass.name` and focuses on `klass.action` this addresses an issue where argparse had problems parsing the 'store_constant' variables as passed from gunicorn's make_settings.

**Comment by jeremyguarini** [comment]
Was looking at current code, was just thinking that using the ignore that comes with make_settings() would of achieved the same effect.

I'll give the update a go in the morning. 

thanks

**Comment by jeremyguarini** [comment]
So I've added the lines to manager.py and still no love.

> (lemur) [lemur@jguarini-ld1 lemur]$ head -n365 lemur/manage.py  | tail -12

    def get_options(self):
        settings = make_settings()
        options = []
        for setting, klass in settings.items():
            if klass.cli:
                if klass.name == 'config':
                    continue
                if klass.action:
                    if klass.action == 'store_const':
                        options.append(Option(*klass.cli, const=klass.const, action=klass.action))
                    else:


> (lemur) [lemur@jguarini-ld1 lemur]$ lemur -c /tmp/lemur/config/lemur.conf.py start -b 0.0.0.0:8001
/tmp/lemur/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
/tmp/lemur/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Traceback (most recent call last):
  File "/tmp/lemur/bin/lemur", line 11, in <module>
    load_entry_point('lemur', 'console_scripts', 'lemur')()
  File "/tmp/lemur/lemur/manage.py", line 638, in main
    manager.run()
  File "/tmp/lemur/lib/python3.5/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/tmp/lemur/lib/python3.5/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/tmp/lemur/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/tmp/lemur/lemur/manage.py", line 379, in run
    validate_conf(pre_app, REQUIRED_VARIABLES)
  File "/tmp/lemur/lemur/common/utils.py", line 99, in validate_conf
    raise InvalidConfiguration("Required variable '{var}' is not set in Lemur's conf.".format(var=var))
lemur.exceptions.InvalidConfiguration: Required variable 'LEMUR_SECURITY_TEAM_EMAIL' is not set in Lemur's conf.

verify missing arg is there
> (lemur) [lemur@jguarini-ld1 lemur]$ grep LEMUR_SECURITY_TEAM_EMAIL config/lemur.conf.py
LEMUR_SECURITY_TEAM_EMAIL = ['my.email@test.com']

**Comment by kevgliss** [comment]
Did you pull down the #596 ? There were a few changes that would need to be applied.

**Comment by jeremyguarini** [comment]
so looking at the commits for #596 I see two, first seems to add in the `if klass.name == 'config':` condition while the second one removed it. I did a git pull off of master this morning still have the same issue.

Should I just be pulling in commit e746133450326aed68b73291320f4fad92ba31d5 ?

thanks

**Comment by kevgliss** [comment]
Yes, they aren't squashed sorry.

**Comment by jeremyguarini** [comment]
After getting correct commit this works.
Thank you for your help on this.
