### ISSUE TITLE
Documentation: Please update quickstart guide to include minimum postgres version

### ISSUE THREAD

**Issue by jeremyguarini** [Netflix/lemur#589]
Hi,

Following the quickstart guide it mentions that I need to have postgres installed but does not specify a version. I found that anything older than 9.2 (without backport) `lemur init` fails due to unsupported JSON type. After updating postgres to 9.2 I was able to proceed on to the next issue.

thanks

**Comment by kevgliss** [comment]
We are actually running postgres 9.4 in production, so that would be the recommended version. It *may* work on older versions but this should point people in the right direction.
