### ISSUE TITLE
lemur init fails on db create

### ISSUE THREAD

**Issue by jeremyguarini** [Netflix/lemur#590]
Hi,

Following the quick start guide I'm in the /www/lemur/ dir and running `lemur init`. I get the following error

> : lemur init
/www/lemur/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Traceback (most recent call last):
  File "/www/lemur/bin/lemur", line 11, in <module>
    load_entry_point('lemur', 'console_scripts', 'lemur')()
  File "/www/lemur/lemur/manage.py", line 636, in main
    manager.run()
  File "/www/lemur/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/www/lemur/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/www/lemur/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/www/lemur/lemur/manage.py", line 192, in run
    create()
  File "/www/lemur/lemur/manage.py", line 143, in create
    stamp(revision='head')
  File "/www/lemur/lib/python2.7/site-packages/flask_migrate/__init__.py", line 363, in stamp
    command.stamp(config, revision, sql=sql, tag=tag)
  File "/www/lemur/lib/python2.7/site-packages/alembic/command.py", line 336, in stamp
    script = ScriptDirectory.from_config(config)
  File "/www/lemur/lib/python2.7/site-packages/alembic/script/base.py", line 129, in from_config
    version_locations=version_locations
  File "/www/lemur/lib/python2.7/site-packages/alembic/script/base.py", line 57, in __init__
    "scripts folder." % dir)
alembic.util.exc.CommandError: Path doesn't exist: 'migrations'.  Please use the 'init' command to create a new scripts folder.

after cd'ing into lemur the command works

> :/www/lemur: cd lemur
>:/www/lemur/lemur: lemur init
/www/lemur/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running stamp_revision  -> 131ec6accff5
[+] Created 'admin' role
[+] Created 'operator' role
[+] Created 'read-only' role
We need to set Lemur's password to continue!
Password:

Please let me know if you need any more information.

--
Jeremy

**Comment by harmw** [comment]
That's actually how it is documented:
http://lemur.readthedocs.io/en/latest/quickstart/index.html#initializing-lemur

**Comment by jeremyguarini** [comment]
you are correct sir! I totally missed tat step. Thanks
