### ISSUE TITLE
possibly don't show certs that have been replaced

### ISSUE THREAD

**Issue by jeremyguarini** [Netflix/lemur#593]
Looking at the certs page I see all the I've created and replaced with newer certs. Could we get a filter/view that only shows 'active' certs? What I'm trying to avoid is showing certs 1, 2, 3 where cert 1 was replaced by 2 and 2 replaced by 3. Cert 3 would be the current cert since the other two have been replaced.

Maybe I'm missing something, but how does a user know which cert to download if a given cert has been replaced by a newer one (other than comparing CN)?

Also in the API response for /certificates/<id> could there be a 'replaced by' field to indicate there is a newer version of the cert?

thanks

**Comment by kevgliss** [comment]
Seems like there are two enhancements here, breaking them up into separate issues #594 and #595.

Let me know if I missed any details, the 'replaced by' field is a simple change, we already store and use this field we just don't expose it via the API. The filtering is more complicated and will likely take a bit longer to complete. 

If you're willing/able some help with the filtering aspect would be greatly appreciated.

**Comment by jeremyguarini** [comment]
Thanks. Will comment in each of the new tickets.
