### ISSUE TITLE
Add 'replacedBy' field in certificate response.

### ISSUE THREAD

**Issue by kevgliss** [Netflix/lemur#594]
In addition to the 'replaces' field, we should also have a field of 'replacedBy' so we can easily determine if a certificate has been replaced and should no longer be used.

**Comment by jeremyguarini** [comment]
yes, having a field that links/points to the most recent version of the cert would be very helpful. Say if cert 2 is replaced by cert 4 with is then renewed/reissued by cert 55. The replaced by  field in cert 2 should either point to cert 55 or show that it was replaced by cert 4 then 55. ie. Replaced By: 4 -> 55

This would help to show the history of the cert along with what the current version is. I see that in the API output cert 55 contains the certs it replaces which is handy.

**Comment by kevgliss** [comment]
Field has been named `replaced`.
