### ISSUE TITLE
How to delete users

### ISSUE THREAD

**Issue by jeremyguarini** [Netflix/lemur#608]
while setting up lemur and testing out a few things I created some test users. How do I go about deleting them? I'm logged in with a user that has admin role but I don't see anything in the UI that will allow me to delete a user. I see that I can mark them as inactive but nothing to remove them.

thanks.

**Comment by kevgliss** [comment]
Deletion of users is not currently supported (who becomes a 'creator' of a certificate if they are deleted). You can however mark them as in-active and it will not allow them to login.

**Comment by jeremyguarini** [comment]
Possibly having certs owned by a DL might be a good choice. What happens when a user leaves the company? How is that cert managed/maintained? I tried to mark a test user as in-active and was still able to log in with it, will double check with a fresh install (maybe I have something messed up).

**Comment by kevgliss** [comment]
Certificates are 'owned' by team DLs but creator is still tied to an individual as are actions like view private keys. When a user leaves the 'owner' is still the team DL. 

If you can login with an in-active user that would be a bug that we should get fixed up.

**Comment by jeremyguarini** [comment]
I see, in the create cert is where I'll put a DL instead of the individual person. If we can't easily delete users, could we show/hide inactive users on the users page? Thanks for clearing that up. As for the inactive login, I'll open a new bug.

**Comment by kevgliss** [comment]
Sure created #613 to track.
