### ISSUE TITLE
inactive user can still log in

### ISSUE THREAD

**Issue by jeremyguarini** [Netflix/lemur#612]
Hi,

I'm able to log in with a user that is marked 'inactive'. Here are the steps that I did to reproduce this:
* git clone
* create new database
* update lemur_config to point to new database
* lemur init
* lemur start
* login as the lemur user
* create new user 'test' with dummy email and did not assign any roles
* login with 'test' user
* logout
* login as lemur
* set 'test' user to inactive
* logout 
* login as test
Here I would expect a flash message saying something along the lines of the account isn't found or is not currently allowed to log in, instead I'm logged in.

Please let me know if you need any additional information.

**Comment by kevgliss** [comment]
Closed by #618
