### ISSUE TITLE
Support more KeyUsage and ExtendedKeyUsage options

### ISSUE THREAD

**Issue by neilschelly** [Netflix/lemur#646]
The UI includes checkboxes to set all these options, but they mostly get ignored now. Many of the x509 extensions are pseudo-coded in a comment beginning here: https://github.com/Netflix/lemur/blob/master/lemur/certificates/service.py#L365

* ~~Some options will be mutually exclusive, like KeyUsage encipherOnly and decipherOnly.~~ separated to #663 
* ~~Some options will imply others, like encipherOnly and decipherOnly requiring keyAgreement.~~ separated to #663
* keyCertSign will imply the BasicConstraint for CA:TRUE. 
* ~~Some extensions requested in the CSR state can only be granted or completed in the signing phase within the CA plugin, like inserting CRL and/or OCSP service URIs.~~ Out of scope. Plugins/providers will ignore what they want to and add what they need to when signing CSRs.
* ~~Since Authorities are essentially a Certificate with specific extensions and usages, some of these options may also need to be applied to the Authority object and data structures.~~ Implemented in #658 

EDIT: I'm reducing the scope of this. I want this ticket to be about encoding the checkboxes/values from the authority/certificate creation pages into the resulting CSR (that gets submitted to the authority for signing). This is primarily all the KeyUsage and ExtendedKeyUsage stuff.

Out of scope:
* Custom OIDs: These are troublesome because they are inherently not supported by the underlying python-cryptography library. It's probably not too much effort to support them in a non-critical state, but the library explicitly _can't_ support custom OIDs with the critical flag, because that would violate the RFC. Issue #665 can work on this.
* CRL Distribution Points: The UI currently offers 3 options (Yes/No/Default), but those values get dropped. It's hard to be clear on what _should_ be here, but the end goal is to include the description/URLs/etc that would be included in the certificate. At the very least, it's unlikely the CSR creation will know these values and the authority plugin/provider would be necessary to do handle this. Issue #662 was created to better deal with this.

**Comment by kevgliss** [comment]
This sounds good, all those checkbox options should already be passed to `issuer_options` into any given plugin.  You're right that a lot of those options are for the CA might not even be respected if inserted into the CSR. Looking forward to it.
