### ISSUE TITLE
Flake8 Error When Executing Git Commit

### ISSUE THREAD

**Issue by chadhendrie** [Netflix/lemur#649]
I'm seeing the following error when I execute a "git commit":

Traceback (most recent call last):
  File ".git/hooks/pre-commit", line 45, in <module>
    sys.exit(main())
  File ".git/hooks/pre-commit", line 32, in main
    from flake8.hooks import run
ImportError: No module named 'flake8.hooks'

I was seeing this in my current Lemur project that I've been developing in. I thought it might be something with my environment, but I did a fresh clone, followed the Quickstart instructions and then tried to commit a change with the above results.

Is anyone else seeing this error? 

Thanks!

**Comment by neilschelly** [comment]
I am also seeing this error, and was unable to trace it down a bit ago. I ended up deleting the pre-commit file locally just to unblock myself so I can stay on a current train of thought. As awful as that sounds, I intended to revisit and see what I'm missing.

For reference, my system is a Debian Jessie box. git version 2.1.4. I have python 2.7 and python 3.4 from Debian packages, with 2.7 being the default. The latest version of flake8 is installed in both system python version environments with pip.

**Comment by chadhendrie** [comment]
Thanks for the info. I did a little digging also and didn't get very far. In the short term, I'll follow your advice and remove the pre-commit.

**Comment by chadhendrie** [comment]
For reference, I'm using MBP with El Capitan. I installed python 2.7.11 and 3.5.1 and git 2.8.2 with homebrew. I am using 3.5.1 to develop with lemur.

**Comment by kevgliss** [comment]
I believe that `hooks` directory can be removed entirely. Awhile back I switch Lemur over to using Yelp's [`pre-commit`](http://pre-commit.com/) that can optionally be installed by users. Running `pre-commit install` will install hooks as defined by `https://github.com/Netflix/lemur/blob/master/.pre-commit-config.yaml`
