### ISSUE TITLE
Custom OIDs not encoded into CSR

### ISSUE THREAD

**Issue by neilschelly** [Netflix/lemur#665]
These are troublesome because they are inherently not supported by the underlying python-cryptography library. It's probably not too much effort to support them in a non-critical state, but the library explicitly can't support custom OIDs with the critical flag, because that would violate the RFC for x509. An x509 implementation (python cryptography here) has to raise an error upon handling a critical extension it doesn't natively recognize/support. So, the x509.UnrecognizedExtension type inherently cannot support critical extensions.

In the create_csr() function, a custom extension will look like:
```{'oid': u'1.3.6.1.5.5.7.3.25', 'value': u'blah', 'is_critical': True, 'encoding': u'string'}```
The value should be DER encoded (unsure about how just now) and added to the CSR in create_csr like:
```
builder = builder.add_extension(
    x509.UnrecognizedExtension(
        oid=custom['oid'],
        value=custom['value']
    )
)
```

**Comment by kevgliss** [comment]
It seems to me that we should respect the RFC here. If custom OIDs should not be allowed to be critical we shouldn't support setting it as such.
