### ISSUE TITLE
Improvements to the lemur_cryptography authority and certificate plugin

### ISSUE THREAD

**Issue by neilschelly** [Netflix/lemur#667]
I have in mind a relatively substantial refactor of the lemur_cryptography plugin.
* Renaming functions to support creating both root CAs or intermediate CAs.
* Structure creating a CA around the create_csr() function in the certificates workflow to avoid copying all that code.
* Implement some of the CA-specific functions when issuing a certificate: authority_key_identifier, certificate_info_access, crl_distribution_points. Those last two will probably end up being placeholders here as they don't really apply to a sorta-fake CA managed by this plugin.
* Set the Issuer details in the signed certificates.

**Comment by neilschelly** [comment]
The implementation above is contingent on my PR for #666 getting accepted first. Changes there may necessitate changes here.

**Comment by neilschelly** [comment]
#666 is merged, but necessitated some changes that make this merge a bit more complicated. This will need to be rebased.

**Comment by kevgliss** [comment]
I have found a few issues with #666 I am currently addressing that should be merged before we attempt to merge this in.

**Comment by neilschelly** [comment]
@kevgliss let me know if I can help resolve those issues. I've been watching the commit messages.

**Comment by kevgliss** [comment]
All the integration tests have now passed for the certificate flow fix a few minor things but nothing serious... I still need to validate the authority flow. Sorry I haven't been very disciplined with my commits so they might be hard to follow.
