### ISSUE TITLE
Consider not running 'create' on startup

### ISSUE THREAD

**Issue by tlianza** [Netflix/lemur#677]
We're happy to commit a PR for this, just want to get a sense for if there's any disagreement:

When lemur starts up it calls create() which runs sqlalchemy's create_all and stamps the migration version: 
https://github.com/Netflix/lemur/blob/master/lemur/manage.py#L185

However, if you're upgrading and accidentally start lemur before running migrations, when this service starts up it's going to:

1. Create some tables in your DB based on what it sees in your models
2. Update the alembic version to make your database think it's at the latest version

That leaves you in a pretty rough state... even if you hand-updated alembic to the "real" version, the migrations aren't going to run successfully, because some of the tables they would have created have already been created via create_all. But, some of the fields the migrations would have altered never got altered.

I think this behavior of calling create() should really be the exception not the rule... like, maybe it's part of someone's first time with lemur, but shouldn't be part of the normal operation of lemur. Is that idea controversial? Any good reasons for it that I'm missing?

**Comment by kevgliss** [comment]
The command `lemur init` should be a one time setup for new users and shouldn't be run at any other time. Not sure what you mean by starts up but I would normally associate that with the`lemur start` actually starts the service, which should have no effect on the tables.

**Comment by tlianza** [comment]
Gotcha... that was our issue I think... we were running lemur init as a mater of course instead of just once. Thanks!
