### ISSUE TITLE
gulp build errors result in missing style sheets

### ISSUE THREAD

**Issue by exitnode** [Netflix/lemur#691]
Hi,

during the build process of gulp, i get the following error:

> (lemur) lemur@lemur:/www/lemur$ node_modules/.bin/gulp build
> [14:16:41] Using gulpfile /www/lemur/gulpfile.js
> (node:4483) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
> [14:16:41] Starting 'build:ngviews'...
> [14:16:41] Starting 'dev:styles'...
> [14:16:42] Starting 'dev:scripts'...
> [14:16:42] Starting 'build:images'...
> [14:16:42] Starting 'dev:fonts'...
> [14:16:42] Starting 'build:extras'...
> [14:16:42] Finished 'build:images' after 36 ms
> [14:16:42] Finished 'build:extras' after 678 ms
> [14:16:45] Plumber found unhandled error:
>  Error in plugin 'gulp-minify-css'
> Message:
>     Broken @import declaration of "https://fonts.googleapis.com/css?family=Roboto:400,500,700" - error 404
> Details:
>     fileName: /www/lemur/lemur/static/app/styles/styles.css
> [14:16:45] Finished 'dev:styles' after 3.33 s
> [14:16:45] Finished 'dev:fonts' after 3.55 s
> [...]
> [14:16:46] Finished 'build:html' after 549 ms
> [14:16:46] Starting 'build'...
> [14:16:46] Finished 'build' after 133 μs

The web interface without the styles.css looks exactly like in bug #425. I have the same effect on Ubuntu 14.04 as well as on 16.04 following the quickstart quide.
Any suggestions?

**Comment by kevgliss** [comment]
Judging by: http://stackoverflow.com/questions/32049394/remote-font-imports-with-css-minification 

It looks like adding `{processImport: false}` might fix the problem... Could you verify that this fixes your issue?

**Comment by exitnode** [comment]
Thank you very much, this solved my problem :)

**Comment by JohnTheodore** [comment]
Which file does {processImport: false} get added to?

**Comment by kevgliss** [comment]
@JohnTheodore I think it's this line. https://github.com/Netflix/lemur/blob/master/gulp/build.js#L108

**Comment by JohnTheodore** [comment]
This worked, thanks!
