### ISSUE TITLE
Why do we need DIGICERT_INTERMEDIATE and DIGICERT_ROOT for DigiCert plugin?

### ISSUE THREAD

**Issue by clement-splk** [Netflix/lemur#699]
The earlier DigiCert plugin from OpenDNS does not have these two required configs and I was able to get it working with DigiCert API.

Not sure how I should set these two entries in lemur.conf.py as this is not needed for DigiCert API call.

Should we make this optional?

**Comment by kevgliss** [comment]
OpenDNS embedded the certificates directly within the plugin (https://github.com/opendns/lemur-digicert/blob/master/lemur_digicert/constants.py), when we pulled it into Lemur core, we made these configurable options as multiple roots could be issued via the Digicert plugin. 

The standard root and intermediates should be available in CertCentral or https://www.digicert.com/digicert-root-certificates.htm

See: http://lemur.readthedocs.io/en/latest/administration.html#digicert-issuer-plugin for how to configure those options. 

Essentially you can just drop the pem in as a string setting, up the root and intermediate you'd like to use.

**Comment by clement-splk** [comment]
Thanks. This helps a lot.
