### ISSUE TITLE
WebUI can not worked well

### ISSUE THREAD

**Issue by lcgkm** [Netflix/lemur#720]
I can't login and click any tab like DASHBOARD, CERTIFICATES, etc...

Code version:

> commit a4068001a3a21d3539bcd0575e50b48d65661e81
> Author: kevgliss <kevgliss@gmail.com>
> Date:   Sun Mar 12 15:01:21 2017 -0700
> 
>     Updating docs to align with normal deployment. (#718)

PS. But the REST API is OK.
```
$ curl -H "Content-Type: application/json" -X POST -d '{"username":"lemur","password":"lemur"}' http://127.0.0.1:8000/api/1/auth/login 
{"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImV4cCI6MTQ4OTQ3NDkxNSwiaWF0IjoxNDg5Mzg4NTE1fQ.dFoRZgKHkqzjRcumiXuskzr_tzrBfqD_ba0vai7rnJ0"}
$
```

**Comment by kevgliss** [comment]
Can you post some logs from the console?

**Comment by kevgliss** [comment]
Please take a look and see if #722 fixes your issue.

**Comment by lcgkm** [comment]
#722 fixes my issue. Thx
