### ISSUE TITLE
Create Authority Failed

### ISSUE THREAD

**Issue by lcgkm** [Netflix/lemur#726]
Version:

> commit 522e1826946e8e5b0f661a5ffb637838827f7cec
> Author: Rick Breidenstein <RickB17@users.noreply.github.com>
> Date:   Mon Mar 13 18:45:10 2017 -0400
> 
>     added python3-dev to dependencies (#724)
>     
>     make release fails without it

Log:
> [2017-03-14 05:42:09,927] ERROR in schema: 'NoneType' object cannot be interpreted as an integer
> Traceback (most recent call last):
>   File "/www/lemur/lemur/common/schema.py", line 158, in decorated_function
>     resp = f(*args, **kwargs)
>   File "/www/lemur/lemur/authorities/views.py", line 223, in post
>     return service.create(**data)
>   File "/www/lemur/lemur/authorities/service.py", line 110, in create
>     cert = upload(**kwargs)
>   File "/www/lemur/lemur/certificates/service.py", line 220, in upload
>     cert = Certificate(**kwargs)
>   File "<string>", line 4, in __init__
>   File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
>     manager.dispatch.init_failure(self, args, kwargs)
>   File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
>     compat.reraise(exc_type, exc_value, exc_tb)
>   File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
>     raise value
>   File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance
>     return manager.original_init(*mixed[1:], **kwargs)
>   File "/www/lemur/lemur/certificates/models.py", line 123, in __init__
>     cert = lemur.common.utils.parse_certificate(kwargs['body'])
>   File "/www/lemur/lemur/common/utils.py", line 53, in parse_certificate
>     return x509.load_pem_x509_certificate(body, default_backend())
>   File "/www/lemur/lib/python3.5/site-packages/cryptography/x509/base.py", line 43, in load_pem_x509_certificate
>     return backend.load_pem_x509_certificate(data)
>   File "/www/lemur/lib/python3.5/site-packages/cryptography/hazmat/backends/multibackend.py", line 341, in load_pem_x509_certificate
>     return b.load_pem_x509_certificate(data)
>   File "/www/lemur/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1169, in load_pem_x509_certificate
>     mem_bio = self._bytes_to_bio(data)
>   File "/www/lemur/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 490, in _bytes_to_bio
>     data_char_p = self._ffi.new("char[]", data)
> TypeError: 'NoneType' object cannot be interpreted as an integer
> 'NoneType' object cannot be interpreted as an integer
> Traceback (most recent call last):
>   File "/www/lemur/lemur/common/schema.py", line 158, in decorated_function
>     resp = f(*args, **kwargs)
>   File "/www/lemur/lemur/authorities/views.py", line 223, in post
>     return service.create(**data)
>   File "/www/lemur/lemur/authorities/service.py", line 110, in create
>     cert = upload(**kwargs)
>   File "/www/lemur/lemur/certificates/service.py", line 220, in upload
>     cert = Certificate(**kwargs)
>   File "<string>", line 4, in __init__
>   File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
>     manager.dispatch.init_failure(self, args, kwargs)
>   File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
>     compat.reraise(exc_type, exc_value, exc_tb)
>   File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
>     raise value
>   File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance
>     return manager.original_init(*mixed[1:], **kwargs)
>   File "/www/lemur/lemur/certificates/models.py", line 123, in __init__
>     cert = lemur.common.utils.parse_certificate(kwargs['body'])
>   File "/www/lemur/lemur/common/utils.py", line 53, in parse_certificate
>     return x509.load_pem_x509_certificate(body, default_backend())
>   File "/www/lemur/lib/python3.5/site-packages/cryptography/x509/base.py", line 43, in load_pem_x509_certificate
>     return backend.load_pem_x509_certificate(data)
>   File "/www/lemur/lib/python3.5/site-packages/cryptography/hazmat/backends/multibackend.py", line 341, in load_pem_x509_certificate
>     return b.load_pem_x509_certificate(data)
>   File "/www/lemur/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1169, in load_pem_x509_certificate
>     mem_bio = self._bytes_to_bio(data)
>   File "/www/lemur/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 490, in _bytes_to_bio
>     data_char_p = self._ffi.new("char[]", data)
> TypeError: 'NoneType' object cannot be interpreted as an integer

**Comment by kevgliss** [comment]
Lemur is python3 only.

**Comment by kevgliss** [comment]
Which authority plugin are you using?

**Comment by lcgkm** [comment]
Plugin: CFSSL

**Comment by kevgliss** [comment]
Do you have `CFSSL_ROOT` set in your config?

**Comment by kevgliss** [comment]
Judging from your other issues this seems like it was resolved, is that the case?
