### ISSUE TITLE
Unable to create PR for 0.4.0 tag

### ISSUE THREAD

**Issue by treacher** [Netflix/lemur#741]
Hello :)

I'm looking to create a PR against version 0.4.0 it seems there is no 0.4.x branch for me to create a pull request against. I'm just wondering would this be the normal approach for creating this type of PR, this is a patch for fixing an issue with the Digicert plugin.

Currently it always sets the `custom_expiration_date` even if you only define `validity_years`. This is a problem as some setups in digicert will reject creation requests if they have a `custom_expiration_date` set. These setups only allow `validity_years` to be passed through.

The change I'm looking to make is on the following branch: https://github.com/Netflix/lemur/compare/0.4.0...treacher:custom_expiration_date-fix

Please advise :)

**Comment by kevgliss** [comment]
Does the problem still exist in master? I would do a PR against HEAD, once that looks okay and is merged I will create a 0.4 branch and cherry pick your PR to backport it.

**Comment by treacher** [comment]
Thanks for the fast response, yes it does, here is the PR: https://github.com/Netflix/lemur/pull/742

**Comment by kevgliss** [comment]
I created the following branch with your PR applied. Please let me know if you into any issues.

https://github.com/Netflix/lemur/tree/0.4.1

**Comment by treacher** [comment]
Is it possible to also cherry-pick the following commit into 0.4.x as well as it causes issues when spinning up a stack: https://github.com/Netflix/lemur/commit/d68b2b22e067066b010885b615d6e06ebab3933c due to a dependency issue.

**Comment by kevgliss** [comment]
Done.

**Comment by treacher** [comment]
It seems cherrypicking that commit so far back has caused quite a few issues a couple to name:
- Factory Boy needs upgrading `ImportError('The ``fake-factory`` package is now called ``Faker``.\n\nPlease update your requirements.\n',)`
- There is a Flakey time dependent test that seems to be failing: `AssertionError: assert not {'_schema': ['Validity end must not be after 2020-01-01 20:59:06']}` 
- It's now referencing methods that don't exist: `ImportError: cannot import name validate_conf`

I suspect those wont be the only or last ones, I wonder what you think we should do in this case? Is there a release coming soon where I could just roll forward with this rather than spending time on fixing something in a branch that's already fixed in the future? Or should I do a PR to fix these things on this branch?

**Comment by kevgliss** [comment]
Master is currently pretty stable (it's what we've been running for a month or so), I just haven't gotten around to cutting a release. Let me try to find some time this weekend and I will get a release tagged.

**Comment by kevgliss** [comment]
Please use the newest release: https://github.com/Netflix/lemur/releases/tag/0.5.0
