### ISSUE TITLE
[featurerequest] LDAP support for users

### ISSUE THREAD

**Issue by arthurlogilab** [Netflix/lemur#791]
It would be useful to have an LDAP connector to handle users.

**Comment by douardda** [comment]
Or any way to delegate auth to the reverse proxy in front of the flask app, in fact.

**Comment by kevgliss** [comment]
This looks like it would be pretty easy to add.

- Add a new LDAP login provider [Examples](https://github.com/Netflix/lemur/blob/master/lemur/auth/views.py#L30)
- Add required configuration parameters
- Add additional dependency on `python-ldap`

I'd be happy to merge something like this.
