### ISSUE TITLE
adding Digicert CA errors on opening cert

### ISSUE THREAD

**Issue by awesomazing** [Netflix/lemur#794]
I am trying to add an authority for Digicert when I click create I receive the following error. I have the configuration pointed to a copy of the DigicertrootCA that is in PEM format and is readable with openssl. Not sure how to proceed. Let me know if more information is needed.

Unable to load certificate
Traceback (most recent call last):
  File "/www/lemur/lemur/common/schema.py", line 158, in decorated_function
    resp = f(*args, **kwargs)
  File "/www/lemur/lemur/authorities/views.py", line 223, in post
    return service.create(**data)
  File "/www/lemur/lemur/authorities/service.py", line 108, in create
    cert = upload(**kwargs)
  File "/www/lemur/lemur/certificates/service.py", line 220, in upload
    cert = Certificate(**kwargs)
  File "<string>", line 4, in __init__
  File "/www/lemur/lib/python3.4/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/www/lemur/lib/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/www/lemur/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/www/lemur/lib/python3.4/site-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/www/lemur/lemur/certificates/models.py", line 125, in __init__
    cert = lemur.common.utils.parse_certificate(kwargs['body'])
  File "/www/lemur/lemur/common/utils.py", line 53, in parse_certificate
    return x509.load_pem_x509_certificate(body, default_backend())
  File "/www/lemur/lib/python3.4/site-packages/cryptography/x509/base.py", line 43, in load_pem_x509_certificate
    return backend.load_pem_x509_certificate(data)
  File "/www/lemur/lib/python3.4/site-packages/cryptography/hazmat/backends/multibackend.py", line 341, in load_pem_x509_certificate
    return b.load_pem_x509_certificate(data)
  File "/www/lemur/lib/python3.4/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1175, in load_pem_x509_certificate
    raise ValueError("Unable to load certificate")
ValueError: Unable to load certificate

**Comment by kevgliss** [comment]
The configuration option expects a string. Not a file path. Ensure that you have either copied your PEM into the configuration directly. You can also attempt to load your file via `open('<path-to-pem>', 'r').read()`.

**Comment by awesomazing** [comment]
Are you saying that I need to copy the section between ----BEGIN----- and ----END---- and include it in a string in the configuration file. I have done that as well and it still fails to load. I am not sure what you trying to explain.

**Comment by kevgliss** [comment]
Sorry yes, normally that error is either a malformed certificate or the user is attempting to pass a file path instead of the whole PEM string. Are you using the CIS plugin or the CertCentral DigiCert issuer type? For CertCentral ensure you are setting `DIGICERT_ROOT` in your configuration. It looks like we are currently lacking documentation for the CIS issuer. 

http://lemur.readthedocs.io/en/latest/administration.html#digicert-issuer-plugin

**Comment by awesomazing** [comment]
This is the configuration settings that I have in the conf file the DOC/GIT differs so I included everything that was on the creators git page. This still fails during the initial CA creation complaining that it cannot load the certificate.

```DIGICERT_URL = 'https://api.digicert.com/'
DIGICERT_ACCOUNT_ID = 'XXXXXX'
DIGICERT_API_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXX'
DIGICERT_REQUEST_TYPE = 'SSL_PLUS'
DIGICERT_ORG_ID = 'XXXXXX'
DIGICERT_ROOT = 'MIIGsDCCBZigAwIBAgIQAWXPzBkXS2mHJkFZyuDHnjANBgkqhkiG9w0BAQUFADBhMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBDQTAeFw0wNjExMTAwMDAwMDBaFw0yMTExMTAwMDAwMDBaMF4xCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xHTAbBgNVBAMTFERpZ2lDZXJ0IEdsb2JhbCBDQS0xMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8iUcMWe3U+uoT6X95s8wUq8QNQIMbMT/9DyiihlzABTaK2rBaDBL/xs21MjdJm4skBZxaj6PZ7CSlqyL3iiXo/uwpSzizKeLy7kYUardBn+bj/ZsjL4EDHebWVB7UA4FXCWclX45hwkPQ04OULdvJ27EmQ30M0APd87mSlSefYw808HAS7S7IU76egrvne2EF4oopd44LovUYo4vZa/shcpsqQvAXkHrprm6eTFYCVMc+d2hhFMx2xnmEZ4HdLEHjhyeRY13nEpY84mNP2Jg+mOi5s7gOu/lP5VJf5th/XbfwH1Q19hbU+MP7lYVh3wkYjtpxAJNeLYZHu7g6YPkGQIDAQABo4IDZTCCA2EwDgYDVR0PAQH/BAQDAgGGMDsGA1UdJQQ0MDIGCCsGAQUFBwMBBggrBgEFBQcDAgYIKwYBBQUHAwMGCCsGAQUFBwMEBggrBgEFBQcDCDCCAcYGA1UdIASCAb0wggG5MIIBtQYLYIZIAYb9bAEDAAMwggGkMDoGCCsGAQUFBwIBFi5odHRwOi8vd3d3LmRpZ2ljZXJ0LmNvbS9zc2wtY3BzLXJlcG9zaXRvcnkuaHRtMIIBZAYIKwYBBQUHAgIwggFWHoIBUgBBAG4AeQAgAHUAcwBlACAAbwBmACAAdABoAGkAcwAgAEMAZQByAHQAaQBmAGkAYwBhAHQAZQAgAGMAbwBuAHMAdABpAHQAdQB0AGUAcwAgAGEAYwBjAGUAcAB0AGEAbgBjAGUAIABvAGYAIAB0AGgAZQAgAEQAaQBnAGkAQwBlAHIAdAAgAEMAUAAvAEMAUABTACAAYQBuAGQAIAB0AGgAZQAgAFIAZQBsAHkAaQBuAGcAIABQAGEAcgB0AHkAIABBAGcAcgBlAGUAbQBlAG4AdAAgAHcAaABpAGMAaAAgAGwAaQBtAGkAdAAgAGwAaQBhAGIAaQBsAGkAdAB5ACAAYQBuAGQAIABhAHIAZQAgAGkAbgBjAG8AcgBwAG8AcgBhAHQAZQBkACAAaABlAHIAZQBpAG4AIABiAHkAIAByAGUAZgBlAHIAZQBuAGMAZQAuMA8GA1UdEwEB/wQFMAMBAf8wegYIKwYBBQUHAQEEbjBsMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wRAYIKwYBBQUHMAKGOGh0dHA6Ly93d3cuZGlnaWNlcnQuY29tL0NBQ2VydHMvRGlnaUNlcnRHbG9iYWxSb290Q0EuY3J0MHsGA1UdHwR0MHIwN6A1oDOGMWh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbFJvb3RDQS5jcmwwN6A1oDOGMWh0dHA6Ly9jcmw0LmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbFJvb3RDQS5jcmwwHQYDVR0OBBYEFB4ciBWq8kbQBdrpHtwivaiX3g+yMB8GA1UdIwQYMBaAFAPeUDVW0Uy7ZvCj4hsbw5eyPdFVMA0GCSqGSIb3DQEBBQUAA4IBAQBk1w8VqkRIKlsRXm3WQ1/gbIyvFNedW/5PD+uilCEGg3O9fwV40ZBuMwzI7Hf63Qg1TBJr/RIFZuXFDmQwTs65A36ewdtDp2D+fjpTb83ll+fUBZSxO181Csc7A0T63c61g/lPur+yZ2xXN9c9qxhRxmoUUD6VDDUSdTVClWN2pvb2OSt4HiFgETeic3LASnhvlkQSYmw49+rT33QRGy5Vo8e7jnwsWKQ8ei8swxkDzu+8VmuBr0oAqxBTQ04X/K54YC5nALAGN7ca/IXZVixfbeWwfUbC2iYqCkV7s0syyocZCitvxTqpotAMITETFJW2+jzn4GJhbm23uzxUtZaI'
DIGICERT_DEFAULT_VALIDITY = '1'```

**Comment by kevgliss** [comment]
Ah, Okay. Yes, you will need to include the header files for the `DIGICERT_ROOT` option.

It would look like:

```
DIGICERT_ROOT = """-----BEGIN CERTIFICATE-----
MIIEGjCCAwICEQCbfgZJoz5iudXukEhxKe9XMA0GCSqGSIb3DQEBBQUAMIHKMQsw
...
TxzhT5yvDwyd93gN2PQ1VoDat20Xj50egWTh/sVFuq1ruQp6Tk9LhO5L8X3dEQ==
-----END CERTIFICATE-----
"""

**Comment by awesomazing** [comment]
Thank you for the clarification it is loading the cert now.
