### ISSUE TITLE
0.5.0 lemur init, looking for migration file that is in the latest code

### ISSUE THREAD

**Issue by henry-megarry-tr** [Netflix/lemur#806]
I am running the init command to create the missing tables that lemur upgrade needs to run. But its failing on this
`alembic.util.exc.CommandError: Can't locate revision identified by '8ae67285ff14'
`
which can be found here
https://github.com/Netflix/lemur/tree/master/lemur/migrations/versions

but not here
https://github.com/Netflix/lemur/tree/0.5.0/lemur/migrations/versions

should it be requiring the latest scripts from the released tag?

**Comment by kevgliss** [comment]
Are you upgrading to 0.5 or to master? That tag was created before the migration so it would be odd that is looking for it.

**Comment by henry-megarry-tr** [comment]
I guess this was happening to me. Tried running the upgrade from master before on accident, even though it failed(because the domain table wasn't created) it must have still edited that table.
https://stackoverflow.com/questions/32311366/alembic-util-command-error-cant-find-identifier
