### ISSUE TITLE
Add plugin for Hashicorp Vault

### ISSUE THREAD

**Issue by RcRonco** [Netflix/lemur#848]
Hi, 
I wrote a plugin for Hashicorp Vault, I use it in my organization.
I would like to add it to the main Lemur project.
If any changes needed or any code fixing please tell me.

https://github.com/RcRonco/lemur_vault

**Comment by kevgliss** [comment]
Hi @RcRonco would you like your plugin to be mentioned in our docs? i.e. http://lemur.readthedocs.io/en/latest/administration.html#rd-party-plugins or would you like to have it pulled into the core project?

If it's the former please open a PR with the correct modification of the docs. If it's the latter please open a PR with your plugin included in lemur's `plugin` directory.

**Comment by RcRonco** [comment]
Ok I will add a PR.
should it be submodule or just put the code?

**Comment by kevgliss** [comment]
If you'd like it to be part of lemur core it should not be a git submodule.

**Comment by RcRonco** [comment]
Ok I will do pull request
