### ISSUE TITLE
npm issues with installation 

### ISSUE THREAD

**Issue by Ortimus** [Netflix/lemur#864]
I am trying to install following instructions from: http://lemur.readthedocs.io/en/latest/quickstart/index.html#installing-build-dependencies  and stuck on 'make release'

I am a node dummy, so can someone tell me how to go past this error ....

I am on ubuntu 14.04 (Canonical, Ubuntu, 14.04 LTS, amd64 trusty image build on 2017-07-27)

Error:
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-125-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /www/lemur
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm http 304 https://registry.npmjs.org/jasminewd2/0.0.10
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-125-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /www/lemur
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm http 304 https://registry.npmjs.org/selenium-webdriver/2.53.3
npm ERR! 404 'types' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.13.0-125-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /www/lemur
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /www/lemur/npm-debug.log
npm ERR! not ok code 0
make: *** [release] Error 1

**Comment by kevgliss** [comment]
You're using quite an old version of node `0.10.25`. When we build Lemur we use `6.2.0`. If that ends up solving your problem we should make the minimum node version `6.2.0` and make a note in the docs.

**Comment by Ortimus** [comment]
Thanks. That solved my problem.

I had followed the quick start installation instructions and run:
sudo apt-get install nodejs-legacy python-pip python-dev python3-dev libpq-dev build-essential libssl-dev libffi-dev nginx git supervisor npm postgresql
which installs **nodejs-legacy**
giving
node --version
v0.10.25
Uninstalling and installing the latest node version solved the issue.
