### ISSUE TITLE
Need help on deploying certificates to AWS ELB and S3

### ISSUE THREAD

**Issue by selatamil** [Netflix/lemur#894]
How to push the certs to endpoints/destination(AWS ELB and S3) from Lemur? Is there any commands available? Kindly let me know the clear procedure to do so.

**Comment by pr8kerl** [comment]
@selatamil have you read the section in the [manual](https://lemur.readthedocs.io/en/latest/administration.html#aws-source-destination-plugin)??
You basically need to ensure you set up the AWS IAM role correctly for lemur to access your aws resources. Then create/configure an AWS destination or source as you see fit. I believe lemur supports storing certificates in S3 buckets or in IAM as server certifcates. We tried the S3 option briefly as a test and all seemed fine.

**Comment by selatamil** [comment]
Hi @pr8kerl ,

Thank you for your quick reply. I configured those already and I already have source/destinations in place. I need a way or Lemur command to push the certs to S3 or IAM. Requesting you to provide the steps you followed in pushing certs to s3. 

Thanks in Advance!

**Comment by selatamil** [comment]
Hi @pr8kerl ,

To be more clear, I have created IAM role and synced the certificates/Endpoints(ELB) from configured Source AWS account. Also I have configured the destinations like AWS s3, IAM. Now I stuck with pushing uploaded certificate to the configured Destination (S3 and IAM certs). Could you please help me with the steps to push the certificate, I mean lemur commands to push the certificates to their configured destination. 

Thanks in Advance!

**Comment by kevgliss** [comment]
@selatamil you can add a `destination` to a certificate during creation or after it has been issued. This will make it available to S3 or IAM depending on your destination configuration.

**Comment by selatamil** [comment]
Hi @kevgliss 

Thank you very much for your response!

I did that already (configured IAM detination), but I don't see the certificates in IAM.  Do we need to issue any command or run any cron to periodically push the certificates. I don't see any logs related to this. 
FYI: My log level is Debug. 

Please find the IAM policy action attached to the Lemur Role for IAM cert upload. 

                "iam:ListServerCertificates",
                "iam:UpdateServerCertificate",
                "iam:GetServerCertificate",
                "iam:UploadServerCertificate"

Kindly let me know how to get this done. 

Thanks in Advance!

**Comment by kevgliss** [comment]
They should be made available immediately... nothing in the error logs is a bit weird. Have you entered your accountId in the destination correctly? `LemurInstanceProfile` will actually assume role into the `Lemur` role to upload certificates. But I would expect some errors.

**Comment by selatamil** [comment]
Hi @kevgliss & @pr8kerl ,

Thank you very much for your support!

Now i'm able to push the certificate to IAM. It was due to the certificate chain which was not in proper order. 

If you don't mind, I have come up with another query, in destination configuration I could only see AWS (IAM) and AWS s3 plugins only & I don't see AWS ELB plugin. Do we need to enable something in module portion of the code to get the AWS ELB plugin in destination configuration? Kindly let me know. 

Thanks in Advance!

Regards,
Tamilventhan S

**Comment by kevgliss** [comment]
There is no ELB plugin, internally we rely on other deployment systems to associate certificates to ELBs (https://github.com/spinnaker). 

If you're in need of such a feature, I would be willing to accept PR for a plugin for ELBs.

**Comment by selatamil** [comment]
@kevgliss , Thank you for your reply!
Will you charge for developing the ELB plugin? please let me know.

**Comment by kevgliss** [comment]
Charge? No... we have no real use for this internally. But Lemur is Open Source so feel free to submit a pull request with this functionality.

**Comment by selatamil** [comment]
@kevgliss Thank you for the clarification.  Could you please let me know the procedure to submit the PR?

**Comment by kevgliss** [comment]
The following docs outline how to write code for Lemur. http://lemur.readthedocs.io/en/latest/developer/index.html

**Comment by selatamil** [comment]
@kevgliss  Thank you for your timely support. We are clear now. 

I'm closing this for now and get back to you with PR if we really need ELB plugin. 

Thanks again!
