### ISSUE TITLE
Issue with Database Upgrade

### ISSUE THREAD

**Issue by csmithson12345** [Netflix/lemur#899]
Hello,
I'm new to GitHub and this project, so please let me know if i have left out any useful information.

I have an issue with the upgrade process for lemur. When performing the command from the virtual environment
```
(lemur) lemur@COMPUTERNAME:/www/lemur/lemur lemur -c /home/lemur/.lemur/lemur.conf.py db upgrade
```
I get the below output. Could you please offer any suggestions for a resolution?

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 7f71c0cea31a -> 932525b82f1a, Changing the column name to the more accurately named 'notify'.
INFO  [alembic.runtime.migration] Running upgrade 932525b82f1a -> e3691fc396e9, Adding logging database tables.
INFO  [alembic.runtime.migration] Running upgrade e3691fc396e9 -> 131ec6accff5, Ensuring we have endpoint updated times and certificate rotation availability.
Traceback (most recent call last):
  File "/www/lemur/bin/lemur", line 11, in <module>
    load_entry_point('lemur', 'console_scripts', 'lemur')()
  File "/www/lemur/lemur/manage.py", line 545, in main
    manager.run()
  File "/www/lemur/lib/python3.5/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/www/lemur/lib/python3.5/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/www/lemur/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/www/lemur/lib/python3.5/site-packages/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/www/lemur/lib/python3.5/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/www/lemur/lib/python3.5/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/www/lemur/lib/python3.5/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/www/lemur/lib/python3.5/site-packages/alembic/util/compat.py", line 64, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "migrations/env.py", line 72, in <module>
    run_migrations_online()
  File "migrations/env.py", line 65, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/www/lemur/lib/python3.5/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/www/lemur/lib/python3.5/site-packages/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/www/lemur/lemur/migrations/versions/131ec6accff5_.py", line 19, in upgrade
    op.add_column('certificates', sa.Column('rotation', sa.Boolean(), nullable=False, server_default=False))
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 1234, in __init__
    args.append(DefaultClause(self.server_default))
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 2413, in __init__
    TextClause), 'arg')
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 1101, in assert_arg_type
    (name, ' or '.join("'%s'" % a for a in argtype), type(arg)))
sqlalchemy.exc.ArgumentError: Argument 'arg' is expected to be one of type '<class 'str'>' or '<class 'sqlalchemy.sql.elements.ClauseElement'>' or '<class 'sqlalchemy.sql.elements.TextClause'>', got '<class 'bool'>'
```

**Comment by kevgliss** [comment]
Can you do a `pip freeze` on your environment?

**Comment by csmithson12345** [comment]
Here are the results
acme==0.17.0
alembic==0.9.5
aniso8601==1.3.0
arrow==0.10.0
asn1crypto==0.22.0
bcrypt==3.1.3
blinker==1.4
boto3==1.4.6
botocore==1.6.8
cffi==1.10.0
click==6.7
contextlib2==0.5.5
cryptography==1.9
docutils==0.14
Flask==0.12
Flask-Bcrypt==0.7.1
Flask-Mail==0.9.1
Flask-Migrate==2.1.1
Flask-Principal==0.4.0
Flask-RESTful==0.3.6
Flask-Script==2.0.5
Flask-SQLAlchemy==2.1
future==0.16.0
gunicorn==19.7.1
idna==2.6
inflection==0.3.1
itsdangerous==0.24
Jinja2==2.9.6
jmespath==0.9.3
-e git+https://github.com/Netflix/lemur@ff4d1edd63d28fa748784d6ae1f65318e01e1dda#egg=lemur
lockfile==0.12.2
Mako==1.0.7
MarkupSafe==1.0
marshmallow==2.13.6
marshmallow-sqlalchemy==0.13.1
mock==2.0.0
ndg-httpsclient==0.4.2
paramiko==2.2.1
pbr==3.1.1
pem==17.1.0
psycopg2==2.7.3
pyasn1==0.3.3
pycparser==2.18
PyJWT==1.5.2
pyldap==2.4.36
PyNaCl==1.1.2
pyOpenSSL==17.2.0
pyRFC3339==1.0
python-dateutil==2.6.1
python-editor==1.0.3
pytz==2017.2
raven==6.1.0
requests==2.11.1
retrying==1.3.3
s3transfer==0.1.11
six==1.10.0
SQLAlchemy==1.1.14
SQLAlchemy-Utils==0.32.14
tabulate==0.7.7
Werkzeug==0.12.2
xmltodict==0.11.0

**Comment by csmithson12345** [comment]
is there any other info i may be able to provide on this? we would love to get this upgrade done. 

please let me know!

**Comment by RickB17** [comment]
The upgrade process worked in our DEV environment and fails in the PRD environment. Below is the pip freeze comparison between the two environments. 

Could some of the missing packages be the difference with the db upgrade not working?

Package  | DEV | PRD
acme | 0.16.0 | 0.17.0
alembic | 0.9.3 | 0.9.5
aniso8601 | 1.2.1 | 1.3.0
arrow | 0.10.0 | 0.10.0
asn1crypto | 0.22.0 | 0.22.0
aspy.yaml | 0.3.0 | #N/A
bcrypt | 3.1.3 | 3.1.3
blinker | 1.4 | 1.4
boto | 2.48.0 | #N/A
boto3 | 1.4.4 | 1.4.6
botocore | 1.5.88 | 1.6.8
cached-property | 1.3.0 | #N/A
cffi | 1.10.0 | 1.10.0
click | 6.7 | 6.7
contextlib2 | 0.5.5 | 0.5.5
cookies | 2.2.1 | #N/A
cryptography | 1.9 | 1.9
dicttoxml | 1.7.4 | #N/A
docutils | 0.13.1 | 0.14
factory-boy | 2.8.1 | #N/A
fake-factory | 0.7.2 | #N/A
Faker | 0.7.18 | #N/A
flake8 | 3.3.0 | #N/A
Flask | 0.12 | 0.12
Flask-Bcrypt | 0.7.1 | 0.7.1
Flask-Mail | 0.9.1 | 0.9.1
Flask-Migrate | 2.0.4 | 2.1.1
Flask-Principal | 0.4.0 | 0.4.0
Flask-RESTful | 0.3.6 | 0.3.6
Flask-Script | 2.0.5 | 2.0.5
Flask-SQLAlchemy | 2.1 | 2.1
freezegun | 0.3.9 | #N/A
future | 0.16.0 | 0.16.0
gunicorn | 19.7.1 | 19.7.1
identify | 1.0.3 | #N/A
idna | 2.5 | 2.6
inflection | 0.3.1 | 0.3.1
invoke | 0.19.0 | #N/A
itsdangerous | 0.24 | 0.24
Jinja2 | 2.9.6 | 2.9.6
jmespath | 0.9.3 | 0.9.3
-e git+https://github.com/Netflix/lemur@f5082e2d3a4efd147694903fcce58e30b2217556#egg | lemur | #N/A
lockfile | 0.12.2 | 0.12.2
Mako | 1.0.7 | 1.0.7
MarkupSafe | 1 | 1
marshmallow | 2.13.5 | 2.13.6
marshmallow-sqlalchemy | 0.13.1 | 0.13.1
mccabe | 0.6.1 | #N/A
mock | 2.0.0 | 2.0.0
moto | 1.0.1 | #N/A
ndg-httpsclient | 0.4.2 | 0.4.2
nodeenv | 1.1.4 | #N/A
nose | 1.3.7 | #N/A
paramiko | 2.2.1 | 2.2.1
pbr | 3.1.1 | 3.1.1
pem | 16.1.0 | 17.1.0
pkginfo | 1.4.1 | #N/A
pre-commit | 0.15.4 | #N/A
psycopg2 | 2.7.1 | 2.7.3
py | 1.4.34 | #N/A
pyaml | 16.12.2 | #N/A
pyasn1 | 0.3.1 | 0.3.3
pycodestyle | 2.3.1 | #N/A
pycparser | 2.18 | 2.18
pyflakes | 1.5.0 | #N/A
PyJWT | 1.5.2 | 1.5.2
PyNaCl | 1.1.2 | 1.1.2
pyOpenSSL | 17.2.0 | 17.2.0
pyRFC3339 | 1 | 1
pytest | 3.1.3 | #N/A
pytest-flask | 0.10.0 | #N/A
python-dateutil | 2.6.1 | 2.6.1
python-editor | 1.0.3 | 1.0.3
pytz | 2017.2 | 2017.2
PyYAML | 3.12 | #N/A
raven | 6.1.0 | 6.1.0
requests | 2.11.1 | 2.11.1
requests-mock | 1.3.0 | #N/A
requests-toolbelt | 0.8.0 | #N/A
retrying | 1.3.3 | 1.3.3
s3transfer | 0.1.10 | 0.1.11
six | 1.10.0 | 1.10.0
SQLAlchemy | 1.1.12 | 1.1.14
SQLAlchemy-Utils | 0.32.14 | 0.32.14
tabulate | 0.7.7 | 0.7.7
tqdm | 4.15.0 | #N/A
twine | 1.9.1 | #N/A
virtualenv | 15.1.0 | #N/A
Werkzeug | 0.12.2 | 0.12.2
xmltodict | 0.11.0 | 0.11.0

**Comment by kevgliss** [comment]
This is most likely an issue with either alembic or sqlalchemy, I would downgrade both of these packages in your prod environment and try again, or try one and then the other. 

We don't pin either of these packages but we might have to.

**Comment by RickB17** [comment]
@kevgliss  I think I'm close, but not there yet. Look like alembic only accepts strings in the default, even when it's a Boolean. Is this accurate/relevant?

https://bitbucket.org/zzzeek/alembic/issues/347/default-value-doesnt-work-on-boolean

https://github.com/Netflix/lemur/blob/dafed86179f581e58a4796ad84292ffedd1352ea/lemur/migrations/versions/131ec6accff5_.py#L19

**Comment by RickB17** [comment]
After this. I needed to comment out and the db upgrade completed. 

https://github.com/Netflix/lemur/blob/dafed86179f581e58a4796ad84292ffedd1352ea/lemur/migrations/versions/5e680529b666_.py#L18
and 
https://github.com/Netflix/lemur/blob/dafed86179f581e58a4796ad84292ffedd1352ea/lemur/migrations/versions/5e680529b666_.py#L19

**Comment by kevgliss** [comment]
Thats interesting, I'm a little confused on why I didn't have that problem in our environment though.
