### ISSUE TITLE
Private Key issue in AWS source sync

### ISSUE THREAD

**Issue by selatamil** [Netflix/lemur#911]
Hi All,

While syncing AWS source account using lemur sync command, private keys are not getting synced in certificates. I hope due to security reasons, private keys are not getting synced. Is the any fix for this. 

Regards,
Tamilventhan S

**Comment by kevgliss** [comment]
AWS IAM does not allow the retrieval of private keys.

**Comment by selatamil** [comment]
thank you @kevgliss
