### ISSUE TITLE
Need help on Ldap integration

### ISSUE THREAD

**Issue by selatamil** [Netflix/lemur#929]
Hi,

I have latest git revision checked in and edited the docs/administration.rst as below for LDAP authentication

LDAP_BIND_URI = 'ldaps://ldap-dev.cloud.example.com'
LDAP_BASE_DN = 'DC=Users,DC=cloud,DC=example,DC=com'
LDAP_EMAIL_DOMAIN = 'example.com'
LDAP_REQUIRED_GROUP = 'lemur_group'
LDAP_GROUPS_TO_ROLES = {'lemur_group': 'admin', 'Lemur Team DL Group': 'team@example.com'}

I'm able to telnet ldap-dev.cloud.example.com 636 from lemur server. But still i'm not able to authenticate Lemur with LDAP. 

Is there anything else need to be modified to achieve this? Kindly suggest me

Thanks in Advance!

**Comment by pr8kerl** [comment]
So those settings need to go into your lemur.conf.py file.

There are a couple of extra settings missing.
Try it with all these...

```
LDAP_AUTH = True
LDAP_USE_TLS = True
LDAP_BIND_URI = 'ldaps://ldap-dev.cloud.example.com'
LDAP_BASE_DN = 'DC=Users,DC=cloud,DC=example,DC=com'
LDAP_EMAIL_DOMAIN = 'example.com'
LDAP_REQUIRED_GROUP = 'lemur_group'
LDAP_GROUPS_TO_ROLES = {'lemur_group': 'admin', 'Lemur Team DL Group': 'team@example.com'}
# if your LDAP server has non-standard CA you may need to point to trusted CA certificate file
LDAP_CACERT_FILE = '/opt/app/lemur/cacerts' 
```
If still issues, post any errors.
I've only tested against Windows 2016 AD LDAP. But hopefully the above will work.

**Comment by selatamil** [comment]
@pr8kerl   Thank you for your quick response. 
I'm getting  ERROR: ldap error: ldap error: {'desc': 'No such object'} [in /opt/lemur/lemur/auth/views.py:119]

We haven't installed any customized SSL on our LDAP (FreeIPA), it has it's self generated SSL cert. Do I need to download the CA and keep it in Lemur server and mention the path in lemur.conf.py

Kindly suggest. 

Regards,
Tamilventhan S

**Comment by pr8kerl** [comment]
Yep. If using ldaps and your server is using it's own certs, then you should retrieve its's CA and configure that in lemur. Use the LDAP_CACERT_FILE option. The file should be in PEM format.
Fingers-crossed.

**Comment by selatamil** [comment]
@pr8kerl ,  Configured CA.

Regarding LDAP_BASE_DN I tried setting in all below formats but no luck

LDAP_BASE_DN = 'CN=users,CN=accounts,DC=cloud,DC=example,DC=com'
LDAP_BASE_DN = 'CN=users,DC=cloud,DC=example,DC=com'
LDAP_BASE_DN = 'DC=Users,DC=cloud,DC=example,DC=com'

ERROR: ldap error: ldap error: {'desc': 'No such object'} [in /opt/lemur/lemur/auth/views.py:119]

Please suggest. 

Thanks

**Comment by pr8kerl** [comment]
@selatamil Mmmmm.
Maybe you could try 
LDAP_BASE_DN = 'DC=cloud,DC=example,DC=com'
Otherwise I may have to see what debug options we can set.
As mentioned, I've only tested against Windows AD so we may need to tweak some options.
Will do some reading.

**Comment by selatamil** [comment]
@pr8kerl ,  I have tried that as well and tried with ldap also instead of ldaps. But no luck. 

Did you used the same configuration for Windows AD? Kindly let me know. I hope /docs/administration.rst file need not to be worried. I'm making changes only only in lemur.conf.py

Regards,
Tamilventhan S

**Comment by pr8kerl** [comment]
@selatamil Oh dear.

Do you know if your FreeIPA supports UPN (User Principal Name)??
What version of FreeIPA are you running. The ldap bind setup within Lemur is configured to bind using UPN. So maybe this is an issue.

You don't have to touch administration.rst - that is purely documentation.
Only make config changes in lemur.conf.py.

I have updated a new branch in my repo which has some debug settings.
You could either clone my [repo]( https://github.com/pr8kerl/lemur/tree/ldap-debug) and run off the ldap-debug branch, or simply copy this [file]( https://github.com/pr8kerl/lemur/blob/ldap-debug/lemur/auth/ldap.py) over your own ldap.py file.
You would then need to add an additional config to your lemur.conf.py file like so:
LDAP_DEBUG = True

This is only for testing ok.
With these settings, it should show a lot of ldap debug info in the log. Maybe this will show something.
Lets see if it produces anything useful for you. If it does I might do a PR for lemur mainline.

Lemur ldap works for me just fine when connecting to windows AD using ldaps and config as described further up. Unfortunately I haven't any other ldap servers to test against. So you may be one of the first non-Active Directory setups.
I'll try to help, but you may have to be patient in trying to find a config that works. There are a lot of variables unfortunately.

**Comment by selatamil** [comment]
@pr8kerl , Thank you for your detailed information!

I'm using FreeIPA 4.3.1. I don't think version 4.3.1 supports UPN. After adding debug steps also we are getting same error only. No additional information. 

I'm ready to wait and try different set of variables, since we are exploring it for the first time.

**Comment by pr8kerl** [comment]
@selatamil I have been having a look at how this can be done. I hope you're not in a huge rush as it may take a few days. I think as long as you can support LDAP simple bind then it **should** be fairly easy.
Using simple bind we should be able to provide just an ldap login name and password. It's the following ldap search filter that needs to know what kind of object attribute to search for (userPrincipalName, cn or uid). So I'm hopeful.

Meanwhile can you confirm for me what an example DN looks like in your ldap directory??
Are your user objects using uid, or cn??
So on my AD ldap, a user DN looks similar to...
CN=User Name,OU=Users,DC=example,DC=net
I'm expecting yours is looking like...
uid=userLogin,OU=Users,DC=example,DC=net

Thanks

**Comment by selatamil** [comment]
@pr8kerl ,
Thank you for your efforts on helping me out, definitely i'm ready to explore all the options to get it done. 

We have integrated our freeIPA with jenkins with the below configuration, please have a look if it could help us
root_DN -= dc=cloud,dc=example,dc=com
User search base =  cn=users,cn=accounts
User search filter = uid={0}
In freeIPA user options, search filter is given as below
User search fields = uid,givenname,sn,telephonenumber,ou,title

Please let me know if you need any other information. 

Thanks

**Comment by selatamil** [comment]
@pr8kerl , Yes you are right, we have to write search filter with uid.

http://blog.emfeld.com/2013/03/ldap-login-authentication-using-python.html

Will the above link help us in getting something? Kindly let me know

Thanks

**Comment by pr8kerl** [comment]
@selatamil Thanks. I've got something else to test.

Can you replace your current ldap.py with [this one](https://github.com/pr8kerl/lemur/blob/ldap-update/lemur/auth/ldap.py)??
Then in your lemur.conf.py can you add this additional config?
```
LDAP_LOGON_ATTRIBUTE = 'uid'
```
If uid doesn't work, try 'cn'.
:crossed_fingers: 

Let me know. Tx

**Comment by selatamil** [comment]
@pr8kerl , Thank you for your update!

I have replaced the ldap.py with the given one and modified lday.conf.py as below

LDAP_AUTH = True
LDAP_USE_TLS = True
LDAP_BIND_URI = 'ldaps://ldap-dev.cloud.example.com'
LDAP_EMAIL_DOMAIN = 'example.com'
LDAP_REQUIRED_GROUP = 'ipausers'
LDAP_GROUPS_TO_ROLES = {'ipausers': 'admin', 'Lemur Team DL Group': 'dl@example.com'}
# if your LDAP server has non-standard CA you may need to point to trusted CA certificate file
LDAP_CACERT_FILE = '/opt/lemur/cacerts/cert.pem'

LDAP_BASE_DN and LDAP_LOGON_ATTRIBUTE tried in below combinations

LDAP_BASE_DN = 'DC=Users,DC=cloud,DC=example,DC=com'
LDAP_BASE_DN = 'DC=Users,DC=accounts,DC=cloud,DC=example,DC=com'
LDAP_BASE_DN = 'CN=Users,CN=accounts,DC=cloud,DC=example,DC=com'
LDAP_BASE_DN = 'CN=Users,DC=cloud,DC=example,DC=com'

and
LDAP_LOGON_ATTRIBUTE = uid
LDAP_LOGON_ATTRIBUTE = cn


but still we are getting same error
ERROR: ldap error: ldap error: {'desc': 'No such object'} [in /opt/lemur/lemur/auth/views.py:119]

Thanks!

**Comment by pr8kerl** [comment]
@selatamil Oh dear.
It still feels like to me that you successfully connect to the ldap server (you don't receive an error about invalid credentials or server unavailable) but the ldap search to confirm your group membership is returning nothing. Which feels more like a config problem.

Can you confirm the exact DN for the user you are trying to authenticate with??
If so, can you mimi the search using a cmdline tool such as ldapsearch??
```
 ldapsearch -x -h ldapserverhostname -D "uid=BindUser,OU=Users,DC=example,DC=myobcorp,DC=net" -W -b dc=example,dc=net uid="BindUser"
```
I can replicate the search using a command similar to above on my server. I use "cn=" though and not "uid=". So this is where I need your help to test. You need to confirm the full distinguished name for your authenticating user and supply that to the -D option. 
Hope this makes sense? Let me know if not.
I kind of feel the LDAP_BASE_DN is incorrect for your setup and you'll need to ensure it really is correct.

**Comment by selatamil** [comment]
@pr8kerl ,

Below LDAP search worked for me
ldapsearch -x -h ldap-dev.cloud.example.com -D "uid=lemur,cn=users,cn=accounts,dc=cloud,dc=example,dc=com" -w 'password' -b  dc=cloud,dc=example,dc=com uid=lemur

and i got below outputs of DN and group details
dn: uid=lemur,cn=users,cn=accounts,dc=cloud,dc=example,dc=com
dn: uid=lemur,cn=users,cn=compat,dc=cloud,dc=example,dc=com
memberOf: cn=ipausers,cn=groups,cn=accounts,dc=cloud,dc=example,dc=com
memberOf: cn=lemur,cn=groups,cn=accounts,dc=cloud,dc=example,dc=com

Please do let me know if you need more information.

**Comment by pr8kerl** [comment]
@selatamil Thanks for that. So you based dn used in your above command is: dc=cloud,dc=example,dc=com
which doesn't quite match up to the base dn's you tried before. So here's hoping. 

So according to the above output, if you keep using the last ldap.py I provided and try these ldap settings in your lemur.conf.py...
 
```
LDAP_AUTH = True
LDAP_USE_TLS = True
LDAP_BIND_URI = 'ldaps://ldap-dev.cloud.example.com'
LDAP_EMAIL_DOMAIN = 'example.com'
LDAP_REQUIRED_GROUP = 'ipausers'
LDAP_GROUPS_TO_ROLES = {'ipausers': 'admin', 'Lemur Team DL Group': 'dl@example.com'}
LDAP_CACERT_FILE = '/opt/lemur/cacerts/cert.pem' 
LDAP_LOGON_ATTRIBUTE = 'uid'
LDAP_BASE_DN = 'dc=cloud,dc=example,dc=com'
```

Again :crossed_fingers: 

Btw, any chance you can upgrade your freeipa to 4.4 so it supports userPrincipalName?? 
I have to ask.

**Comment by selatamil** [comment]
@pr8kerl , Thanks a lot for your support. It worked.
