### ISSUE TITLE
Ability to resync destinations

### ISSUE THREAD

**Issue by aaronmell** [Netflix/lemur#935]
Does Lemur have the ability to resync to a destination on a periodic basis?
The docs don't really explain how/when the pushes happen. 

For example, I'd like to build a provider to push certs to IIS on a group of windows machines, the caveat being that the machines will change over time, and as new machine are added, I would like to be able to push certs to the new machine.  Is there any way to handle that in lemur?

**Comment by kevgliss** [comment]
You would most likely combine the ideas of auto-rotation and endpoints to accomplish what you need. Destinations are more for external systems that you would hand a certificate off to (think AWS, Hashicorp Vault, Kurbernetes, etc.,)

Lemur uses a daily cron to determine if certificates are expiring, it will re-issue them and then replace/rotate them. The replacement process looks for any existing endpoints and attempts publish/assign the new certificate to the endpoint where the previous certificate was deployed.

If you take a look at the AWS plugin:
https://github.com/Netflix/lemur/blob/98907e66e9230b2019d328198b287eda7c7fc046/lemur/plugins/lemur_aws/plugin.py#L246

The source plugin defines how to find and deploy to endpoints. If you were to write a similar plugin for your IIS/Windows, I believe Lemur would be able to re-issue and redeploy them for you.
