### ISSUE TITLE
node vs nodejs binary

### ISSUE THREAD

**Issue by putz612** [Netflix/lemur#944]
I am trying to setup lemur on a fresh install of Ubuntu 16.04.3 and running into lots of errors during install.  It looks like the latest version of the nodejs package in Ubuntu do not provide a symlink from nodejs to node and quite a few of the packages fail to install due to some wanting node vs nodejs.  
```
--> Installing dependencies
npm install

> optipng-bin@3.1.4 postinstall /lemur/lemur/node_modules/optipng-bin
> node lib/install.js

sh: 1: node: not found
npm WARN install:optipng-bin@3.1.4 optipng-bin@3.1.4 postinstall: `node lib/install.js`
npm WARN install:optipng-bin@3.1.4 spawn ENOENT

> jpegtran-bin@3.2.0 postinstall /lemur/lemur/node_modules/jpegtran-bin
> node lib/install.js

sh: 1: node: not found
npm WARN install:jpegtran-bin@3.2.0 jpegtran-bin@3.2.0 postinstall: `node lib/install.js`
npm WARN install:jpegtran-bin@3.2.0 spawn ENOENT

> gifsicle@3.0.4 postinstall /lemur/lemur/node_modules/gifsicle
> node lib/install.js

sh: 1: node: not found
```

Not really sure how to best handle this in the instructions, either create the symlink to from nodejs to node or install node via nodesource.  I have seen both mentioned online.  Looking for ideas on getting this off the ground.

**Comment by kevgliss** [comment]
@putz612 somehow this fell through the cracks... Have you run the following command on your new ubuntu instance?

`$ sudo apt-get install nodejs python-pip python-dev python3-dev libpq-dev build-essential libssl-dev libffi-dev libsasl2-dev libldap2-dev nginx git supervisor npm postgresql`

http://lemur.readthedocs.io/en/latest/quickstart/index.html#installing-build-dependencies

**Comment by spensireli** [comment]
Creating the symlink did the trick for me.  I recently ran into the same issue recently.
ln -s /usr/bin/nodejs /usr/bin/node

**Comment by jchuong** [comment]
+1 on this, would like to know why we use Nodesource instead of what is in official repos.

Personally, I am now using `update-alternatives --install /usr/bin/node node /usr/bin/nodejs 1` and hasn't blown up in my face yet.

**Comment by kevgliss** [comment]
@jchuong I'm open to switching... I'm not familiar enough with Node to know that the benefits of using one particular version of node or another (it's only used as the JS build system within Lemur).

**Comment by vsnine** [comment]
Looks related to my issue during quickstart: [PR #1004](https://github.com/Netflix/lemur/pull/1004)

**Comment by kevgliss** [comment]
@putz612 please let me know if the changes made in #1004 don't solve your issue.
