### ISSUE TITLE
Add support for Mandrill as a notification method

### ISSUE THREAD

**Issue by t0xicCode** [Netflix/lemur#95]
The current lemur_email notification system only supports ses or smtp. Mandrill is a popular transactional mail service (built by the guys that make mailchimp).

Adding support for Mandrill would be a nice addition. I have started development on a mandrill plugin (t0xiccode/lemur_mandrill), but rolling this functionality into the "core" lemur_email plugin would make it easier to get started for organisations using it for emails.

**Comment by kevgliss** [comment]
Sounds good, feel free to fork and modify the original email plugin to add mandrill support. I think it would make sense as this is still 'email' and not necessarily a different notification type, say SMS or IRC which I would rather have in a completely separate plugin.
