### ISSUE TITLE
Configuring SES credentials for lemur to send email notifications

### ISSUE THREAD

**Issue by selatamil** [Netflix/lemur#954]
Hi,

Kindly let me know the additional configuration required in lemur.conf.py to activate SES email sender. 

I did the complete SES policy setup for the attached IAM role and LEMUR_EMAIL = 'lemur.example.com' in lemur.conf.py and the email got verified in SES as well. But still when i execute lemur notify expiration i'm getting 0 notification. 
Starting to notify subscribers about expiring certificates!
Finished notifying subscribers about expiring certificates! Sent: 0 Failed: 0

FYI: For testing I have created notifications for 8,9,10 and 12 months interval, but no email notifications received. 

Kindly help.

**Comment by selatamil** [comment]
I mean, I did the complete SES policy setup for the attached IAM role and LEMUR_EMAIL = 'lemur.example.com' in lemur.conf.py and the email got verified in SES as well. But still when i execute lemur notify expiration i'm getting 0 notification. 
Starting to notify subscribers about expiring certificates!
Finished notifying subscribers about expiring certificates! Sent: 0 Failed: 0

FYI: For testing I have created notifications for 8,9,10 and 12 months interval, but no email notifications received. 

Kindly help.

**Comment by kevgliss** [comment]
Judging from your output Lemur it looks like it's not necessarily a problem with SES, but with your notifications. Essentially Lemur isn't finding any certificates to notify. 

One thing to note is that the notifications are supposed to be run on a daily cron. Each day, Lemur will attempt to gather all notifications that should trigger that day, and then generate a message for all certificates attached to that notification. 

I would test your setup by generating a 1 day notification and then creating a certificate (you can use the cryptography issuer) that expires within the next day. 

Its also important to note that Lemur will only notify on the given day that the notification specifies. So if you have a 12 month interval it will only notify on the day that is exactly 12months from the certificate expiration. It does not continually notify after it hits that threshold.

**Comment by selatamil** [comment]
@kevgliss  Thank you for your response. Do we need to mention anywhere in lemur.conf.py to send mails from SES. I have verified Email address in SES and configured policy for the instance profile to send SES mail. Mentioned the verified Email address as LEMUR_EMAIL. Is that enough?

Please let me know.

**Comment by kevgliss** [comment]
You need to specify `LEMUR_EMAIL_SENDER='ses'` See: http://lemur.readthedocs.io/en/latest/administration.html#notification-options
