### ISSUE TITLE
Running lemur init from a programmatic standpoint

### ISSUE THREAD

**Issue by SecurityInsanity** [Netflix/lemur#982]
We're looking to stand up lemur, and we're looking to build an AMI. During this AMI Build phase if specified through a variable we'd like to run a script to initialize the database. Unfortunately it appears `init` requires user input/output that's important.  

Any docs on running this from a programmatic standpoint?

**Comment by kevgliss** [comment]
`init` is only ever run once, on a fresh install/database. We build our AMIs in much the same way without issue.

**Comment by SecurityInsanity** [comment]
So do you guys run `init` from a manual computer or as part of the build process? If part of the build process, how do you get it to run without waiting for input?

**Comment by kevgliss** [comment]
We only run it once if we have a new DB coming up. In practice this hasn't happened in years. So is not part of the build process. Essentially `init` just sets up some default users/roles in the database.  

For a new install yes we would run it once manually.
