### ISSUE TITLE
can we install lemur in Amazon Linux?

### ISSUE THREAD

**Issue by selatamil** [Netflix/lemur#983]
can we install lemur in Amazon Linux? I'm getting blank page on browser and below error while starting lemur. Kindly help.

ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory

Regards,
Tamilventhan S

**Comment by selatamil** [comment]
@kevgliss @pr8kerl  Kindly let me if we can use Amazon linux to run Lemur application.

**Comment by kevgliss** [comment]
It has not been tested on Amazon Linux (only Ubuntu is officially supported).

**Comment by selatamil** [comment]
Thank you @kevgliss
