### ISSUE TITLE
Can we generate CSR for submitting ssl enrollment 

### ISSUE THREAD

**Issue by selatamil** [Netflix/lemur#987]
@kevgliss Is it possible to generate CSR in lemur WEB GUI to manually submit SSL enrollment with third party certificate providers like comodo.  If yes please let me know the procedure? 

Regards,
Tamilventhan S

**Comment by kevgliss** [comment]
@selatamil this is currently not possible.

**Comment by jchuong** [comment]
I have a plugin for exporting CSR already.  I can make a pull request later.
